openatv/enigma2

- lib/service/servicemp3.cpp
**Bug description:** changing of delay for external subtitles required a restart of video. This was because the delay setting (and the fps conversion as well) was applied during reading subtitles from disk, which happen when the playback starts. 
**Fix:** the delay setting is now taken into account when the subtitles are pushed to screen. This allows for instant effect.
**Bonus fix:** the delay setting read from config file must be divided by 90 because it is stored in pts, not in ms. Looks like the delay for external subtitles never worked properly because the minimum delay 0.5s in settings pane resulted in 45sec real delay (and required video restart of course).
> Fixed: adjusting of external subtitles delay required video restart

- data/setup.xml
- lib/gui/esubtitle.cpp
- lib/gui/esubtitle.h
- lib/python/Components/UsageConfig.py
- lib/python/Screens/AudioSelection.py
- added new setting "HI-cleanup for external subtitles (yes/no)" under "Main menu -> Setup -> System -> Extended System -> Subtitle settings";
- when active the parts of subtitles intended for the hearing impaired are automatically removed (e. g. "(THUNDER RUMBLING)" or "[GRUNTS]") making the subtitles to better suite the needs of people without hearing difficulties watching with audio in a foreign language;
- the quick subtitles menu (activated via "Subtitles-key -> Red-key") was also extended with the new setting;
- the subtitles are cleaned up when pushed to screen; changing the setting has an immediate effect and doesn't require restart of the video.
> new setting to cleanup hearing impaired subtitles

- lib/python/Screens/CronTimer.py
Set the same text as [CronManager]
> [CronTimer.py] fix for translation

- lib/dvb/scan.cpp
To overcome scanning conflict on TPs with same onid/tsid
> Invalid ONID/TSID on 26.0E & 7.0E

- lib/dvb/epgcache.cpp
- lib/dvb/epgcache.h
This is very useful if epg data is send on 2 or more different pids or use non stardart one.
Usage:
Create a file "/etc/enigma2/epgpids.cusom" and fill in the format
Orbital position | TSID | ONID | Custom pid to use
The values ​​can be decimal or hexadecimal (0x ...), and combined
For orbital position using integers where 1 means 0,1 ° (19,2°E -> 192)
For orbital position can be used as negative numbers (0,8°W -> -8 or 3592)
examples:
390 17 28 299 # 39°E 12688V, epgpid to use: 299
0x186 0x11 0x1c 0x12b # Same, but in hexadecimal format
390 17 28 0x12b # Or combined
> Add possibility to set custom epgpid from whitch to grab epg data.

- lib/python/Components/Converter/MovieInfo.py
Shows the size of the file in gigabytes (with two digits for megabytes) when it is higher than 1024 MB. (E.g. 4.35GB)
> File size in GB with 2 digits when file is +1024MB

- lib/python/Screens/InfoBarGenerics.py
Allows any skin to use SecondInfoBarECM.
> SecondInfoBarECM available in all skins

- lib/python/Components/UsageConfig.py
- lib/python/Screens/InfoBar.py
Option “Allow quit movie player with exit” was extended with new possible value “Behave like stop-button”. This allows to use exit-button just like stop-button. In particular when option “Behavior when a movie is stopped” is set to “Return to movie list” the button “Exit” returns to movie list too, which was not possible before (it could be configured to return to previous service but not to movie list). That's similar to how EMC behaves.
> Option to stop movie player with exit-button

- lib/python/Screens/ButtonSetup.py
- lib/python/Screens/InfoBarGenerics.py
New function “Show subtitle quick menu” is now available in Hotkey setup. It shows subtitle quick menu directly. This menu is otherwise accessible via “Subtitle selection (Text-button) -> Subtitle Quickmenu (Red-button)” which requires more button clicks and shows unnecessary intermediate dialog. The subtitle quick menu is often useful to sync external subtitles in movie player and being able to show the quick menu directly is a big advantage.
Special case: if no subtitle stream is selected the function shows subtitle stream selection dialog.
**New function in hotkey dialog:**
**Subtitle quick menu:**
I personally assigned the **Text-button** to the new function. The text-button by default shows **Subtitle selection**. Now if no subtitle stream is selected the "Subtitle selection"-dialog …
> hotkey for subtitle quick menu

- lib/python/Components/UsageConfig.py
- lib/python/Screens/AudioSelection.py
Originally the range for external subtitle delay was “-10..+20 seconds”. When using subtitles from other releases it is sometimes necessary to adjust subtitles using larger offsets. For example releases may or may not include summary of previous episodes, which can easily take one or two minutes at the beginning of episode.
To solve the problem the range for the delay setting was extended to “-600..600 seconds”. Since the change step is just 0.5 seconds it was not comfortable to adjust large delays. In order to cope with such a large range of possible values the “quick subtitle menu”-dialog was extended to process numeric keys to switch between values with larger steps:
- "1" and "3" change delay -0.5 and +0.5 seconds respectively;
- "4" and "6" change delay -5 and +5 seconds;
- "7" and …
> extended range for external subtitle delay

- lib/python/Screens/AudioSelection.py
After upgrading from OpenATV 4.2 to 5.3 I've found that changing of external subtitle delay (via quick subtitle menu) causes pausing of playback. That's how the effect appeared:
- make one change to delay - the playback pauses;
- make another change - the playback resumes;
- and go on.
When the delay is changed a special resync-routine pauses and then immediately resumes the player (this is necessary to reread subtitles):
```python
def resyncSubtitles(self):
self.infobar.setSeekState(self.infobar.SEEK_STATE_PAUSE)
self.infobar.setSeekState(self.infobar.SEEK_STATE_PLAY)
```
This code wasn't changed since v4.2, where it worked flawlessly. I guess the change of behavior is caused by the upgrade of GStreamer (from 0.10 to 1.x), which now probably cannot process pause and resume commands at …
> fixed external subtitle resync

- lib/python/Components/UsageConfig.py
because 'true' deformed the subtitles sometimes
> [UsageConfig] change 'dvb_subtitles_centered' to false

- data/setup.xml
- lib/python/Components/UsageConfig.py
- main/enigma.cpp
When setting up an universal remote control I've faced an inability of using long button presses in macros. Why would I want this? Because there is a number of functions (to setup by editing of keymap.xml or via Hotkey setup screen) which can be useful in macro sequences, such as "discrete power on" and "discrete power off" commands. Sacrificing one physical button for each function isn't practical. It's better to assign such functions to long presses. Only if we could execute them from macro sequences...
To work around this problem I've added an emulation of long button presses via two normal (short) presses. One button on the remote must be defined for the long press emulation purpose (for example a rarely used `TV` or `Radio`). Then a normal (short) press on the emulation button …
> Long button press emulation

- data/keymap.ntr
- data/keymap.u80
- data/keymap.xml
- lib/python/Screens/InfoBarGenerics.py
Fixed two things:
1.  audio-key in “audio selection screen” were supposed to switch between pages “audio selection” and “subtitle selection” but that did not work. The code for that was there but the key mapping was incorrect. Fixed:
2. Long press on audio-key were supposed to toggle digital audio downmix, but that did not work either, for the same reason (key mapping issue), now it does:
> Audio-key fix

- lib/python/Screens/ButtonSetup.py
- lib/python/Screens/InfoBarGenerics.py
Added two commands for hotkeys setup:
1. Enable digital downmix;
2. Disable digital downmix.
These are discrete commands which change state of digital downmix setting when necessary or do nothing if the setting were in required state already.
I use these commands on an universal remote control in macro sequences **watch tv** (which among other things enables downmix; audio comes from TV) and **watch movie** (which among other things powers on AV-receiver and disables downmix). Discrete commands are required to ensure the downmix option is set correctly regardless of its previous state.
> discrete commands to on/off digital downmix

- lib/python/Screens/InfoBarGenerics.py
This is a follow-up to #401.
Fixed: hotkeys with short key presses did not work with new discrete commands for digital downmix on/off.
> addition to #401: fix for short key presses

- lib/dvb/scan.cpp
Adding another invalid ONID/TSID (126/30300) for TPs 11304H and 11262H on 7.0E to overcome the TPscan overwrite.
>  Invalid ONID/TSID (126/30300) on 7.0E

- lib/python/Screens/UserInterfacePositioner.py
Previously (tested on dreambox dm7020hd) changing position or size did not have any effect until GUI is restarted. Modified the code to also set dst_apply to 1 to activate the changes so they become visible at configuration time.
> Ensure the settings become visible during configuration

- lib/dvb/epgcache.cpp
Save mhw(new)-epg after update can cause segfault.
Cache must be saved on exit or by external call.
It solves segfault when try to update mhw-epg from SID 30150
and EPG is set to 4 or more days.
> epgcache.cpp: do not save cache on MHW2

- lib/python/Screens/EpgSelection.py
17:38:16.784 Traceback (most recent call last):
17:38:16.784   File "/usr/lib/enigma2/python/mytest.py", line 26, in <module>
17:38:16.785     from Screens import InfoBar
17:38:16.785   File "/usr/lib/enigma2/python/Screens/InfoBar.py", line 4, in <module>
17:38:16.785   File "/usr/lib/enigma2/python/Screens/MovieSelection.py", line 342, in <module>
17:38:16.785   File "/usr/lib/enigma2/python/Screens/ParentalControlSetup.py", line 10, in <module>
17:38:16.786   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 21, in <module>
17:38:16.786   File "/usr/lib/enigma2/python/Screens/EpgSelection.py", line 1777
17:38:16.786     self.skinName = 'EPGSelection'
17:38:16.787                                  ^
17:38:16.787 IndentationError: unindent does not match any outer …
> EPGSelection - fix indentionError introduced in #478

- lib/dvb/frontend.cpp
SNR fix for Vuplus DVB-S NIM(AVL6222) (DVB-S2) with a maximum of 14.9 dB.
> Fix SNR for Vuplus DVB-S NIM(AVL6222) (DVB-S2)

- lib/python/Screens/AudioSelection.py
Renaming `Channel` to `Audio Channel` as its badly named, because the naming is used for more than 1 function.
For example this `Channel`  refers to the `Audio Channel`, and in the add Timer section it refers to the `TV channel`.
(Another alternative would be to add a space at the end of the name to allow 2 translation strings, but i think `Audio Channel` better reflects the function anyway.)
> Renaming Channel to Audio Channel in AudioSelection

- lib/python/Plugins/Extensions/Infopanel/QuickMenu.py
* Changed the `Download plugins` description to `Setup Plugins` as it was identical/also used in the plugin overview menu. (L243)
* Changed the `Skin Setup` 2x description to `Select LCD Skin` and `Select Enigma2 Skin` as it was used two times as a description (L256 & L257)
* Changed the `Setup Videomode` description to `Setup Video/Audio` as it was used two times as a description. (L241 & L310)
* Changed the `Service Searching` 2x description to `Automatic Service Searching` & `Manual Service Searching` as it was used two times as a description. (L326 & L327)
* Changed the `Settings...` description to `OSD Setup` as it was already used for a function. (L251)
> Updated QuickMenu.py descriptions

- mytest.py
Setting wakeup time to time in the past reboots Azbox (mini)ME models instead of deep standby.
> Dont set wakeup time in the past for Azbox (mini)ME

- lib/python/Screens/Satconfig.py
so we don´t need another translation
> [Satconfig.py] fix typo "advanced" / same as line 102 "Advanced"

- lib/service/servicemp3.cpp
- lib/service/servicemp3.h
Major changes into the main e2 gstreamer player.
This change requires the latest version of dvbmediasink.
The sinks will now always be made to use dvbmediasink.
This avoids the use of autosink which could sometimes use the alsasink.
The mem leak by each reinitiation of sinks is gone.
The sinks will be made up on the first media who plays.
Later on that sink will remain in use as long e2 is running.
When playing audio only media the audio sink will be synchronized with gstreamer,
This gives a better and correct start stop and next media for all media inclusif very short.
Nice for audio playlists.
The buffering event has been removed and is not sent to the py plugins anymore.
This event was far to cpu intensif and sometimes the cause of non start from live media.
However the buffering is …
> Big changes into servicemp3.cpp.

- lib/python/Components/Converter/ServiceInfo.py
Would it be acceptable to allow 2152-2160 as 4K?
On Astra1 19.2 is a UHD channel broadcasting in 3840x2152. Currently its not recognised as a 4K channel.
http://www.satindex.de/frequenz/10714/
> Modified resolution recognised as 4K

- lib/python/Screens/BoxPortal.py
when name string translated, may not picked up in list as installed plugin
> pass translatable strings as plugin names

- lib/service/servicemp3.cpp
- lib/service/servicemp3.h
Adapted to use new properties e2-asyn and e2-sync.
Stopped the unneeded flush at media start after async completed.
Corrected subtitle dificult start up on suvtitle change.
Corrected use of cuts file. Now 100 % ok without emc.
Emc can now be adapted to not use cuts file anymore for,
resumepoints .
Requires the very last dvbmediasink openatv-dev
modified:   lib/service/servicemp3.h
> A lot of extra changes.

- lib/python/Components/Converter/TextCase.py
This allows UTF-8 special characters (é, ç, ñ, etc...) to be turned into upper or lower case.
> UTF-8 special characters now working

- lib/python/Screens/AutoDiseqc.py
This commit allows:
- to tune automatically Hispasast (30W).
- to translate the tuner state.
- to translate the name and position of the satellites.
> Hispasat added and "tuner_state" translatable

- lib/python/Screens/Standby.py
Scripts must be located under /usr/script and Scripts must have permissions to execute (chmod 755).
/usr/script/StandbyLeave.sh (Script is used, when leaving Standby)
/usr/script/StandbyEnter.sh (Script is used, when entering Standby)
Thanks to arn354 for the code/changes in OpenMips:
https://github.com/openmips/stbgui/commit/53bd3ef93bbd6e264ee572ce9ff0a2ae27d4681f
> Standby.py - Add possibility to run a Script when Entering/Leaving Standby

- enigma2.bb
Currently the LCD skin for the ultimo4k (800x480) is not shown on the feed for download/install.
> Missing colorlcd800 entry in enigma2.bb

- lib/service/servicemp3.cpp
Gstreamer recipe updated key-unit-seek is always ok no.
Insert pause protection to not pause if already paused.
> Gstreamer updated back to key unit seek

- lib/service/servicemp3.cpp
This solves the media stop when switching to higher resolution chunk.
Now the high resolution chunk is tried first.
> Selecting the high badwith resolution for hls streams.

- lib/python/Components/Lcd.py
- workaround for boxes like sf4008 who need hex as value to set it correct
VFD_initial_scroll_delay
VFD_final_scroll_delay
VFD_scroll_delay
- add Option of 3 seconds
> [Lcd.py] add workaround for boxes who need hex as value

- lib/python/Components/UsageConfig.py
https://github.com/openatv/enigma2/blob/DEV/lib/python/Components/Renderer/Cover.py#L21
> [UsageConfig.py] workaround to show Cover in LCD-Displays

- lib/python/Screens/InfoBarGenerics.py
fix skin error ...
09:09:03.2860 {   } skin.py:1086 readSkin [SKIN] Parsing embedded skin <embedded-in-'HideVBILine'>
09:09:03.2866 {   } skin.py:1325 readSkin [SKIN] processing screen <embedded-in-'HideVBILine'>:
09:09:03.2871 { E } skin.py:408 applyAll [Skin] Error: {MetrixHD/skin.MySkin.xml}: color '0' must be #aarrggbb or valid named color. Please contact the skin's author! 
09:09:03.2873 {   } Screens/Screen.py:151 show [SCREENNAME]  HideVBILine
> [InfoBarGenerics.py] fix skin error / HideVBILine

- lib/python/Components/Renderer/LcdPicon.py
- lib/python/Components/Renderer/Picon.py
Flexibility with service types in picons. In essence radio
This also allows for IPTV services starting with something different to 4097, ( more correctly different to 1).  
This will partly address following issue:
https://github.com/openatv/enigma2/issues/707
> [Picon] Different IPTV/Service types 

- lib/dvb/db.cpp
This commit is to replace a workaround in OpenWebIF ( https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/2629beca15b8322222e8b08d2babce2380e1bfc3 ) and ABM ( https://github.com/oe-alliance/AutoBouquetsMaker/commit/89771c6a153f06bb2bd1b7c6b801e58ce6f65e60 ) that should really be handled in enigma cpp code.
Recreate bug as follows:
1) Retrieve lamedb from STB over FTP.
2) Manually edit a channel name.
3) Send lamedb to STB over FTP.
4) Call http://<STB-IP>/web/servicelistreload?mode=0
5) Check channel name.
In the case of the current code the service name does not change.
This makes it impossible to correctly reload service lists.
Only way to get clean reload with current code is to put the STB to sleep (init 4).
The code in this commit cleans enigma2 before the reload so the …
> [db.cpp] Clear services before reloadServicelist

- lib/python/Screens/Standby.py
if the minitv of lcd-display´s is on, some boxes can crash if they go to deep-standby
> [Standby.py] fix a deep-standby-crash on some boxes

- lib/python/Screens/InfoBarGenerics.py
This commit allows to use "FullDescription" widget in SecondInfobar screen.
e.g. <widget name="FullDescription"...
> FullDescription widget in SecondInfobar

- lib/python/Screens/InfoBarGenerics.py
It shows the sub-title field when no description is provided by the EPG.
> FullDescription update

- lib/python/Components/Lcd.py
Damit wird auch beim Starten der Box der richtig LCDMiniTVMode bei den Gigablues gesetzt, bzw. nicht durch den anderen Aufruf
>> config.lcd.minitvmode.addNotifier(setLCDminitvmode) <<
wieder auf "0" gesetzt.
> [lcd.py] fix set LCDModeMinitTV at the start of the box

- lib/python/Screens/MultiBootStartupGB.py
because SetupSummary expected "config" as "list" and here is "StaticText"
> [MultiBootStartupGB.py] change LCD-Screen to SimpleSummary

- lib/python/Plugins/Extensions/MediaPlayer/plugin.py
11:02:22.4455 {   } Screens/Screen.py:151 show [SCREENNAME]  SubtitleDisplay
11:02:22.4465 { D } Traceback (most recent call last):
11:02:22.4466 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 68, in action
11:02:22.4470 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
11:02:22.4472 { D }   File "/usr/lib/enigma2/python/Screens/AudioSelection.py", line 477, in keyOk
11:02:22.4473 { D }   File "/usr/lib/enigma2/python/Screens/AudioSelection.py", line 299, in enableSubtitle
11:02:22.4474 { D }   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 4918, in enableSubtitle
11:02:22.4476 { D }   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 4883, in doCenterDVBSubs
11:02:22.4478 { D } AttributeError: …
> [MediaPlayer] fixes a crash when activating the dvb-subtitles

- lib/dvb_ci/dvbci.cpp
It seems that removing the CI resets input source to wrong input.
Instead of reseting to tuner leter 0->A,1->B,etc. it resets to A.
Writing the correct input should fix the problem after removing the CI.
> dvbci: properly reset the input source on CI removal

- lib/dvb/sec.h
- lib/python/Components/EpgList.py
- lib/python/Components/config.py
Fix issues reported in opendreambox git
---------------------------------------
- use colon as hour delimiter instead of a single point in multiepg
- fixed some tuner config related issues
- fixed crash when more than 4 satellites are configured with multiple fbc tuners
> Add fixes from opendreambox git

- lib/python/Screens/About.py
Translators can now change the date format to their native format
example for german
msgid "%Y-%m-%d"
msgstr "%d.%m.%Y"
> [about.py] make some dateformats translateable

- lib/python/Screens/NetworkSetup.py
Pressing ok key, an input box is opened.
Entered string is used in command "openvpn start" as config file name.
So you can change in gui the openVpn config file you want to load.
> Added possibility to choose a config file for OpenVpn

- lib/dvb/frontend.cpp
restore the original logic of eec6ad54811373f42920343213c42896401f7c2d,
which was to:
-use DTV_ENUM_DELSYS on recent DVB_API versions
-use FE_GET_INFO.type on older DVB_API versions
-fallback to FE_GET_INFO.type when DTV_ENUM_DELSYS fails
commit 7e9e38e9ad641161abbc9e0d2ed5a97f27478074 and
436fb8d36a19c2a3045de388ecb832aa54c21a0b break the fallback logic by
introducing debug log after the 'else' clause.
As a result, the fallback was always executed, even when DTV_ENUM_DELSYS
produced valid results.
On multitype frontends, where the initial value of FE_GET_INFO.type is
not necessarily equal to the current value of FE_GET_INFO.type after
having iterated through all delsys, this could mean that frontend info
was stored to the wrong m_delsys entry. (e.g. DVB-T frequency_min/max
overwriting …
> frontend: fix DTV_ENUM_DELSYS fallback logic

- data/unicable.xml
Add Inverto IDLU-UST110-CUO4O-32P according to:
http://inverto.tv/multiswitch/308/unicable-ii-cascadable-switch-with-terrestrial-input-and-4x-dcss-scr-legacy-terrestrial-outputs
> Add Inverto IDLU-UST110-CUO4O-32P

- data/keymap.ntr
- data/keymap.u80
- data/keymap.xml
- doc/VIRTUALKEYBOARD
- lib/python/Screens/VirtualKeyBoard.py
* Rework VirtualKeyBoard Shift functions
Change the name of the current Shift function to Caps Lock.  Add a new Function called Shift.  The new Shift function allows the selection of a different shift level for the next character only.  Once the selection is made the previous shift level is immediately restored.
The new Shift function has been assigned to the YELLOW button.  The Locale function that was on the YELLOW button has been moved to the TEXT button.  This was done as it is expected that the new Shift function could be used more frequently than the Locale function.
**NOTE:** This change should have a matching change to all skins to add the new vkey_shift.png icon image.
* [VIRTUALKEYBOARD] Add reworked shift information
Add information about a new feature for VirtualKeyBoard that …
>  Rework VirtualKeyBoard Shift functions

- lib/python/Screens/VirtualKeyBoard.py
This change moves the character glyph / text / icon to the top layer of the image stack.  Previously the highlight image was at the top of the stack.  This change allows skin designers to have more options in skinning the VirtualKeyBoard with fewer compromises.
> [VirtualKeyBoard.py] Reorganise image overlay stack

- lib/python/Tools/Directories.py
The bulk of the changes are in the "resolveFilename" method.  Some of the changes are to clean up the code, some to correct bugs, some to generate consistent results and others to add new functionality.
- This code has undergone a PEP8 clean up.
- The original code was difficult to read.  The refactor should make the code more self explanatory.  More comments have been added to aid readability.
- The previous code tested if the system paths existed and, if not, tried created them at the end of the process.  Moving this logic earlier avoids wasting processing if the required paths can't be created.
- The code to create the system paths now tries to create the entire path tree and not just the lowest level directory.
- One of the uses for the "resolveFilenames" method is to return the …
> [Directories.py] Refactor and enhance the code

- lib/python/Tools/Directories.py
- For the SCOPE_CURRENT_SKIN and SCOPE_ACTIVE_SKIN scopes modify the scope's base path to reflect the currently selected skin.
- Use "os.path.dirname()" to simplify finding the skin and display skin names.
> [Directories.py] Correct reported issues

- data/menu.xml
The current name does not mention anything about tuners. Tuners and scanning covers both terms
(cherry picked from commit 92e8e5ecf62fb8eeb801e985578dc59fa7dab467)
> [Menu] Rename service searching

- lib/python/Tools/Directories.py
This change renames the resolution search directories from "skin_\<resolution\>" to "skin_fallback_\<resolution\>" to avoid confusion expressed by some developers.
The "skin_\<resolution\>" names are still in place to maintain functionality.  They will be removed when the skin repository updates are completed.
> [Directories.py] Change resolution path name

- lib/python/Tools/Directories.py
- Improve copying of stat and times in "copyfile" and "copytree" methods.
- Don't abort the file times copy if the file mode copy fails.
- Provide more accurate failure logging.
- Improve the "stat" import.
- Remove deprecated "skin_<resolution>" search.
- Update and correct deprecation comments.
> [Directories.py] Apply corrections and enhancements

- lib/python/Components/ActionMap.py
- Use a slightly longer form of initialisation for the ActionMap __init__. This format avoids an issue where the initialisation parameters become persistent across all invocations of this code. This is inappropriate and undesirable.
In essence the problem with the original code is that it appears to be an efficient way to create a default empty list and dictionary. What actually happens is that these items get created as a persistent objects. Every invocation of the \_\_init\_\_ method that doesn't specify the parameters will use that SAME (persistent) objects. Any changes to either object will persist (be remembered) and be carried forward into every other invocation of this method! THIS IS NOT WHAT SHOULD HAPPEN!
See  https://docs.python-guide.org/writing/gotchas/
- Add new logging code …
> [ActionMap.py] Improve initialisation and logging

- tools/enigma2.sh.in
This change adds the option for skins to include a backdrop.mvi image at the top level of the skin that will be used when that skin is selected.
The code first checks to see if a skin is defined in the "settings" file and uses it if found. If no skin is identified then the "skin.pyo" file is searched to see if a built-in skin has been defined. If found then that will be used. If no skin associated backdrop is identified then the code will progress to the original search in "/etc/enigma2/" and finally use the image in "/usr/share/".
> [enigma2.sh.in] Add option for skin backdrop

- lib/python/Screens/Volume.py
Add the VolumeText variable to allow skins to also display the current volume as a numeric value.
(Also improve the volume log message.)
> [Volume.py] Add VolumeText screen variable

- lib/python/Screens/VirtualKeyBoard.py
Use None rather than a number (-1) to trigger the initialisation of the cursor pointer (an integer index).  While the code works now the use of None will protect against any future changes in valid number range.
> [VirtualKeyBoard.py] Use None rather than -1 for currPos

- lib/python/Plugins/SystemPlugins/IceTV/API.py
- lib/python/Plugins/SystemPlugins/IceTV/__init__.py
- lib/python/Plugins/SystemPlugins/IceTV/plugin.py
Fetch only user's selected channels to the IceTV channel map
- Add UserChannels class to the IceTV API. UserChannels is an AuthRequest that requests only the user's enabled channels.
- Make EPGFetcher.getChannels() return only the user's selected channels. Rename the old getChannels() to getAllChannels().
- Precursor to allowing batching of show requests to channel groups.
Allow batching of EPG fetches to limit memory use
- Allow the EPG to be fetched in batches of channels.
- The aim is to reduce the maximum memory requirement when downloding and processing the EPG. The larger (~140 channels, 14 days) German EPG appeared to be causing OOM problems on some boxes.
- config.plugins.icetv.batchsize controls the maximum size of the batch.  When set to 0, the EPG is loaded in a single fetch as …
> Icetv batch fetch

- lib/python/Plugins/SystemPlugins/IceTV/API.py
- lib/python/Plugins/SystemPlugins/IceTV/plugin.py
Change EPGFetcher.makeChanShowMap() to construct the map over
the Pythonised JSON data instead of converting it all into Python input
form in one go.
Move the conversion of the Pythonised JSON into the new method
EPGFetcher.convertChanShows() that does that conversion over a single channel.
Change the EPGFetcher.processShowsBatched() to call convertChanShows()
on each channel entry in channel_show_map.
This saves 20-30% of maximum memory use during EPG processing.
Bump version number.
> Convert and import EPG data channel at a time

- lib/python/Plugins/SystemPlugins/IceTV/API.py
- lib/python/Plugins/SystemPlugins/IceTV/plugin.py
Handling the much larger icetv.de EPG needs some performance improvements.
[IceTV] Speedup of time conversion
Use new start_unix and end_unix fields in shows to make time
conversion in the EPG faster.
[IceTV] Cache genre mappings
Speed up the processing of genre names to genre EIT codes
by caching known conversions.
This is more helpful in the icetv.de EPG, because of
the larger number of events (~280000) and because the
icetv.de data typically has more genres/event.
Bump version number.
> [IceTV] Optimise some aspects of EPG processing

- lib/python/Plugins/SystemPlugins/IceTV/API.py
- lib/python/Plugins/SystemPlugins/IceTV/plugin.py
Sorry, I know that having unrelated commits in a single PR is not good practice, but I needed to get these finished today, and they would be likely to cause merge problems if they were all branched from the same base.
[IceTV] Fix inconsistent indenting
Fixed some indenting that was done on an 8-character indent instead
of a 4-character indent.
[IceTV] Fix bug in genre mapping caching
Cached genre mappings weren't being added to the list of genres,
and the unmapped eit code was being added to cache instead of the
remapped value.
So little code... so many bugs.
Bump version number.
[IceTV] No translation of addLog messages
Remove the translation of addLog() mesages, to make things easier
for developers who don't know the user's selected language.
> Minor IceTV fixups

- lib/dvb/epgcache.cpp
[eEPGCache] Speed up insertion of events into EPG
By taking advantage of the fact that the EPG per-channel list of
events by time is non-overlapping, the check for overlaps when a
new event is added in eEPGCache::sectionRead() can be reduced from
O(N) to O(log N), where N is the number of events in the channel's
EPG.
This improves both the processing speed of EIT EPG data and imported
EPG data (e.g. IceTV), because eEPGCache::sectionRead() is common
to both.
Also drop any zero-length events. Handling them would make
the speedup slightly more complicated.
For Australian IceTV data, it reduces the import time for the EPG
from ~0.67 sec to ~0.14 sec (4.8x), for an 8-day German IceTV EPG
(130+ channels), it reduces the import time from ~16.5 sec to ~2.32
sec (7.1x).
The production German …
> Speed up insertion of events into EPG

- lib/python/Tools/Directories.py
This commit corrects the search order for  skin, display and font objects to ensure that user locations are searched before the default locations.
> [Directories.py] Correct search orders

- lib/python/Tools/Directories.py
Commit notes from Littlesat (OpenPLi):
Check mediafiles in use on basename only.  E.g. when you have a mounted drive the path could be different so your box could not go into deep standby.
> [Directories.py] Synchronise with upstream repositories

- lib/python/Plugins/SystemPlugins/IceTV/API.py
- lib/python/Plugins/SystemPlugins/IceTV/__init__.py
- lib/python/Plugins/SystemPlugins/IceTV/plugin.py
[IceTV] Prepare log for sending to IceTV
Save the log information in a form suitable for sending to IceTV,
and format it as needed for user display.
Use strftime() instead of datetime for date/time formatting for consistency
with other date/time formatting in the code.
[IceTV] Allow sending of IceTV logs to the IceTV server
Helps support remote debugging by IceTV staff.
Fetch IceTV server user settings, and if sending debug logging to
the server is enabled in the settings send IceTV logging information to
the IceTV server.
Only log information in EPGFetcher.log is sent.
Setting config.plugins.icetv.member.send_logs to False will prevent
any debug logs from being sent to the server, but tere is currently
no UI to change the config variable.
Bump IceTV plugin version.
> [IceTV] Allow sending of IceTV logs to the IceTV server

- lib/python/Tools/Directories.py
- [Directories.py] Raise priority of "/etc/enigma2"
This change corrects an error where the USER priority for "/etc/enigma2/" was set too low and below that of the SKIN priority.
This change correctly implements the USER, SKIN, DEFAULT priority protocol.
- [Directories.py] Fix SCOPE_FONTS
This change corrects a few issues with the SCOPE_FONTS search list.
- If there is no display skin in use redundant search entries were added to the search list
- The "/etc/enigma2/" search item was omitted from the list
This change correctly implements the USER, SKIN, DEFAULT priority protocol.
- [Directories.py] Add common directory
Add new skin common directory to store shared or common skin override components.  This location can be used to store shared or common skin override components in a more …
> Correct issues with Directories.py

- lib/driver/hdmi_cec.cpp
EPG hdmi command is wrongly set to KEY_INFO 
case 0x53: should be set to	key = 0x16d;
accordingly to input_fake.h
lib/driver/input_fake.h
#define KEY_INFO         0x166
#define KEY_TIME         0x167
#define KEY_EPG          0x16d
> HDMI CEC :  FIX EPG_KEY

- lib/python/Tools/Directories.py
Add SCOPE_KEYMAPS so that the location information for the kepmap files is centrally defined and available. This will also ensure that the keymaps directory exists so that the "Keyboard.py" code can't fail.
> [Directories.py] Add SCOPE_KEYMAPS

- lib/python/Tools/Directories.py
- Add SCOPE_LIBDIR as added by Persian Prince into OpenVision and OpenPLi.
- Move SCOPE_CURRENT_PLUGIN_ABSOLUTE and SCOPE_CURRENT_PLUGIN_RELATIVE to the appropriate location in "defaultPaths" dictionary.
> [Directories.py] Add SCOPE_LIBDIR

- lib/dvb/radiotext.cpp
seems like, previous version of radiotext.cpp wasnt saved in utf-8 ...
> radiotext - fixed lossy encoding

- lib/python/Components/SetupDevices.py
- lib/python/Components/Timezones.py
- lib/python/Tools/Geolocation.py
- mytest.py
- [Timezones.py] Refactor and optimise the code
- Clean up and optimise the code.
- Add access to geolocation data to establish the initial guess of the user's timezone.
- Don't change the default timezone when navigating through available timezone lists.
- Ignore the existence of alternate txdata from "posix" or "right" packages.
- Improve the configuration comments.
- Correct name display of "Dumont d'Urville".
- Use the 2019c version of "timezone.xml" file to offer users a classic view of timezone selections.  This list is the default for OpenATV and is available under the "Timezone area" of "Classic" if the new "timezone area" and "Timezone" style UI is adopted by OpenATV.
- [Geolocation.py] New tool to provide geolocation data
- [mytest.py] Activate geolocation initialisation
- …
> [Timezones.py] Refactor and optimise the code

- lib/python/Components/Timezones.py
The correct timezone default was incorrectly hard coded for the "Classic" mode UI.
> [Timezones.py] Correct initialisation default

- lib/python/Components/SystemInfo.py
- Optimise "countFrontpanelLEDs()" method.
- Optimise imports to eliminate duplicate imports.
- Sort imports to allow for easier compare and merge between images.
- PEP 8 cleanup the code.
> [SystemInfo.py] PEP8 and code cleanup

- lib/python/Plugins/SystemPlugins/IceTV/plugin.py
Add class name to reference to evRecordWriteError to prevent
crash when there is a disk write error during recording.
> Fix crash in IceTV plugin on recording write error

- lib/dvb/epgcache.cpp
removed for further testing due to seg fault, endless spinner and blocking issues
> [epgcache.cpp] "m_OPENTV_EIT_map.erase(it)"

- lib/python/Components/Timezones.py
- mytest.py
- [Timezones.py] Add further improvements
- Correct display of UTF-8 areas and zones.
- Add callbacks for before and after the timezone is set.
- Separate the AutoTimer code out of the Timezones code.  Move the AutoTimer code to the end of this code and add the hooks as a template until the AutoTimer code is updated to use the new callback code.
- Enable AutoTimer processing code.
- Correct a minor spelling error.
- [mytest.py] Move Timezones initialisation
This change enables the AutoTimer processing to be restored to the Timezones.py code.
NOTE: The AutoTimer code in the Timezones.py code should be moved into the AutoTimer plugin code.
> [Timezones.py] Add further improvements

- lib/python/Components/Timezones.py
Don't save the changed timezone settings until the user exits the settings screen.
> [Timezones.py] Fix incorrectly saved setting

- data/setup.xml
This change enables the area / region and timezone in that region Timezone UI.  Users can now select their area or region of the world and then can select from a significantly shorter list of timezones that apply to that area or region.
If users prefer they can still select the "Classic" area and the Timezone list will then offer the traditional comprehensive list of timezones by GMT offsets.
> [setup.xml] Enable area and timezone UI

- lib/python/Components/Timezones.py
This patch disables the code that tried to synchronise the Enigma2 time zone with that defined in the Operating System.  For now the difference will be logged but Enigma2 will no longer be synchronized.
I hope this patch can be removed as soon as the code that is unexpectedly changing /etc/localtime can be found and fixed.
> [Timezones.py] Patch to avoid /etc/localtime issues

- lib/python/Components/Timezones.py
With the new area / region and timezone UI being enabled in "setup.xml" the default time zone in "Timezones.py" needs to be updated to "Europe/Berlin" to provide a better user experience when setting the timezone.
> [Timezones.py] Update default timezone

- lib/python/Components/Timezones.py
- Allow the time zone in the "settings" file to override the "/etc/localtime" time zone setting.  This will allow users to restore their "settings" file from a backup and have the Linux, glib, TZ and Enigma2 time zones all be matched.
- Add "/etc/timezone" to the settings updated when the time zone changes.  (This is used by Java and some other software.)
- Correct spelling of "timezone" to "time zone" for displayed text.
> [Timezones.py] More code clean up

- lib/dvb/radiotext.cpp
Reverts openatv/enigma2#1521
need more rework if transformed from iso 8859-15 to utf-8.
> Revert "radiotext - fixed lossy encoding"

- lib/python/Components/Sources/Source.py
- Match removal message to match style used in skin.py.
- Use camelCase for variables.  (ObsoleteSource class does not appear to be used.)
- PEP8 clean up.
This change also aligns this code between images.
> [Source.py] Match message to skin

- lib/python/Screens/InfoBar.py
Workaround for the TV/Radio toogle button in Octagon SF8008.
> TV/Radio toogle button in Octagon SF8008

- lib/python/Tools/Directories.py
The SCOPE_CURRENT_LCDSKIN definition was missing the environment lookup to resolve the "${datadir}" shell variable.
> [Directories.py] Correct missing env lookup

- lib/python/Components/Converter/TemplatedMultiContent.py
- lib/python/Components/MultiContent.py
- [MultiContent.py] Enhance templates
- Enhance template colours to be defined by colour names, # colour value and hex colour value.
- Enhance template pixmaps to use resolveFilename to be able to find relative image references within the current skin.
- PEP8 clean up the code.
- [TemplatedMultiContent.py] Enhance templates
- Add an ability to specify fonts via the parseFont() method.
- Remove the list converter code as the source, converter and render chain is *not* an error condition.
- PEP8 clean up the code.
- [MultiContent.py] Cast error text as a string …
- This was a suggested improvement.
> Enhance TemplatedMultiContent

- data/setup.xml
- lib/python/Components/ConfigList.py
- skin.py
- [skin.py] Refactor and optimise the code
- Simplify, improve and optimise the skin loading code.
- Remove the loadSkinData() method code and create a new method InitSkins() to be caaled from mytest.py  (The loadSkinData() method is now a placeholder for older versions of mytest.py and simply executes the new InitSkins() method.)
- Provide log diagnostics for failed skin loads (XML errors).
- Improve logging information about screens at screen load time.
- Optimise the parseCoordinate(0 code.
- Enhance the parseParameter() code.  Font processing is now done here and not in the skin loader code.
- Use the new RcModel.py library code to initialise the loadPixmap() method.
- Remove all inline image cache code and use the C++ image cache instead.
- Simplify the logging messages.
- Remove the …
> Overhaul skin processing engine

- skin.py
- Use isfile() rather than pathExists().  Using isfile() as a test for existence is more optimal because, in context, it is better to know that the path exists and is a file rather than just knowing the path exists.
- Remove obsolete imports.
- Cast err as a string to ensure the print format is correct.
> [skin.py] Add a few more clean ups

- skin.py
Log font not found errors at the Python layer rather than relying on the C++ layer.
> [skin.py] Log font errors

- lib/python/Screens/Menu.py
- Don't use a skin.py internal variable if an access method is available.  In this case, don't use the "domScreens" dictionary but rather the "findSkinScreen()" method instead.  This is not likely to break if the skin.py code changes again.
- The Python coding style ".has_key()" is deprecated.
- Don't import all of skin if it isn't required.  Mistakes or errors could damage the skin code.
> [Menu.py] Improve crash correction

- data/keymap.ntr
- data/keymap.u80
- data/keymap.xml
- data/setup.xml
- data/skin_default.xml
- lib/python/Components/UsageConfig.py
- lib/python/Screens/ButtonSetup.py
- lib/python/Screens/ChannelSelection.py
- lib/python/Screens/EpgSelection.py
- lib/python/Screens/InfoBarGenerics.py
- lib/python/Screens/PiPusageModeSetup.py
- lib/python/Screens/PictureInPicture.py
- lib/python/Screens/ScreenSaver.py
- po/enigma2.pot
- po/hu.po
Hi,
I have expanded and modified the existing PiP solution for Enigma2.
I wanted it to be quick and easy to use.
Quick to use, either as a function or from a programmed button, or from the standard Blue button.
There is a warning window to set up a quick use of the Blue button.
The use of PiP and the PiP mode selection window can be assigned to a specific button on the remote control.
But it can be used just as quickly by the standard Blue button.
There are three modes to choose from to use PiP.
There are 3 ways:
- standard -> Functions that are currently running
- noadspip -> Ads could be filtered out while ads go, another channel could be watched
- side-by-side -> If you want to watch multiple shows at once, you could use this mode the right way
The PiP mode switching window makes it …
> Expanding the functionality of the PiP

- lib/python/Components/Timezones.py
Correct the name of the Spanish archipelago from "Canary" to "Canary Islands".
> [Timezones.py] Correct "Canary" to "Canary Islands"

- po/en.po
- po/en_GB.po
This change:
- uses plain (or at least more plain) English,
transitioning technical terms to more everyday, user-friendly wording
- fixes typos and grammatical issues
- keeps Americanizations within en_US (en.po), and Intl English in en_GB
- makes capiltalisation, hyphenation, abbreviations and acronyms
more consistent across menus, option lables and descriptions
- makes terms more consistent (eg. key -> button; rotor/motor -> dish rotator)
- makes option descriptions more consistent
('If set to yes'..., 'This option lets you...', 'Configure...' etc.)
- adds a couple of enhanced descriptions (eg. technical terms)
- removed all 'Fuzzy' entries from en_GB and several from en_US (en.po)
Yet to be done includes:
- date formatting
Not part of this work:
- changes to enigma2.pot translation …
> Complete overhaul of English en_US (en.po) and en_GB translation files.

- po/en.po
- po/en_GB.po
English (American) and English (British) translation tweaks
This change:
- makes more terms consistent
(rotator -> positioner, elements -> files)
- fixes manual comment prefixes
(#. -> #)
- adds comments to some button lables in prep for msgctxt, 
as red/green/yellow/blue are also used in skin settings
- uses given language for language labels
(e.g. French -> Français)
- removes some more 'fuzzy's
Not part of this work:
- changes to enigma2.pot translation entry template file
- changes to source code
> English (American) and English (British) translation tweaks

- lib/python/Screens/Screen.py
This change protects the code from tasks started at system startup that don't have a session.
> [Screen.py] Protect against screens with no session

- lib/python/Screens/Screen.py
This change protects the code from tasks started at system startup that don't have a self or session.
> [Screen.py] Protect against screens with no self or session

- lib/python/Screens/Screen.py
This change improves on the previous fix to protect the code from tasks started at system startup that don't have a self or session.
It should also be noted that an issue was found in the IceTV code that triggered the issue on OpenATV.  Hopefully that issue will also be corrected in due course.
> [Screen.py] Improve the previous stability fix

- lib/python/Components/ConfigList.py
This fix error on ConfigList init.
For example in plugin YouTube init I get error:
ConfigListScreen.__init__(self, searchList, session)
File "/usr/lib/enigma2/python/Components/ConfigList.py", line 176, in __init__
self["config"] = ConfigList(list, session = session)
File "/usr/lib/enigma2/python/Components/ConfigList.py", line 21, in __init__
self.list = _list
File "/usr/lib/enigma2/python/Components/ConfigList.py", line 102, in setList
assert len(x) < 2 or isinstance(x[1], ConfigElement), "entry in ConfigList " + str(x[1]) + " must be a ConfigElement"
AssertionError: entry in ConfigList None must be a ConfigElement
> Do not use list as variable in ConfigList

- lib/python/Screens/Screen.py
Clear the screen path history buffer when the screen path is cleared.
> [Screen.py] Clear screen path history buffer

- po/en.po
- po/en_GB.po
Update English en_US (en.po) and en_GB translation files
This change:
- fixes typos and grammatical issues
- adds missing translations
- uses own-language option values (audio/subs/epg)
- removes 'fuzzy' flags left by previous fix for #1736 
- fixes a few more 'fuzzy' entries
Not part of this work:
- changes to enigma2.pot translation entry template file
- changes to source code
This is very likely still incomplete!
There are some known '# needs improvement' and 'fuzzy' entries
> Update English en_US (en.po) and en_GB translation files

- lib/dvb/scan.cpp
This removes an entry that was added 10 years ago to cover a dual illumination that lasted less than a week.
397d121#diff-0745b6c402dc73ba260d2a203317df44
Most of the rest of this section just contains rubbish that should also go in the dustbin.
> scan.cpp: update 28.2E

- lib/dvb/epgcache.cpp
- lib/service/event.cpp
This problem is related to the fact that when saving information from SHORT_EVENT_DESCRIPTOR to the epg.dat cache file, it is transcoded to UTF-8. And since the information is initially transmitted in ISO 8859-5 encoding, in which the Cyrillic character is encoded in one byte - the standard field SHORT_EVENT_DESCRIPTOR of 255 - 6 bytes can contain text in 249 characters, in UTF-8 Cyrillic characters are encoded in two bytes and, accordingly, in the field SHORT_EVENT_DESCRIPTOR can fit approximately 125 Cyrillic characters, so that everything that is more than 249 bytes is truncated. In this patch, the text field is saved with the original encoding, and transcoding is performed when the text field is requested.
> No truncate SHORT_EVENT_DESCRIPTOR text for UTF8

- skin.py
- Make all print statements Python 3 ready.
- Use more appropriate variable names for screen IDs.
- Optimise some screen ID code.
- PEP8 correct an if statement.
These changes bring the openATV version of this code closer to the other images. It is hoped that openATV can help bring the code back into parity.
> [skin.py] Various updates

- lib/dvb/scan.cpp
https://github.com/OpenViX/enigma2/commit/27306a4a00c704f847ac5f2415524d552a00b228
https://github.com/OpenPLi/enigma2/commit/cee4e647520ae78d202a41eb048b16437b2087b9
> [scan.cpp] isValidONIDTSID: remove defunct transponder duplication hacks

- lib/python/Tools/NumericalTextInput.py
- Remove duplicated self.mapping definition.
- Update commented print statement for Python 3 compatibility.
> [NumericalTextInput.py] Small code clean up

- data/keymap.xml
- Change "ConfigListActions" colour buttons from "m" (Make) to "b" (Break) to allow legacy code using "m" to override these assignments.
- Correct the keyboard function keys to match previous documentation. (RED = F5 -> BLUE = F8)
> [keymap.xml] Correct key assignments

- lib/python/Screens/Screen.py
- skin.py
These updates bring openATV into sync with developments on the other main images.
[skin.py] Correct a print statement
- Correct a print statement to be ready for Python 3 that was missed in a previous change.
[skin.py] Enable processing of templated screens
- This code allows embedded screens to be a template of a screen scaled to HD resolution together with scaling data to allow that screen to be resized to the current GUI resolution.
[skin.py] Add skin screen validation code
- This option works in conjunction with a change in Screen.py to allow code to check if a screen in the skin is compatible with the code.  If the list of widgets considered mandatory are not present then the current screen will be rejected and the next option will be tested.  It is assumed that if all skin options …
> Screen / Skin updates

- lib/python/Components/AVSwitch.py
- lib/python/Screens/InfoBarGenerics.py
- lib/python/Screens/VideoMode.py
This commit disables the config.av.policy_169 setting on boxes which don't have a /proc/stb/video/policy2 file.
> Disable config.av.policy_169 setting on boxes which don't have a /proc/stb/video/policy2 file

- lib/python/Components/Sources/EventInfo.py
* Split MP3 Stream titles by "-" and display it for Event_Now / Event_Next
* rename to pServiceEvent (pythonServiceEvent)
* fill short and extended description for Event_Now and Event_Next
* Move element3 to Event_Next if it is not empty and place element1 and element2 on Event_Now. If element3 is empty place element1 on Event_Now and element2 on Event_Next
> Update EventInfo for audio internet streams

- lib/python/Components/config.py
This reverts commit 1a2e392dfcaef0118889f540e6d2157b4e1a1f38.
Breaks FileCommander and EMC
> Revert "[ConfigDirectory] add missing value properties"

- lib/python/Components/HdmiCec.py
This fixes a NameError crash as msgaddress was still used in the volume forward log statement.
> [HDMICec]: Crash FIX! invalid use of msgaddress.

- lib/python/Components/Converter/EventName.py
- lib/python/Components/Sources/EventInfo.py
- lib/python/Screens/InfoBar.py
* EventInfo do not refresh downstream elements
This change is to reduce load for normal dvb service reference types
because evUpdatedInfo for dvb is called more often. For example if the
video size has changed which can be the case for old tv series with
4:3 resolution but advertising is broadcast in 16:9.
MP3 and AAC streams advertise their title change via evUpdatedInfo
instead of evUpdatedEventInfo.
* Implement getExtraEventData in Converter and Source
This is implemented in python's fake class and not in servicemp3's
impementation of event.h's c++ interface.
Requested here https://www.opena.tv/skins/57124-radioinfobar-running-text-post483479.html#post483479
* Show infobar if servicemp3's service info changed
This change is to show the infobar if the service info changed and there …
> Update implementation of servicemp3's mp3 and aac stream titles

- lib/python/Components/UsageConfig.py
Add "Visual impaired commentary". "NAR" in UK. "qad" used by French national channels.
Add "oth" to "Original". Used by Rai (Italian national channels)
"qaa" is not English. This is used for original language and already exists in that section.
Copied form commits by Huevos from Vix
> [Usageconfig] language options

- lib/python/Components/MovieList.py
1) buildBeginTimeSortKey() is supposed to sort by time not name.
2) add missing empty string in the return value. The tuple is supposed to have a length of 3, not 2, so it matches the tuple produced by buildAlphaNumericSortKey(), otherwise there will be crashes when using buildGroupwiseSortkey().
> [MovieList] fix buildBeginTimeSortKey(()

- lib/dvb/sec.cpp
The EPGImporter plugin creates a fake, simulated, recording to check if a channel is available.
That causes an unnecessary movement of the dish while importing the epg. Adding the !simulate condition avoids that (first I tried with just no_rotor_command_on_tune but that doesn't work in this case).
Probably the !simulate condition should also be added to the branch sending commands to a diseqc rotor, but since I don't have one I didn't touch that part.
> Dont' move the external rotor with "simulate" and "no_rotor_command_on_tune"

- lib/python/Components/VfdSymbols.py
Custom front panel color in "on" state
Seem to affect more boxes except sf8008(m)
https://www.opena.tv/octagon-sf8008-4k-uhd/57653-oatv6-4-power-buton-led-color-recording.html
> [VfdSymbols] Fix wrong front panel led color after record in standby

- po/pl.po
The author of the translation used incorrect form for "enable", "turn on". In fact "Załącz" means "Attach" (like "attach file to email"). Some people in Poland uses "załącz" (attach) instead of "włącz" (enable/turn on) because second one is very similar to "wyłącz" (disable/turn off). But according to Polish Dictionary this is incorrect and in fact confusing for most people in Poland. Even google translator report it as a potential mistake.
```
załącz -> attach
włącz  -> enable / turn on
wyłącz -> disable / turn off
```
> replace incorrect translations of "turn on" in polish translations

- lib/python/Components/config.py
The value "enable" should be "enabled" to match all other cases of this logic test.
> [config.py] Correct trueValues list

- lib/python/Screens/Setup.py
This change forces the self["config"] list to be cleared if there are no eligible items available to be displayed.
> [Setup.py] Correct setup element list

- data/keymap.xml
- data/setup.xml
- lib/python/Components/UsageConfig.py
- lib/python/Components/config.py
- lib/python/Screens/NetworkSetup.py
- Refactor and optimize the code to create the new DNSSettings class.
- Provide a NameserverSetup redirection class to capture access from older code.
- Make the DNSSettings class a sub class of Setup.
- Fix and improve the ConfigIP class.
- Add a "DNS" section to "setup.xml".
- Add a "DNSSettingsActions" section to "keymap.xml".
- Simplify the "UsageConfig.py" definition of "config.usage.dns".  (All devices that can connect to the Internet have a router or gateway.)
- Allow the DELETE or BACKSPACE buttons to delete the current octet of the IP address being edited.
- Allow the ERASE button to reset the current IP address to 0.0.0.0 and position the cursor onto the first octet.
> [NetworkSetup] Refactor NameserverSetup into DNSSettings

- lib/python/Screens/Setup.py
- Remove the old Python 2 compatibility code.
- Remove unused imports.
- Simplify the XML default.
> [Setup.py] Remove Python 2 code

- lib/python/Components/NetworkTime.py
- lib/python/StartEnigma.py
- Refactor and simplify NetworkTime code.  (Camel case variables, improve logging and simplify the code.)
- Move from using the deprecated "/usr/bin/ntpdate-sync" shell script to the "/usr/sbin/ntpd" program.
- Move all the network time management code from "StartEnigma.py" to" NetworkTime.py".
- Add notifier for changes to network time sync period.  (In the past changes to the time period were not enacted until the old time period had expired.  Thus if you changed from once a day to 30 minutes the change would not happen until the full day timer expired.  The code now triggers a time update when the time period is changed and then the new period is immediately implemented.)
> [NetworkTime] Refactor code

- lib/python/Screens/NetworkSetup.py
The "run()" method in "DNSSettings" is redundant as it is already provided in the parent "ConfigListScreen" class.
> [NetworkSetup] Remove redundant run() method

- lib/python/Screens/NetworkSetup.py
These extra saves were used during testing but should not have made it into the final code.
> [NetworkSetup.py] Remove superfluous "save()"s

- lib/python/Components/ConfigList.py
This change adds a new facility to allow Setup sub class based code to be notified when the user saves changed settings.
This can be considered an alternative to setting notifiers on a number of individual settings.  It is particularly helpful if a number of different settings contribute to a single required change.  When using separate notifiers the same change code could be called multiple times.  With this simple notifier call back system a Setup sub class can register to be notified if nominated settings have been changed and then perform a required action once.
The following methods have been added:
- addSaveNotifier()
- removeSaveNotifier()
- clearSaveNotifiers()
The methods do as their names imply.
An example of how this change is intended to be used will soon be made to Time.py …
> [ConfigList.py] Add a settings save notifier

- lib/python/Components/NetworkTime.py
- lib/python/Screens/Time.py
This change uses the new saveNotifier call back notification system added to "ConfigList.py" to allow the system to track any changes made to any of the "Sync time using", "NTP server" or "Sync NTP every (minutes)" settings.  If, and only if, any of these settings are changed and saved when the user edits the "Time Settings" screen will cause the "timeCheck()" method inside the "NetworkTime.py" module will be called to update the time synchronization policy as changed by the user.  The network time change will only be run ONCE no matter haw many of the dependent settings have been changed.  The code will only be run if any of the settings in the "Time Settings" screen affecting the network time have been changed.
**NOTE: This pull request must be merged *AFTER* #2237!**
> [Time.py] Implement new saveNotifier system

- lib/python/Screens/MessageBox.py
This changes returns the initialization of the "self.list" variable to an empty list rather than None to protect skins with applet embedded Python code that uses "self.list" without checking that it exists or is a valid list.  The change improves compatibility with older screens that test the length of self.list without first checking that it exists as a list.
NOTE: All skin applets with embedded Python code should include try/except around all the code to ensure that errors in the skin Python do not crash the skin or Enigma2.
> [MessageBox.py] Change "self.list" initialization

- lib/python/Components/MenuList.py
This will give codes a better way to access the MenuList's list without directly groping for an internal variable.
In the future this will allow us to rename the "list" variable to something else to avoid confusion with the list data type.
> [MenuList.py] Add a "getList()" method

- lib/python/Components/ChoiceList.py
- Remove the unused "row_delta_y()" method.
- Remove the odd coordinate manipulation code.  It uses fixed magic numbers that may interfere with or not suit the current skin.
- Remove the template vertical offsets and use RT_VALIGN_CENTER instead.
- Widen the default template width to suit the default HD resolution.
- Make the horizontal line use the UTF-8 dash character rather than "-" (minus) to draw a continuous line.
- Add a more logical "none" key to do the same as the "dummy" key.
- Match the default font height to suit the template height.
- camelCase the variable "ItemHeight" to "itemHeight".
> [ChoiceList.py] Clean up and improve the code

- lib/python/Screens/FactoryReset.py
This change results from https://github.com/openatv/enigma2/commit/a4837d4701f28cd0c2998e69e6a715a05ae5f789 where the inappropriate title text was masked by this setTitle.  This screen title will now always reflect the title as assigned in setup.xml.
> [FactoryReset.py] Remove superfluous setTitle call

- lib/python/Screens/NetworkSetup.py
The DNSSettings screen title will now always reflect the title as assigned in setup.xml.
> [NetworkSetup.py] Remove superfluous setTitle call

- lib/python/Screens/Menu.py
The ProtectedScreen class must not be initialised until after the menu details are loaded.  Initialising ProtectedScreen to early causes isProtected() to be run before the variable it uses (self.menuID) has been created.
> [Menu.py] Correct initialisation sequence

- lib/dvb_ci/dvbci_datetimemgr.cpp
This code seems very similar to https://github.com/atvcaptain/dvb-apps/blob/master/lib/libdvben50221/en50221_app_datetime.c#L100 but https://github.com/atvcaptain/dvb-apps/blob/9b74778ab215bbe8901cac7ff176d039c725a23c/lib/libdvben50221/en50221_session.c#L280 does not prepend the length of the packet to the data sent to the CAM.
So for enigma2 this ends up as:
90 02 00 04 9f 84 41 06 05 e9 1d 20 11 52
instead of:
90 02 00 04 9f 84 41 05 e9 1d 20 11 52
> Fix sending datetime to CAM

- data/setup.xml
- lib/python/Screens/InfoBar.py
- lib/python/Screens/SleepTimer.py
- lib/python/StartEnigma.py
This change allows the user to press SLEEP, or assign another button to act as SLEEP, to bring up an interactive version of the SleepTimer screen where only the Sleep Timer options are shown and the user may press OK to select and save the Sleep Timer options.
The user interface for this screen when called from a menu is unchanged.
> [SleepTimer.py] Add button mode

- lib/python/Plugins/Extensions/MediaPlayer/plugin.py
This reverts commit 82611a03238f5de0be1d20934e2d88605e893f73, reversing
changes made to 21e1932bc9a2c6ebebcaa7f1c7b203280c107c73.
There were actually no problems with saving playlist name input.
> Revert "Merge pull request #2285 from 4l3x2k/7.0"

- lib/dvb_ci/dvbci.cpp
- lib/dvb_ci/dvbci.h
- lib/dvb_ci/dvbci_ui.cpp
- lib/dvb_ci/dvbci_ui.h
- lib/python/Screens/Ci.py
- By default every device is enabled
- Allows the user to disable the CI device from the menu (to be used by other software)
- At startup a disabled device will not initialize but will appear in the menu as disabled and the user can choose to enable it
This functionality triggers also a Reset. @atvcaptain do you think we should remove the Reset functionality or leave it as it is.
> Add support for enabling and disabling CI devices

- lib/dvb_ci/dvbci.cpp
Python config is not available at the time the CI devices are initialized. Use eSimpleConfig instead.
> Switch to use eSimpleConfig which can access the startup config

- lib/python/skin.py
This call was added to ensure that the current windowstyle is always activated.  The fact that window styles was repeatedly activated was not considered an issue.
Recent work on openATV has been targeted at optimising the performance and code.  With this in mind we would like to review this code and look to optimising it.
There are some new changes and enhancements coming to the window styles and we would like to see skin processing optimised to improve the speed of the UI and user experience.  If any skin developers or users detect any screen or skin changes resulting from this change please alert us as a matter of urgency.  Please only report any issues *DIRECTLY* caused by this one change!
> [skin.py] Remove superfluous reloadWindowStyles() call

- lib/python/Components/Sources/List.py
- The up() and down() methods did not respect the C++ code list navigation.  A previous edit introduced a local/Python version of enableWrapAround that required Python code to enable the wrap around functionality and caused the skin attribute enableWrapAround="0" or "1" to be ignored.  The original functionality has been restored.  The old calling arguments are still accepted for compatibility with calling code but are ignored.  If you wish to control the wrap around status of a widget please use the skin enableWrapAround attribute.
- The selectPrevious() and selectNext() methods are no longer required for managing the wrap around status and now simply call the up() and down() methods respectively.  These methods should be removed as soon as all calling code is fixed to go back to the …
> [List.py] Correct list navigation and clean code

- lib/python/skin.py
This new attribute is being added in preparation of a new Enigma2 GUI option that will allow skinners to select if multi-page widgets will scroll a page at a time or they will scroll a line at a time.
Do not use this attribute until the matching C++ code is published as complete.
> [skin.py] Add the new "scrollbarScroll" attribute

- lib/python/Tools/Downloader.py
- Remove the deprecated HTTPProgressDownloader class as the functionality upon which it is based was deprecated in twisted version 16.7 and has been removed since twisted version 22.
- Use a current download method that can properly handle all http and https requests.
- Implement a refactored DownloadWithProgress class that uses the twisted reactor.callInThread call to do the fetch in another thread but still allow the UI to be updated with the download progress.  Note that the name has been changed to use a capital letter as the first character as is normal practice for class names.
- Add a downloadWithProgress class to provide compatibility with all old code that calls the class with a lowercase first letter.  (Classes should start with a capital letter.)
> [Downloader.py] Refactor code

- lib/python/Components/ScrollLabel.py
- Locally process all ScrollLabel specific skin attributes.  They are no longer passed to skin.py for processing.
- Use new skin.py based attribute validation / processing methods rather than duplicating the code.
- Remove the "showscrollbar" argument as this functionality is now skinable.
- Remove duplicate execution of the updateScrollbar() method.
- Improve variable names to make the code easier to read and follow.
- Force the left and right columns into "noWrap" mode to ensure that the left and right columns remain synchronised.
- Create and manage both the left and right eLabels on GUI creation so that the attributes can be applied to both on their creation.
- Optimise the list navigation.
- Rename some attributes to clarify their meaning:
- "colposition" is now "splitPosition".
- …
> [ScrollLabel.py] Refactor and enhance the code

- lib/python/skin.py
This corrects a boot crash when processing the default initialisation values for "scrollbarMode" and "scrollbarScroll".
Apologies for the error and any inconvenience.
> [skin.py] Correct default initialisation values

- lib/python/Components/ChoiceList.py
- lib/python/Components/ConfigList.py
- lib/python/Components/MenuList.py
- lib/python/Components/ServiceList.py
- lib/python/Components/TimerList.py
- lib/python/Screens/HelpMenu.py
Now that the skin "windowstyle" allows for the skin's default of enableWrapAround to be set it is no longer necessary to hard code the default.  The system default has been adjusted to set the system default to enabled.  The skin default can be set in the "listbox" tag in the "windowstyle" block of the skin.  As before individual screens can still have an "enableWrapAround " attribute to modify the settings for any individual screen.
> Remove hard coded enableWrapAround

- lib/python/Components/ConfigList.py
Correct the variable name of slider "borderWidth" variable.
> [ConfigList.py] Correct variable name

- data/setup.xml
- lib/python/Components/UsageConfig.py
- lib/python/Screens/Menu.py
This change adds menu images to all "Menu.py" based screens.  This is done in a style similar to how images were added to "Setup.py" screens.  The images are defined in a "menus" block within the skin.  Each "menu" tag in the block contains a "key" attribute which is the "entryID" of the menu entry to which this image will be attached.  The "menu" tag also contains an "image" attribute that is the path to the menu image to be used for that menu entry.
Similar to "Setup.py" "Setup" screen the "Menu.py" "Menu" screen can have a "menuimage" widget which defines where the menu image will be displayed.  This image will change to reflect the currently selected menu entry.  If a "default" image is defined then this image will be used for all menu entries that do not have a specifically assigned …
> [Menu.py] Add menu images

- lib/python/Screens/Menu.py
Don't require skins to have a "description" widget.  This was required for some testing and was not intended for production code.
> [Menu.py] Don't require mandatory widgets

- lib/python/Components/ScrollLabel.py
This fix unconditionally hides the right side panel if it is not used.  (The panel is made transparent.)  This resolves issues for screens that are not transparent and the right hand panel is unused.
> [ScrollLabel.py] Fix: Hide right panel if unused

- lib/python/Components/Pixmap.py
- lib/python/skin.py
[skin.py] More improvements and fixes
- Refactor "loadPixmap()" method into "parsePixmap()".  Improve error reporting.
- Use "parseInteger()" method in more places to protect more of the skin code from crashing.
- Don't translate the "text" or "title" attributes if they are empty strings.
[Pixmap.py] Import update
- Change the "loadPixmap()" method import to "parsePixmap()" to match a change in "skin.py".
> [skin.py] More improvements and fixes

- lib/python/Screens/Menu.py
- The "displayBrand" and "displayModel" variables are global and should have been in all upper case.
- Some debug logging has been removed to stop bloating the logs.
> [Menu.py] Correct module variable case, quiet logs

- lib/python/Screens/Information.py
[Information.py] Remove testing text colors]
- The embedded colours were only intended to test the new spacing code and should not have been sent to the repository.
- The debug log index pointer needs to be reset when the debug log list is cleared.
> [Information.py] Small fixes

- lib/python/Components/config.py
- Remove the use of "set()" function that makes "ConfigLocation" class "load()" and "setValue()" lists unique.  The "set()" function now has a side effect of changing the list into a random order.  This is undesirable for some users.  Similarly sorting the list here is also seen, by some users, as undesirable.  A change has been planned for the future where users will be given control of the order list in the UI.
- Implement a new (Python 3.7 or newer) function to ensure the the "ConfigLocation" values are unique.  This new function does *not* change the list order.
- Make a few more PEP8 clean ups.
- Remove an unused and broken method "getKeys()" from the "ConfigDictionarySet" class.
- Add a new value of "enable" to the Boolean True values validation list.
- camelCase a variable.
> [config.py] Code fix and small tidy ups

- lib/python/Components/config.py
This change adds an optional new argument to the getResolvedKey() method.  This option, "silent", allows code to call getResolvedKey() and, if the key is missing/invalid, return None rather than an empty string.  The silent option also suppresses the error log for the key error.
This option has been added for code, like the ConfigEntryTest converter, that may access invalid config items.  The option suppresses all the unwanted log entries.  The option also allows the calling code to identify if the requested key was not found instead of just returning an empty string value.
The reason for adding this option was triggered by skins wanting to know if the IceTV plugin is installed and active.  If the plugin is not installed then the required key was not available and the logs could fill with …
> [config.py] Enhance getResolvedKey() method

- lib/python/Components/Converter/ConfigEntryTest.py
- In my last change I presumed that everyone would want invalid key errors to be suppressed.  This presumption was inappropriate. I have now added a new optional argument, "Ignore", that instructs the code to ignore the key error.  If the option is not used then the error is once again reported.  The difference is that the error condition is now associated with this converter so it should be easier to find and address any skin issues. Skinners can now decide when, and when not, to report config key errors.
- Correct the option list when reporting invalid arguments.
> [ConfigEntryTest.py] Code enhancement

- lib/python/RecordTimer.py
Add three new TIMERTYPE variables that can be used in the new Timers.py code.  These new variables match the equivalent variables in PowerTimer.py.
> [RecordTimer.py] Add TIMERTYPE variables

- lib/python/PowerTimer.py
- lib/python/Screens/PowerTimerEntry.py
Convert "autosleepwindow", "nettraffic", "netip" and "showextended" variables from ConfigSelection to ConfigYesNo objects as they only have "Yes"/"No" values.
> PowerTimers use Boolean for some values

- lib/python/Screens/InfoBarGenerics.py
- lib/python/Screens/ScreenSaver.py
This change makes the class name match the module name.  The code has also been tidied up with the imports sorted and optimized and variables camelCased.  Also the randint() function has been replaced with the base randrange() function as the lowest value for the X and Y coordinates should be 0 not 1 (the left and top screen coordinates are 0 not 1).
The class name change is also reflected in "InfoBarGenerics.py".
The code defaults to using the newer screen name of "ScreenSaver" but will fall back to using the previous "Screensaver" screen name for skins that aren't updated.
> [ScreenSaver.py] Match class name to module name

- lib/python/Screens/FlashManager.py
- Fix an error that SONAR did not report.
- Don't use "zip" as a variable name as suggested by SONAR.
- Remove some development time comments.
> [FlashManager.py] More ZipFile clean up

- lib/python/timer.py
This debugging code is only temporary as we look for all code that uses float for begin and end times.  The begin and end times should only be integers but we are noticing some code is ending up with float based times.
> [timer.py] Add debugging for non integer times in timers

- lib/python/TranslationData.py
This file contains dummy ngettext() definitions to be used to initialize the translation harvester. These strings may be used in ngettext() computations that can not be seen by the harvester.
NOTE: This code should never be referenced or loaded!
> [TranslationData.py] File for translation triggers

- lib/python/Components/config.py
This change was made in conjunction with the addition of the new module TranslationData.py.  This was added as an aid to ensuring all strings are added to the translation harvest. After reviewing this code and discussing the feature with other developers we agree that this implementation will not deliver the results we want. It creates an opportunity for parts of the code to get out of sync.
We will now change ConfigSelectionNumber instances that require units into ConfigSelection instances with appropriate choices lists.
> [config.py] Remove units argument from ConfigSelectionNumber

- lib/python/Screens/Timers.py
- Don't show the new margin before + duration + margin after UI is there are no margins.
- Add the units to the sleep delay ConfigSelection list of options.
> [Timers.py] Improve time displays

- lib/python/Screens/InfoBarGenerics.py
This change creates a callback in the button press detection code.  The EnergySaver timer now hooks into this callback rather than directly processing the timer code directly.  This has been done so that some of the PowerTimers can now share the same callback system.
> [InfoBarGenerics.py] Rework EnergySaver timer

- lib/python/PowerTimer.py
- lib/python/timer.py
This change eliminate a crash for Standby and Deep standby PowerTimers when attempting to unbind from the action map when no binding is active.
> [PowerTimer.py] Don't unbind if not bound

- data/menu.xml
- data/setup.xml
- Separate the "Recording" XML block into two more logical blocks.  One is for the recording based settings and the other is for the playback based settings.  Note that some settings are appropriate to both menus.
- Update menu.xml to add the new "Playback Settings" menu item.
> [setup.xml] Separate Playback and Recording Settings

- lib/python/Screens/Timeshift.py
This change holds the "Timeshift" screen open until the MessageBox is dismissed.  The solves a possible screen corruption on returning to the calling menu.
> [Timeshift.py] Correct MessageBox sequence

- lib/python/skin.py
This name change better reflects what this skin attribute does.  As per the HTML concept of padding this is the horizontal and vertical space to add before the content is displayed.  The "textPadding" attribute specifies the horizontal and vertical padding, in pixels, to be applied to text based list boxes.   This attribute is only used by "eListboxPythonStringContent()" widgets which includes "MenuList()" widgets and StringList conversions.
For example, a textPadding="10,2" of a MenuList widget will indent the text 10 pixels from the X (left) position of the widget and will drop the text 2 pixels from the Y (top) position of the widget.  Note that these values are symmetrical in that the padding will also be affect the left and bottom padding of the widget.  The space available in the …
> [skin.py] Rename textOffset to textPadding

- lib/python/skin.py
This enhances the previous commit that changed textOffset, into textPadding.  This attribute can now be set as a skin based default.
> [skin.py] Add windowstyle defaults for textPadding

- lib/python/skin.py
The scaling methods are inappropriate in this situation as the values are taken from the skin and should already be correctly scaled.  The methods are not available here anyway.
> [skin.py] Fix setDefaultPadding arguments

- lib/python/skin.py
Some skin attributes are optional and need not be specified to achieve the default value.  This change sets the default values in the dictionary get() functions to suppress the "[Skin] Error: The value 'None' is not a valid integer!" errors that were being generated when the attribute was not defined.  (Even though the message was displayed the correct value was being set.)
Remove the specified default value of "None" as this is not required as this is the default.
> [skin.py] Suppress confusing skin error logs

- lib/python/skin.py
The widget padding options have now been enhanced.
1. Any eLabel widgets may now also have the "textPadding" attribute applied to them.  This makes sense, for example, for widgets that have a backgroundColor and you don't want the text being displayed too close to the edge of the widget.  This can also be used to align text in eLabel() widget headings to line up with padded list boxes, etc.
2. The "textPadding" attribute may now have 1, 2 or 4 values in a comma separated list.  If only one value is supplied then that padding value is used as the padding for the left, top, right and bottom edges of the widget.  If two values are supplied then the first value is used as the left and right padding while the second value is used as the top and bottom padding.  If four values are supplied then …
> [skin.py] Enhance the padding options

- lib/python/Screens/OScamInfo.py
If reader name contains special characters the request fail with "reader not found"
> [OScamInfo] Fix statistic view

- lib/python/Plugins/Plugin.py
- lib/python/Screens/InfoBarGenerics.py
This change allows plugins to be notified when the InfoBarShowHide class is loaded.  The notification will include the reason (1=Started, 0=Stopped), the instance of the InfoBar being started/stopped and the type of InfoBar that is being started/stopped.
[InfobarGenerics.py]
- Add the plugin hooks for the WHERE_INFOBARLOADED event.
[Plugin.py]
- Add the WHERE_INFOBARLOADED type of event.
- Tidy up the code.  Sort the imports.  Optimize the code.
> Add InfoBarShowHide hook

- lib/python/Screens/Timers.py
- The wrong timer start variable was used for the UI.  This caused an error in the start timer calculations when the timer was saved.
- Remove some debugging comments.
> [Timers.py] Correct start timer date

- lib/python/skin.py
This change adds a new widget attribute "wrap" to be the opposite of the "noWrap" attribute.  This avoids the double negative of setting no noWrap.  This change is comparable to the recent change of "selection" being created as the opposite of "selectionDisabled".
The deprecation warning on "selectionDisabled" has been removed. The function of "selection" and "selectionDisabled" has been updated, like the new "wrap" and "noWrap", to be fully symmetrical.
> [skin.py] Add a new "wrap" attribute

- lib/python/Components/ScrollLabel.py
- Change the lineHeight calculation to be independent of the current ScrollLabel content.
- Remove the hard coded "noWrap" and allow the ScrollLabel widget to determine when lines will wrap and adjust the data to keep the left and right panels synchronized. If the old behaviour of truncating text to fit the line is desired then set "noWrap="1"" in the skin. (The latest version of the skin.py code also allows "wrap="0"".)
- Add a new method, isNavigationNeeded(), to allow calling code to determine if a navigation action map is required.  If navigation is not required the navigation actions can be disabled.
> [ScrollLabel.py] Enhance ScrollLabel functionality

- lib/python/Components/config.py
Add two shortcut methods to access ConfigSelection data:
- getChoices() returns a list of all the choices (values) from a ConfigSelection object.
- getDescriptions() returns a list of all the choice descriptions from a ConfigSelection object.
Just to be clear:
- config.item.getChoices() is equivalent to config.item.choices.\_\_list\_\_().
- config.item.getDescriptions() is equivalent to config.item.description.\_\_list\_\_().
> [config.py] Add ConfigSelection shortcuts

- data/setup.xml
- lib/python/Screens/FlashManager.py
- lib/python/StartEnigma.py
- lib/python/Tools/MultiBoot.py
This change fixes an issue on a handful of boxes, including the SF8008 family, Beyonwiz V2, Ulan and Amiko, that use different technologies for some of the boot slots.
This change also introduces a new MultiBoot debug log option to allow for collection of more information should these sorts of issues arise again.
Fix provided @captain.
> Fix MultiBoot for differing boot slots

- lib/python/Components/MediaPlayer.py
This code is part of a bigger refactor of the FileCommander / MoviePlayer / FileList code.  This small section has been brought forward to address issues being raised in GitHub and the forum that the MediaPlayer is stuck playing the wrong files (typically is always plays the last file in the playlist no matter what file is selected) when OK is pressed.
> [MediaPlayer.py] Fix playlist file selection bug

- lib/python/Screens/SubservicesQuickzap.py
Old Bug
PS: Another thing: The Index on init is the bouquet service number!? Not the SubserviceIndex.
> Fix SubservicesQuickzap Selected

- lib/python/Components/config.py
Allow for the number value to be displayed with units text if specified in the calling code.  This allows for the numbers to be displayed in a more meaningful way.  For example, instead of an option list of "1, 2, 3, 4, 5" you could display "1 Second, 2 Seconds, 3 Seconds, 4 Seconds, 5 Seconds".
NOTE: The unit strings used in the units list/tuple should be defined elsewhere for translation as this code can not translate variables!
> [config.py] Improve ConfigSelectionNumber

- lib/python/Plugins/Extensions/FileCommander/plugin.py
UnboundLocalError: cannot access local variable 'size' where it is not associated with a value
Sorry again 3 PR. You close the [Updates Branch](https://github.com/openatv/enigma2/tree/FileCommanderUpdates) and haven't visit my [suggestion](https://github.com/openatv/enigma2/issues/2649#issuecomment-1339725166).
> [FileCommander] Fix Crash

- lib/python/Tools/MultiBoot.py
Also, "revision" is not always numeric. It can be alpha, as it often is in homebuilds.
14:02:49.3718 Traceback (most recent call last):
14:02:49.3719   File "/usr/lib/enigma2/python/Components/Console.py", line 52, in finishedCB
14:02:49.3723   File "/usr/lib/enigma2/python/Tools/MultiBoot.py", line 377, in analyzeSlot
14:02:49.3727 TypeError: %d format: a real number is required, not str
14:02:49.3728 PC: b64bdcd0
14:02:49.3728 Fault Address: 338709f9
14:02:49.3728 Error Code:: 518
14:02:49.3732 Backtrace:
14:02:49.3734 /usr/bin/enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x75CA4]
14:02:49.3735 /lib/libc.so.6(__default_rt_sa_restorer) [0xB6074D30]
14:02:49.3735 -------FATAL SIGNAL
> [Multiboot.py] "revision" is a string, not a number

- lib/python/Screens/HelpMenu.py
Change the HELP screen remote control diagnostics to now include a two line label that provides the key ID name and the expected button label for each button that is displayed during the diagnostic scan performed by the "testHighlights()" method.  (This diagnostic is invoked by long pressing HELP while the help screen is displayed, where the help's help is shown if the button is short pressed.)
Note that this new feature will require a skin change for the new diagnostic to be seen.  As mentioned above, a 'name="label"' widget is required and it should allow for two lines of text.
> [HelpMenu.py] Expand remote control help diagnostics

- lib/python/Components/Input.py
- Remove all the Python 2 code.
- Add comments to explain where self.text is defined and used.
- Rename self.textU to self.textBuffer to remove potential confusion with Unicode text.
- Reorder some of the methods to keep related functions together.
> [Input.py] Remove Python 2 code options

- lib/python/Screens/VirtualKeyBoard.py
- Remove all the Unicode definitions used by Python 2.
- Fix the backspace button on the Hungarian keyboard.
- Use AlphaBlend rather than AlphaTest to improve the display of the stacked button images.
> [VirtualKeyBoard.py] Remove Python 2 code options

- lib/python/Screens/EventView.py
- Parsing of BeginTime simplified. BeginTime can be obtained directly (from timestamp) and can be than easily converted to a string format.
- This fixes also the problem with incorrect time conversion during winter time for recordings made in summer time
> [EventView.py] BeginTime conversion

- data/setup.xml
Reworded to make users aware that they need to tune to specific transponder for the EPG to be absorbed. For Sky on 28.2, it is 11778  MHz, Vertical, 27500
> [Setup] OpenTV EPG

- lib/python/Components/Converter/VfdDisplay.py
The source CurrentService fires too often for some streams as to display the clock. Thus only the channel number is shown. The event in question is evUpdatedInfo that fires in less than a second really often for some streams. This patch filters the event received by VfdDisplay converter from CurrentService source and thus allows to display the channel number and after a delay the clock. This may also affect dvb services where evUpdatedInfo is also received but quiet less often.
> [VfdDisplay] Show channel number and clock for some streams

- lib/python/Screens/ButtonSetup.py
- Fix for long button extension translation.
- Allow some strings translations: "EPG", "Setup", "Scanning", "Plugins", "InboBar" and "Power".
> Fix and allow strings translations

- lib/python/Components/UsageConfig.py
- lib/python/Screens/NetworkSetup.py
This change add the Quad9 DNS servers to the list of available DNS providers.
> [NetworkSetup] Add Quad9 DNS service

- lib/python/StartEnigma.py
- lib/python/Tools/Directories.py
- Revert the sys import change as it breaks the twisted redirection of stderr and stdout.
- Remove use of the system() system call.
- Move autorestoreLoop() into runScreenTest() where is is actually used.
- Change all file processing code to use with blocks and add error logging.
- Remove the "killall -9 showiframe" code as it is no longer required.
- Add the new fileUpdateLine() method to Directories.py and use it to simplify some status file updates.
- Replace locale if block with a dictionary lookup.
> [StartEnigma.py] More clean up and simplification of the code

- data/setup.xml
- lib/python/Components/International.py
- lib/python/StartEnigma.py
[International.py]
- Use the new config item "config.crash.debugInternational" to control if the International code initialization will be logged.
- Correct some spelling errors (no translation changes are required).
- Improve the placement of a critical comment.
[StartEnigma.py]
- Add a new config item "config.crash.debugInternational".
- Move the International initialization to be do as early as possible.
[setup.xml]
- Add the option to configure International logging.
> [International] Make initialization logging configurable

- lib/python/Components/About.py
- lib/python/Components/SystemInfo.py
- lib/python/Plugins/SystemPlugins/SoftwareManager/ImageBackup.py
- lib/python/Screens/InfoBarGenerics.py
This change moves the "getChipSetString()" method from the about.py module to a BoxInfo variable called "ChipsetString".  The variable is immutable as the box can't change its chipset during operation.  ;)
The new variable can be accessed with "BoxInfo.getItem("ChipsetString")".
A side benefit of this change is that the chipset is determined only once.  This can reduce file access and time taken to get the value for this variable.
> Move "getChipSetString()" to a BoxInfo variable

- data/keymap.ntr
- data/keymap.u80
- data/keymap.xml
- lib/gui/elistbox.cpp
- lib/gui/elistbox.h
- lib/gui/elistboxcontent.cpp
- lib/gui/elistboxcontent.h
- lib/python/Components/Converter/TemplatedMultiContent.py
- lib/python/Components/Sources/List.py
- lib/python/skin.py
[eListBox.cpp]
* Add horizontal and grid orientation layouts.
* Optimize rendering to reduce code and improve performance.
* Reformat code to reflect common styling and improve readability.
[eListBoxContent.cpp]
* Add support for horizontal and grid layouts.
* Optimize rendering to reduce code and improve performance.
* Reformat code to reflect common styling and improve readability.
[TemplatedMultiContent.py]
* Add support for new orientations.
[Skin.py]
* Add orientation and item alignment parsers for new horizontal and grid orientation layouts.
[keymap.xml]
* Update "ListboxActions" to separate LEFT/RIGHT for horizontal and grid layouts.
The UI designs that intended to stop using LEFT and RIGHT as the page up/down functions were proposed in the light of this new navigational …
> Horizontal and Grid listbox layout

- lib/python/skin.py
In line with the standard that all the Enigma2 code being written in US English so too should the skins.  Given I added this and it is not being used I think it best to remove the non-US options before they get used.
> [skin.py] Remove non-US spellings

- lib/python/Screens/FlashManager.py
Fix URL can't contain control characters
* As in the case of OpenSPA "/Descarga%20de%20Im%C3%A1genes/AirDigital/Zgemma H9.2H SE/"
> [Screens/FlashManager]

- lib/python/Components/config.py
- Add a new "getSelectionList()" method to return a list of tuples that are the current contents of the ConfigSelection list.
- Add a new "setSelectionList()" method to set the list of tuples that will be the current contents of the ConfigSelection list.
- The existing "setChoices()" method remains as a synonym of the "setSelectionList()".
> [config.py] Ad new ConfigSelection methods

- lib/python/Components/ChoiceList.py
Add a new skin parameter called "ChoicelistVerticalAlignment", that takes a value from "*top", "*center", "*middle" or "*bottom", to specify the vertical alignment of all ChoiceList base widgets.  (NOTE: The "*" is required to tell the parameter processor that the data is actually a string value and to not try and process this value through the numeric parsers.)
This parameter is a temporary hack to allow skins from other distributions to work, unchanged, on openATV.  The other images should really fix the alignment issue in their code.  The issue in the other images is that the default alignment is "top" and skinners have been forced to manually calculate offsets of the text to cause the text to be centered vertically in the line.  In openATV we fixed this issue so that no such offset is …
> [ChoiceList.py] Make vertical alignment configurable

- lib/python/Screens/DVD.py
This fix tries to disable the InfoBar showing in DVD menues which is annoying because it allows actions in the menu only if the InfoBar is hidden.
Also a new text is added to show the camera perspective of DVDs that support it. MetrixHD does not have an Icon for it. So thus the textual description.
Furthermore there is a fix to a print statement for logging / debugging purpose.
> [DVD] Fix infobar show / hide and introduce angle label text

- lib/python/Components/ParentalControl.py
- lib/python/StartEnigma.py
[StartEnigma.py] Correct ParentalControl import
- This change corrects the ParentalControl import issue as reported by @TwolDE.
[ParentalControl.py] Make "parentalControl" accessible
- This change complements the fix in StartEnigma.py to allow the "parentalControl" variable to be importable/accessible while StartEnigma.py is running.
> Fix ParentalControl import issue

- data/menu.xml
- lib/python/Screens/HarddiskSetup.py
A storage device is initialised automatically when you record, go to flash online etc without any user intervention. 
The context of the menu/ question is that it is asking if we want to format the device, not if we want to initialise it. (initial setup for use). Most E2 users are from a Windows background and "Format" in this context reflects the function in a more user friendly term.
> [HarddiskSetup] Change "Initialize" to "Format"

- lib/python/Screens/Setup.py
This update changes the comments for the Summary screen to advise coders and skinners that the proposed widget name changes are now available and should be used.  The old widgets "SetupTitle", "SetupEntry" and "SetupValue" are now deprecated and will be removed soon.
All openATV display skins will be updated to use the new widget names.
> [Setup.py] Update comments to warn of pending change

- data/keymap.xml
- Remove re-tasking of the MUTE button.  MUTE should *always* be available to mute the audio.
- Correct spelling of "key press".
- Sort all the unclassified action maps alpabetically to make them easier to find.
> [keymap.xml] MUTE fix and tidy up

- lib/python/Tools/MultiBoot.py
- The existence of the UUID key in the bootSlots dictionary is a quick test if it is defined.  Adding the False value breaks this functionality.
- Fix the issue where the search for UUIDs in the /bin/blkid output was not tolerant of the "UUID=" string being present in the various STARTUP files.
> [MultiBoot.py] Small code optimizations

- lib/python/Screens/FlashManager.py
- Shorten the lambda function.
- The existence of the UUID key in the bootSlots dictionary is a quick test if it is defined.  There is no need to fetch the value as it won't exist if the value is False.
> [FlashManager.py] Correction and optimization to last commit

- lib/python/Components/PluginComponent.py
- lib/python/Plugins/Plugin.py
The REASON definitions created in the last commit required the inclusion of PluginComponent as an additional include into plugins.  As all plugins already import the PluginDescriptor class from Plugin.py it makes more sense to define the REASONs here.
> [Plugin] Move the REASON definitions

- lib/python/Screens/Satconfig.py
Include wording that is in hint text. It is not asking if you have a signal wire `connected` to the tuner, it is as asking if you are `connected through another tuner`.  Make text reflect the question better.
Before:
After:
> Unicable connected

- lib/python/Tools/Geolocation.py
- Update internet library from "urllib" to "requests".
- Use new Enigma2 call to determine Internet connectivity.  This is a non blocking call that is much faster than the old Python equivalent.  If the newer Enigma2 code is not available then the old behaviour is used.
- Correct spelling errors.
> [Geolocation.py] Code updates

- lib/python/skin.py
- Correct parseGradient.
- Correct spelling of setBackgroundGradientSelected().
- Add comment about itemSpacing values being stripped elsewhere in the code.
- Rework selectionZoom() to use a skin value of an integer with a value ranging from 0 to 500.  The value of 0 means no zoom.  A value of 500 means 500%, 5 fold, zoom.
> [skin.py] Small corrections and adjustments

- lib/python/Screens/ServiceScan.py
Fix crash error after this !
14:17:35.7055   File "/usr/lib/enigma2/python/Screens/ServiceScan.py", line 138, in __init__
14:17:35.7059   File "/usr/lib/enigma2/python/Screens/ServiceScan.py", line 18, in __init__
14:17:35.7061   File "/usr/lib/enigma2/python/Components/MenuList.py", line 37, in setList
14:17:35.7064     self.l.setList(self.menuList)
14:17:35.7066     ^^^^^^
14:17:35.7069 AttributeError: 'FIFOList' object has no attribute 'l'
> [ServiceScan.py] Update after this commit https://github.com/openatv/enigma2/commit/aa2c1a7cd025e3be087aecf1eb17d6fc8f90b498!

- lib/python/Components/EpgList.py
- lib/python/Screens/EpgSelection.py
Currently the Graphical EPG is very slow for bouquets with lots of channels (e.g. the "Last Scanned" bouquet).
Moving to the bouquet, and stepping forward or backward in time takes several seconds. (I'm using a Zgemma H.2S.)
The problem seems to be that the Graphical EPG code is loading EPG data for all the channels in the bouquet at once.
This patch changes it so it only loads data for the channels visible in the EPG. (It only keeps visible channels in the list.)
It is much faster for me now.
I'm still new to the OpenATV code, so there are probably things I've missed (e.g. certain config options may be broken). But I think something like this needs to be done to speed up the EPG.
> Changed graphical EPG to only load event data for visible channels.

- lib/python/Screens/PluginBrowser.py
This change force removes the move background highlight if the user exits edit move while move mode is enabled.
> [PluginBrowser.py] Fix move highlight being stuck

- data/unicable.xml
Programmed to use only 16 SCR for Italian market
> Add GT-S2dCSS24 - Italy

- lib/python/Screens/PluginBrowser.py
- Correct spelling of PLUGIN_NAME_VERSION.
- Restore no action debug log as a comment for future possible use.
> [PluginBrowser.py] Small spelling fix

- lib/python/Components/Converter/ServiceInfo.py
- lib/python/Screens/InfoBarGenerics.py
- lib/python/Screens/SubservicesQuickzap.py
Please note.
The sref for iptv channels must have ":" + name at the end in bouquet file to define the channel name. The sref in groupservice file must be identical like in bouquet file. (case sensitive) Subservice functionality for non iptv channels is untouched.
Close #1889
> Fix subservices for iptv channels.

- lib/dvb/pvrparse.cpp
- lib/python/Screens/MovieSelection.py
- lib/service/servicedvbrecord.cpp
- lib/service/servicemp3.cpp
- lib/service/servicemp3.h
[eStaticServiceMP3Info]
* get name from meta for ".stream" recordings
[eMP3ServiceOfflineOperations]
* add cuts, meta and eit for stream recordings to delete list
[MovieSelection]
* handle .streams recording filenames like .ts in case of deletion
[eDVBServiceRecord]
* do not create cuts file if there is no recording
[eMPEGStreamInformationWriter]
* do not create access points if there is no recording file
Close #2864
Close #754
> Fix some recording issues

- lib/python/Screens/Setup.py
This change resolves a potential crash if a setup image is defined but the image file is missing or invalid.
> [Setup.py] Correct a potential crash

- lib/python/Screens/Timers.py
- An error was created in the changes from openATV 6.4 to openATV 7.0 where an unrecordable service caused a recording location pop up to be called rather than the correct select a new service pop up.  This issue is now corrected.
- Add appropriate titles to all the pop up windows.
> [Timers.py] Correct regression error and window titles

- lib/python/Components/PluginComponent.py
- lib/python/Screens/PluginBrowser.py
- The Plugin browser screen now opens faster as the Internet connectivity test is done in the background.
- The remove, download and update plugin lists are now cleared when the action is commenced. This resolves issues with the same plugin being processed multiple times.
- Plugin error messages can now be optionally kept in the error buffer if the user so wishes. The PluginComponent.py code has been adjusted to ensure that the same plugin error is only logged once.
- HELP button text has been updated.
- The GREEN button no longer opens/closes the categories in the PluginActions screen.
- The repository refresh can now be cancelled before it completes if the user entered the "Download Plugins" screen by accident.
> [PluginBrowser.py]  UI changes

- lib/python/Components/Renderer/AnalogClockLCD.py
- code was completely overworked and optimized
- senseless differentiation between '**hColor**', '**mColor**' and '**sColor**' replaced by '**fColor**' (foregroundColor)
- old '**hColor**', '**mColor**' and '**sColor**' is still supported for compatibility reasons
- new attribure '**bColor**' (backgroundColor) added mainly for testing reasons
> [AnalogClockLCD] optimized

- lib/python/Screens/TimeDateInput.py
Date/time Input screen doesn't show day name. This fixes that.
> Add dayname to Date selection

- lib/python/Plugins/Extensions/PicturePlayer/ui.py
class Pic_Thumb
- Otherwise the presentation of thumbnail images (GREEN button) will appear descent.
before this commit:
<a href='https://postimg.cc/Jsdd9DxW' target='_blank'><img src='https://i.postimg.cc/SKyFYczj/antes.jpg' border='0' alt='antes'/></a>
with this commit:
<a href='https://postimg.cc/n9z3RnmL' target='_blank'><img src='https://i.postimg.cc/0jGhNQ27/despues.jpg' border='0' alt='despues'/></a>
> PicturePlayer: use floor division to get integer

- lib/python/Components/Opkg.py
- Remove defunct code.
- Add global variables for opkg definitions rather than hard coding the values.
- Add some new commands for future refactors.
- Deprecate the startCmd() method.  The newer and more flexible runcmd() method will be used moving forward.
As soon as code using startCmd() is updated this method and its support methods will be removed.
> [Opkg.py] Clean up and enhance the code

- lib/python/Components/International.py
The country entry of "Kurdistan" is being added to address some cultural issues.  The data used for this entry is NOT official.  The values used have been selected to not clash with current ISO designations.  While there is some clash with NATO designations the Enigma2 code is based on ISO so the clashes will be ignored for now.
> [International.py] Add a non ISO country of "KU" for "Kurdistan"

- lib/python/Screens/Processing.py
This change corrects a small visual anomaly where the initial display of the ProcessingScreen does not start at the nominated progress position.  Users may not have noticed the issue as the first update corrected the display.
> [Processing.py] Correct small visual anomaly

- lib/python/Screens/PluginBrowser.py
- Rework the package and plugin categories to simplify the categories listed to users.
- Add an ability to recategorize packages with inappropriate or malformed categories that are not managed or fixable by openATV developers.
> [PluginBrowser.py] Rework categories

- lib/dvb/pmt.cpp
- lib/dvb/pmt.h
- lib/python/Navigation.py
- lib/python/Screens/InfoBarGenerics.py
- lib/service/elistboxservicecontent.cpp
- lib/service/listboxservice.cpp
- lib/service/servicedvb.cpp
* add zap delay if stream relay active to prevent "no free tuner".
* show correct provider, namespace, transponder and frontend info for stream relay services
* show recording indicator in channel selection for stream relay services
PLEASE NOTE!!
All of this will only work if you use whitelist_streamrelay.
Some parts are taken from openVix.
Thanks to @DimitarCC
> StreamRelay

- lib/python/Screens/EventView.py
This change uses `date.dayshort` instead of `date.long`.
EPG data is pretty much guaranteed to be less than a year ahead.  Even if further than a year away, that would be inferred by overlapping months.
> Show eg. `Wed 29 Nov` instead of `29 Nov 2023`

- lib/python/Screens/MessageBox.py
- The summary screen was looking at itself rather than the parent to see if the "list" widget exists.  It now correctly looks at the parent.
> [MessageBox.py] Correct summary display

- lib/python/Screens/MessageBox.py
This commit correct an error in the previous commit where it was assumed that the list object only existed if a list was specified or type was TYPE_YESNO.  The list is now checked for actual content.
> [MessageBox.py] Correct a crash created by the last commit

- lib/python/Screens/MessageBox.py
The dummy widget has been restored as some skins do not check if the "list" widget actually exists before manipulating it.  The widget is optional and code should be checking that the widget is available *BEFORE* trying to manipulate it.  This hack has been restored to give skinners more time to correctly fix their skins!
> [MessageBox.py] Restore unused widget definitions

- lib/python/Screens/InfoBarGenerics.py
- `setEndime` date was always today
too, on a event which ends tomorrow. --> TimeDateInput refactory
- Prepare for https://github.com/GhostofGeeeee/enigma2/tree/TimeDateInput refactory
- `changeDuration` needs `marginAfter = 0` too.
- Abort `setEndtime` on creation should be indefinitely
- Focus on Clock `dlg.keyDown()`
Please feel free to help me proper the commit documetaion
> [Instant Record] Improvements + fix setEndime+changeDuration

- data/keymap.xml
This new action map will allow code to grab or reassign the PREV and NEXT buttons for other uses.
The original button usage design used these buttons for navigation but many users complained and wanted them reserved for editing.  This commit is a workaround to allow these buttons to be remapped back to navigation on a case by case basis.
> [keymap.xml] Add new PreviousNext action map

- lib/python/StartEnigma.py
- Replace the old and defunct SimpleSummary screen with the newer ScreenSummary screen and logic.
- Improve the profile tag strings and add a few more tags to make the startup counter more granular.
> [StartEnigma.py] Update Summary screen and profile tags

- lib/python/Screens/Information.py
- lib/python/Screens/Screen.py
- lib/python/skin.py
[Screen.py]
- Add facility to have a screen based image based on the class name of the screen.
- Add new methods "isAlreadyShown()", "setStandAlone()" and "getStandAlone()" to replace direct access to the "self.already_shown" and "self.stand_alone" variables.
- Add "already_shown" and "stand_alone" properties to support legacy code that is manipulating the old internal variables.
- Add new methods "setImage()" and "getImage()" to fine control the new screen based image facility.
- Remove logging of the screen names as this is already done in "skin.py".
- Improve variable names.
[skin.py]
- Add new "screens" dictionary for the new screen based image system.
- Add code to read the "screens" tag block from the skin.
- Correct the variable name in the "menu" tab block reader.
- Improve some …
> [Screen] Add integrated screen based images

- lib/python/Screens/ChoiceBox.py
This change corrects an error created by using a variable from a newer version of ChoiceBox that is not yet ready to commit.
> [ChoiceBox.py] Catch and correct an argument error

- lib/python/Components/Converter/ClockToText.py
This clears up a deprecation warning from Python "builtins.DeprecationWarning: Plural value must be an integer, got float".
> [ClockToText.py] Use floor division to avoid getting a float

- lib/python/Screens/Setup.py
Remove the "setupimage" code and swap to the new screen "Image" based code instead.  This changes removes some code from "Setup.py" and uses the common code in "Screen.py".  Functionality is unchanged.
Skinners: You will need to rename the "setupimage" widget in your skins to "Image".
> [Setup.py] Switch to new screen image system

- lib/python/Components/International.py
The translation of "Thailand" should be "ประเทศไทย". This is a common form of the country name.
The current translation "ราชอาณาจักรไทย" is only use for the official full form "Kingdom of Thailand".
> [L10n] Update International.py: "ราชอาณาจักรไทย" -> "ประเทศไทย"

- lib/python/Screens/ButtonSetup.py
- lib/python/Screens/ChannelSelection.py
- lib/python/Screens/EpgSelection.py
- lib/python/Screens/InfoBarGenerics.py
- create, fill and refill a virtual (groupedservices.virtualsubservices.tv) bouquet
- if subservices available, they can be entered via
- "Reception Lists"
- ChannelContextMenu new item added
- Hotkey
[InfoBarGenerics]
- add method for ButtonSetup
[ButtonSetup]
- append "Show subservices"
[EpgSelection]
- provide a subservicelist for all EPG's but a bouquet change isn't available
For issues: 3163, 3164
> [ChannelSelection] Subservices

- lib/python/Components/Converter/EventInfo.py
This temporary work around solves an f-string issue for Python 3.11 users.
> [EventInfo.py] Work-around for Python 3.11 users

- lib/python/Components/Converter/RemainingToText.py
This temporary work around solves an f-string issue for Python 3.11 users.
> [RemainingToText.py] Work-around for Python 3.11 users

- data/keymap.xml
This is a new action map to allow for a future clarification that will make all VirtualKeyboard actions use a standardised case.
Having two separate action maps that differ by the case of one letter that do very different things is not a good idea and can cause confusion.
> [keymap.xml] Add new ShowVirtualKeyboardActions action map

- lib/python/Plugins/Extensions/FileCommander/keymap.xml
- lib/python/Plugins/Extensions/FileCommander/plugin.py
- lib/python/Plugins/Extensions/FileCommander/setup.xml
[plugin.py]
- Add legacy navigation mode.  This allows the legacy navigation where LEFT/RIGHT are page up/page down and CH+/- are left panel/right panel respectively.  Unified navigation uses LEFT/RIGHT as left panel/right panel and CH+/- is page up/page down.  The latter has been created to make all screen navigations more consistent and predictable.
- Add an auto multi-selection mode.  This option causes the multi-selection mode to be disabled after the nominated command has been executed.
- Add options to select all, deselect all, and toggle selections.
[setup.xml]
- Add the configuration option for legacy navigation mode.
- Add the configuration option for auto multi-selection mode.
[keymap.xml]
- Add KEY_RECORD to allow for the toggle selections action.
> [FileCommander]  Address user requests

- lib/python/Components/Sources/EventInfo.py
Enigma2 times used for displays, and most processing, are in whole seconds.
> [EventInfo.py] Ensure that times are an integer

- lib/python/Components/AVSwitch.py
- lib/python/Screens/InfoBarGenerics.py
- lib/python/Screens/Menu.py
- lib/python/Screens/StartWizard.py
- lib/python/Screens/VideoMode.py
- lib/python/Screens/VideoWizard.py
This code is about to be refactored as well as some associated configuration code related to the GUI position and 3D settings. This name change brings this mechanism into line with similar instances.
[InfoBarGenerics.py]
- Use the new avSwitch class instantiation pointer.
[Menu.py]
- Use the new avSwitch class instantiation pointer.
[StartWizard.py]
- Use the new avSwitch class instantiation pointer.
[VideoMode.py]
- Use the new avSwitch class instantiation pointer.
[VideoWizard.py]
- Use the new avSwitch class instantiation pointer.
> [AVSwitch.py] Prepare for a refactor

- data/Makefile.am
- data/menu.xml
- data/setup.xml
- data/wizardosdcalibration.xml
- lib/python/Screens/OSDCalibration.py
- lib/python/Screens/WizardOSDCalibration.py
- lib/python/StartEnigma.py
This change is in preparation of a major refactor of the "UserInterfacePositioner.py" code and its associated Wizard "WizardUserInterfacePositioner.py".  This commit has minimal code changes and is focused on introducing the new module names and new classes.  This will give skinners time to prepare skins for the code changes when they are committed.
At this time skinners should be aware that the new screen name for "UserInterfacePositioner2" will be "OSDCalibration".  When this commit is merged skinners should add a conditional widget "description" that will replace the current widget "status".  The "conditional" attribute should be used on the "description" widget to suppress skin errors until the new OSDCalibration code based on "Setup" is published.  Skinners should also add the …
> [OSDCalibration.py] Prepare for a major refactor

- data/keymap.xml
- data/menu.xml
- data/setup.xml
- lib/python/Components/ConfigList.py
- lib/python/Screens/OSDCalibration.py
- lib/python/Screens/Setup.py
[Setup.py]
- Add code to check if the attribute "allowDefault" as been added to a "setup.xml" "setup" tag.  If so, tell "ConfigList.py" to allow the new "default" option.
[ConfigList.py]
- Add an optional calling argument that enables the new reset to default option.
- Create a method "keyDefault()" to implement the default action.  This can be redefined in sub-classes to implement custom default resets.
- Add a YELLOW button to the Setup screen that offers the "Default" action if the YELLOW button is available,
- Add the button AUDIO to trigger the default in all cases, even if the YELLOW button is otherwise allocated.
[OSDCalibration.py]
- Remove the custom screen for "OSD3DCalibration" as this can now be handled by the "Setup" class directly.
[menu.xml]
- Restore the "setup" tag to run …
> [Setup] Add an option to reset all entries to default

- lib/python/skin.py
This change allows individual screens to have the screen image turned off even if there as a default image for that class of screen.
To turn off/disable the screen image for any screen simply set the skin "image" attribute to an empty string.  That is:
>  image=""
> [skin.py] Allow images to be turned off

- lib/python/Components/Converter/XmlMultiContent.py
- lib/python/Components/Renderer/Listbox.py
- lib/python/Components/Sources/List.py
- lib/python/skin.py
- This change introduces XML based skin templates.  The old Python based templates are now deprecated.  When they are no longer needed all code that supports them will be removed.
- The new XML templates now use standard skin based attributes rather than Python code fragments and Python variable names.
- The index into the data tuples with the data to be formatted can now be specified by index number into the tuple and by a new variable name mechanism. This now means that as long as the code behind the skin keeps the same variable name the actual tuple order can now be changed without requiring a skin change.
- The templates can be defined in-line within a screen definition or they can be collected into a separate "skinTemplates.xml" file.
[skin.py]
- Add new XML based multi-content …
> Major skin enhancement

- data/setup.xml
- lib/dvb_ci/dvbci.cpp
- lib/python/Components/AVSwitch.py
- lib/python/Components/UsageConfig.py
- lib/python/Screens/OSDCalibration.py
- lib/python/StartEnigma.py
- lib/service/servicedvd.cpp
[AVSwitch.py]
- Complete rewrite and optimization of the code.
- Remove dead code and duplicated methods.
- Use C++ helper code to reduce the Python code complexity.
- Move "config.osd" ConfigSubsection here from"StartEnigma.py" and "UsageConfig.py" here as this is where it is most appropriate.
- Raname "iAVSwitch" to "avSwitch" to better reflect its definition and usage.  The old name pointed to the new name to keep old code functional.
[StartEnigma.py]
- Remove "config.osd" ConfigSubsection definition and move it to "AVSwitch.py"..
- Remove the defunct "config.osd.language" definition and use the newer "config.misc.locale" definition.  The "config.osd.language" functionality is still maintained for code that has not yet been fixed. Note that "config.osd.language" is …
> AVSwitch and related code refactor

- lib/python/Screens/OScamInfo.py
reader names like 'Vip%2bMax' are now displayed correctly as 'Vip+Max'
> [OSCamInfo]  bugfix: unquote strings for Reader/Users

- lib/python/Screens/Menu.py
This change ensures that the C++ default navigation is disabled so that only the ActionMap navigation is used.
> [Menu.py] Use only ActionMap navigation

- lib/python/Screens/ChannelSelection.py
This commit corrects the legacy navigation where the buttons for previous and next bouquet selection were reversed.
> [ChannelSelection.py] Correct legacy bouquet navigation

- lib/python/skin.py
Correct a deprecation warning from Python being logged in the Enigma logs.
> [Skin.py] Correct deprecation warning from Python.

- lib/python/Components/VolumeControl.py
- Remove the restriction that stopped mute being applied if the volume was set to 0.
- When the volume is set to 0 silently apply mute to avoid a driver issue on VU+, and possibly other receivers, that do not silence the audio when the volume level is set to 0.
> [VolumeControl.py[ Code adjustments to address feedback

- lib/python/Components/UsageConfig.py
- Remove translations of the button names as this is incorrect.
- Separate some of the combined buttons so that the selection can be better matched to real remote controls.
> [UsageConfig.py] Correct "long_press_emulation_key"

- lib/python/Screens/ServiceScan.py
The callback to trigger a display skin update for a change in progress was accidentally omitted.  This commit corrects that omission.
Also, correct the widget type for the Title widget in the display screen.
> [ServiceScan.py] Add missing callback

- lib/python/Screens/OScamInfo.py
> [OSCamInfo] bugfix: no attribute 'activeComponents'

- lib/service/servicedvb.cpp
(copying patch from openPLi, commit ad0660b): Some receivers have a bug in the file drivers that deliver subtitles on playback of records completely out of sync with the video, making them unusable. This PR slightly adjusts the bad timing handler to treat subtitles that have been delivered too early by the filesystem as valid and to queue them up for showing later at the appropriate time. The handling of subtitles that arrive too late remains unchanged.
> Fix subtitle runahead on recordings

- data/setup.xml
- lib/python/Components/UsageConfig.py
- lib/python/Screens/OScamInfo.py
- OSCamInfo screen: show binary signing information if oscam binary was signed
- OSCamInfo screen: adjust some elements in position and size
- OSCamInfoSetup screen: ip address option now also accepts dns names (config.oscaminfo.ip, default=127.0.0.1)
- OSCamInfoSetup screen: new default value for port option (config.oscaminfo.port, default=83)
- OSCamInfoSetup screen: new option to enable the use of https protocol (config.oscaminfo.usessl, default=off)
- OSCamInfoSetup screen: new option to enable certificate verifying (config.oscaminfo.verifycert, default=off)
> [OSCamInfo] plugin improvements

- lib/python/Components/config.py
Remove some redundant toString() methods as they are the same as the base class upon which each of the classes that contain the duplications is based.
> [config.py] Remove redundant methods

- lib/python/Plugins/Extensions/FileCommander/plugin.py
- lib/python/Screens/ChoiceBox.py
couldn't handle bookmarks with "," in path.
Don't use .split(",") and ",".join() to use ConfigText as list.
Use list as string for ConfigText.
> config.misc.pluginlist.fc_bookmarks_order

- lib/python/Screens/MovieSelection.py
- A few small code optimizations.
- Stop using Button() widgets and move to StaticTest() widgets for buttons as per BUTTONGUIDE.
- Adjust code to account for the Button() to StaticTest() change.
- Use F-strings.
- Use consistent quoting.
> [MovieSelection.py] Code tidy up

- lib/python/Screens/MovieSelection.py
This change allows empty directories to be deleted.  For some reason this was previously prohibited.
If anyone knows why this was previously not allowed and there is still an objection to this fix then please post some details so the fix can be reviewed.
> [MovieSelection.py] Make empty directories deletable

- lib/python/Components/VolumeControl.py
- lib/python/Screens/InfoBarGenerics.py
Issue #3504 Infobar opens the muteDialog, but couldn't handle it.
Now Infobar open and close it together.
The muteDialog will not longer coverup other Screens while its open, this is only desired for a volume action.
Fix a Bug that an open Infobar cancels the volumeMuteLong action.
> Link/connect Infobar and muteDialog

- lib/python/Components/VolumeControl.py
- lib/python/StartEnigma.py
[VolumeControl.py]
- Register a method to be called by the existing shutdown mechanism.
- Add some logging to show the module startup and shutdown.
- Move a small block of code into a more logical position.
[StartEnigma.py]
- Remove the special call to shutdown the volume control module.
- Use a more consistent callback variable name.
> [VolumeControl] Use existing shutdown code

- lib/python/Screens/ChannelSelection.py
- don't let the history empty(on startup), this can crash.
> [ChannelSelection] improve Subservices

- lib/python/Screens/EpgSelection.py
- don't lose PiP state on close EPG by zap etc..
Reproduzieren(nur ein einfaches Beispiel):
- **PiP an**
- EPG lang + EPG vom aktuellen Sender
- OK(EPG schließt, **PiP bleibt aktiv**)
- Blau drücken(da sollte unter anderen "Bild-im-Bild deaktivieren" stehen, **stattdessen aber "Bild-im-Bild aktivieren"**)
> [EPGSelection] restore pipshown value on close

- data/keymap.xml
- lib/python/Screens/VolumeControl.py
- Correct an issue where the changes made in the VolumeAdjust settings screen were not fully reverted if the user cancelled the changes.
- Correct an issue where the "TVRadioActions" keymap was duplicated with different keys.
> [VolumeControl.py] Fix keymap and cancelling changes

- data/keymap.xml
- lib/python/Screens/InfoBar.py
- lib/python/Screens/InfoBarGenerics.py
The functionality of the TIMER button is duplicated in both the InfoBar.py and InfoBarGenerics.py modules.  This change removes the InfoBarGenerics.py duplication.  The defunct key map is also removed.
> [InfoBar] Remove duplicated timer button class

- lib/python/Screens/VolumeControl.py
This change protects against the following error:
```
2025-07-12 16:42:36.1265   File "/usr/lib/python3.13/html/__init__.py", line 130, in unescape
2025-07-12 16:42:36.1267 TypeError: argument of type 'NoneType' is not iterable
```
If the volume.xml file is incorrect or invalid.
> [VolumeControl.py] Defend against invalid volume.xml files

- lib/python/Components/AVSwitch.py
The BoxInfo.getItem("ChipsetString") data is already a string and does not need to be cast to become a string.
> [AVSwitch.py] Remove unnecessary cast to string
