lib/python/Components/Timeshift.py

http://www.opena.tv/plugins/13277-timeshift-dauer-begrenzen.html

[Timeshift.py] new: polling of the timeshift folder if files can be deleted (faster cleared = less of space usage)

---

data/setup.xml
lib/python/Components/Timeshift.py
lib/python/Components/UsageConfig.py

New options "Timeshift events limit" ,  "Timeshift checking for older
files" and "Timeshift check free space"added, last changes reworked and
optimized

[Timeshift.py] new options - see description

---

lib/python/Components/Converter/ServiceInfo.py

http://www.opena.tv/openatv-4-2-rueckmeldungen/14621-reproduzierbares-fehlverhalten-aufnahmen-ansehen-live-tv.html
http://www.opena.tv/edision-optimuss-os2-plus/13520-fehler-osd-emc-progressbar.html

[ServiceInfo.py] fix possible skin error on some box types

---

lib/python/Components/Timeshift.py

fix possible bs:
http://www.opena.tv/vu-solo-2-a/15184-nonstop-crash-post134489.html#post134489

[Timeshift.py] fix file size counter in last commit

---

lib/network/serversocket.cpp
lib/network/serversocket.h
lib/network/socket.cpp
lib/network/socket.h

Supports IPv4-only kernels as well.

[streaming] Portable code for IPv6-streaming

---

lib/python/Plugins/Extensions/MediaPlayer/plugin.py

see-->http://www.opena.tv/openatv-5-0-rueckmeldungen/16484-mediaplayer-post146650.html#post146650

[MediaPlayer] next adjusting on pauseEntry

---

lib/python/Plugins/Extensions/MediaPlayer/plugin.py

see-->http://www.opena.tv/openatv-4-2-rueckmeldungen/16402-mediaplayer-kein-seitenweise-vorblaettern-mehr-moeglich-atv-4-2-vom-18-05-15-a-post146161.html#post146161

[MediaPlayer] adjusting for left/right

---

lib/python/Screens/LogManager.py

replace the unicode <control> character in LogManagerViewLog

replace unicode character in ViewLog

---

po/es.po

Here's an updated translation for Spanish language. Based on your 2015-07-05 [de.po] file.
I added a lot of strings that there weren't in the original file.

[es.po] Updated translation

---

lib/python/Components/ConfigList.py

AttributeError: 'VideoSetup' object has no attribute 'HideHelp'

fix last commit

---

lib/python/Plugins/SystemPlugins/SoftwareManager/Flash_online.py

tested with quad+ and Red Eagle Twinbox LCD

[flash_online.py] speedup download time on some boxes

---

data/display400/skin_display.xml

fix size of 
+ Movieplayer
+ MovieSelection
+ add Mediaplayer Screen

[display400] update Skin > fix size of some Screens

---

lib/python/Screens/InfoBarGenerics.py

Makes event description scrollable in SecondInfoBar (screen)

Event description scrollable in SecondInfoBar

---

data/keymap.xml

Makes event description scrollable in 2ndInfobar.

Add 2ndInfobarActions

---

lib/dvb/epgcache.cpp

This fix broken epg in channel selection on sh4 boxes.
Thanks @Taapat

fix optsidonid size in find customeitpids

---

lib/dvb/epgcache.h

Movistar+ 7 days EPG and other improvements.

MHW2 EPG improvements

---

lib/python/Components/Sources/CurrentService.py

Allows Cover display in MoviePlayer

---

lib/python/Screens/EventView.py

Allows to translate similar broadcasts format

---

po/nl.po

Imported latest from the POT-file, and added new translations. Completed for 86%

Updated Dutch PO-file / Translation

---

RecordTimer.py

Add Short filename with date and time

Update RecordTimer.py - Add Short filename with date and time

---

lib/python/Components/RecordingConfig.py

Update RecordingConfig.py - Add Short filename with time

---

po/de.po

Add short filename with time (RecordingConfig.py)

Update de.po - Add short filename with time (RecordingConfig.py)

---

lib/python/Screens/VirtualKeyBoard.py

There was a mistake since the previous one was Polish.

Spanish keyboard corrected

---

po/nl.po

Total now at 97%. 136 lines left.

Updated Dutch PO.

---

po/nl.po

* Updated the Dutch PO with 50+ new translation strings not yet merged into the official POT.
* Fixed some typo's etc.

Updated the Dutch PO

---

po/nl.po

* Added 5 new entry's
* Good Cleanup

Updated Dutch PO

---

po/fr.po

Update fr.po with more accurate translations

---

lib/python/Plugins/SystemPlugins/VideoTune/VideoFinetune.py

forget the fontsize of the numbers

[VideoFinetune] fix last commit

---

po/el.po

Official Greek full Greek translation for OpenATV, based on the last enigma2.pot 16/6/2016

Greek translation full update 16/6/2016

---

lib/python/Screens/ButtonSetup.py

if we have more than one option on a hotkey
the title would not be translated on the choicebox

[hotkey] fix translation in choicebox

---

po/el.po

Greek translation update 19/6/2016

Greek translation update 19/6/2016

---

lib/python/Screens/EpgSelection.py

if we use text-button in EPG_TYPE_GRAPH and EPG_TYPE_INFOBARGRAPH now jumps to correct time

[EpgSelection] fix jump to correct time ( text-button )

---

po/el.po

Revised el.po in sync with enigma2.po and de.po, no problems with sync!

Greek translation update 6/7/2016

---

po/el.po

Greek translation update 31/7/2016

Greek translation update 31/7/2016

---

data/setup.xml
lib/python/Components/UsageConfig.py
lib/python/Screens/EpgSelection.py

This adds option of allowing (to a certain degree) re-assigning of the four coloured keys buttons within Graphical EPG.
Thanks to bbbuk/ketmp/darkdreamdan/matt007

Add option of re-assigning coloured key within G-EPG

---

data/displaytext/skin_display.xml

add MovieMenu, Timer, AutoTimer, PowerTimer-Screen
change JobView-Screen
fix EMCSelection-Screen

[displaytext] change/add some screens ..

---

po/el.po

Greek translation update 8/8/2016

Greek translation update 8/8/2016

---

po/el.po

Greek translation update 29/8/2016

Greek translation update 29/8/2016

---

po/el.po

Greek translation update 10/9/2016

Greek translation update 10/9/2016

---

el.po

Greek translation update 13/9/2016

Greek translation update 13/9/2016

---

lib/python/Screens/ResolutionSelection.py

Allow translation of "Video: "

Allow translation

---

lib/python/Components/EpgList.py
lib/python/Components/UsageConfig.py
lib/python/Screens/EpgSelection.py

Add guidebouquetlist for supported skins (epgtabs)

Add optional channel numbers on epg 

---

lib/dvb/epgcache.cpp
lib/python/Components/Renderer/NextEvents.py

see http://www.opena.tv/die-bastelecke/28812-chennelselection-verbesserungsvorschlag-post254914.html#post254914

Add NextEvents - thx tecfan69

---

po/el.po

Greek translation update 24/10/2016

Greek translation update 24/10/2016

---

po/en.po
po/openATV-enigma2.pot

NEW CREATED
Full and %100 Compatible Proper Version
(only openatv)
Generated: TM2TURK by thawtes

Add openATV enigma2 new POT file [tm2TURK]

---

po/el.po

Greek translation update 16/11/2016

Greek translation update 16/11/2016

---

po/el.po

Greek translation update 23/11/2016

Greek translation update 23/11/2016

---

po/el.po

Greek translation update 5/12/2016

Greek translation update 5/12/2016

---

po/el.po

Greek translation update 22/12/2016

Greek translation update 22/12/2016

---

po/el.po

Greek translation update 2/1/2017

Greek translation update 2/1/2017

---

lib/python/Screens/BoxPortal.py

fix previous commit

---

po/el.po

Greek translation update and cleanup 11/1/2017

Greek translation update and cleanup 11/1/2017

---

lib/python/Plugins/SystemPlugins/SoftwareManager/Flash_online.py

This commit allows to translate both "Online" and "Backup&Flash".

Allow some translations

---

mytest.py

"Transponder Time" can be translated now.

Translation allowed

---

lib/python/Plugins/SystemPlugins/SoftwareManager/BackupRestore.py
po/nl.po

* Added /etc/feeds.xml to backup process. (Used by the rssreader)
* Removed /etc/enigma2/automounts.xml as its backup'd 2 times now. (Please review)
* Updated the nl.po

Changes to the backup process & nl.po update

---

po/el.po

Greek translation update 23/1/2017

Greek translation update 23/1/2017

---

lib/service/servicemp3.cpp

The new way of works also needed another way for position keeping.
Now position for audio only does work back ok.
By codecs using the mpeg unpack and who have a missing pts on the video
will now also have a position keeping.

Forgotten issue by previous patch serviceMP3.

---

lib/service/servicemp3.cpp
lib/service/servicemp3.h

Now the main player work also ok on emc (enhanced moviecenter)
modified:   lib/service/servicemp3.h

Adapted servicemp3 to work also ok on emc

---

po/el.po

Greek translation update 4/2/2017

Greek translation update 4/2/2017

---

lib/service/servicemp3.cpp
lib/service/servicemp3.h

modified:   lib/service/servicemp3.h

EMC hack for resume and cuesheet

---

lib/service/servicemp3.cpp

Preparation on some extra seek changes

---

po/el.po

Greek translation update 21/2/2017

Greek translation update 21/2/2017

---

lib/dvb/frontend.cpp

Update to 1620, as maximun dB is 16.2
I hope this fixes the low SRN rates displayed.

Update "Si21662" sat_max

---

po/el.po

Greek translation update 26/2/2017

Greek translation update 26/2/2017

---

lib/service/servicemp3.cpp
lib/service/servicemp3.h

This commit does requires the very last dvbmediasink update

Dev New position updated procedure

---

lib/service/servicemp3.cpp

Gstreamer 0.1 compile error due to previous patch.

---

lib/service/servicemp3.cpp
lib/service/servicemp3.h

Requires last update dvbmediasink

Further changes eservicemp3 Player

---

lib/service/servicemp3.cpp
lib/service/servicemp3.h

modified:   lib/service/servicemp3.h

Position taking correction

---

lib/python/Components/EpgList.py

It makes time and date formats adaptable to each country norm.
There is also a small cosmetic change.

Time & date formats made changeable

---

lib/python/Screens/Setup.py

[Setup] add support for passing 'PluginLanguageDomain' so plugin setup.xml can be translated properly.

PluginLanguageDomain

---

lib/python/Components/MovieList.py

we can see it in "Movie Center"-Screen

[MovieList] make picon transparent ( AlphaBlend )

---

po/el.po

Greek translation update 2/5/2017

Greek translation update 2/5/2017

---

po/sk.po

Translation for some new texts and various corrections of previous Slovak translation. Translating can proceed if you will be satisfied with my work.

Update of sk.po for Enigma 2

---

po/sk.po

New translations for some texts were added, part of older translation was corrected and unified. Language file was shortly tested. This process will continue, if you will be satisfied with my work.

Translation of new texts, older texts corrected and unified.

---

data/display220/skin_display_picon.xml

[disply220] emc screen

---

po/it.po

I saw some mistakes or missing labels and tried to fix them (in the italian translationfile).

Update some translations, some typos or missing labels

---

po/el.po

Greek translation update 1/8/2017

Greek translation update 1/8/2017

---

lib/python/Components/Converter/TunerInfo.py
lib/python/Components/Sources/TunerInfo.py

Currently the function "TUNER_AVAILABLE" is missing in TunerInfo.py.
This feature is used to show the available/used tuners on the VFD/LCD display.
Tested locally and working.
(Was struggling with the Python indent, so please check before merging.)

Added the "TUNER_AVAILABLE" feature to TunerInfo.py.

---

lib/python/Screens/About.py

at this moment only for Gigablue Quad 4K

[about.py] add system temp gb4k  / second try

---

lib/base/httpstream.cpp

Thanks to @littlesat of PLi. 
From this commit https://github.com/OpenPLi/enigma2/commit/c288bdf16fe92ad2e63802466024c358c78f502c

 Solve an issue when starting fallback/remote streams from same TP

---

lib/python/Screens/EventView.py

"summary_description" widget fix

---

lib/python/Components/Lcd.py

- change to better LCD-PIP-modes
- more MiniTV options

[Lcd.py] Update for Gigablue LCD-PIP and LCD-MiniTV

---

lib/python/Screens/MinuteInput.py

fix crash based on ..
https://github.com/OpenViX/enigma2/pull/192

[MinuteInput.py] Fix crash - thx prl001

---

po/el.po

Greek translation update 19/10/2017

Greek translation update 19/10/2017

---

po/enigma2.pot

add missing strings, from plugins and dev branch re check

Update enigma2.pot ( missing strings , part-1)

---

lib/dvb/Makefile.inc
lib/dvb/db.h
lib/dvb/demux.cpp
lib/dvb/demux.h
lib/dvb/dvb.h
lib/dvb/filepush.cpp
lib/dvb/filepush.h
lib/dvb/pmt.h
lib/dvb/rtspstreamserver.cpp
lib/dvb/rtspstreamserver.h
lib/dvb/sec.h
lib/service/servicedvbstream.cpp
lib/service/servicedvbstream.h

The RTSP URL respects satip specifications (http://www.satip.info/sites/satip/files/resource/satip_specification_version_1_2_2.pdf) and supports the following methods:
- OPTIONS 
- DESCRIBE (for obtaining the signal and stream info)
- PLAY
-SETUP (only tcp mode is supported)
PLAY command can be used to add/remove pids (pids=, addpids= and delpids= options are supported).
The restriction is that only one frequency can be played at one time (no multiple SETUP/PLAY with different frequencies supported). That's why is needed a SAT>IP server that can overcome those limitations and implement a full satip protocol that can be used by another applications:
To use the RTSP in standalone mode, ffmpeg can be used with the following command line:
ffplay -rtsp_transport tcp  -i …

Add RTSP/TCP server for enigma2 on port 8554

---

lib/python/Screens/EventView.py
po/nl.po

Latest PR broke the showing of event information on the VFD screen/skins. 
https://github.com/openatv/enigma2/commit/b18071fa08639be62bea52b70d08d44bdb06cfb6#commitcomment-25265354

Revert latest EventView.py commit

---

lib/dvb/rtspstreamserver.cpp

- remote service_list array and n_service_list as they are unused
- run searchServiceRef just once

rtsp server changes

---

data/setup.xml

because this option is not for MultiEPG settings
it is only for single EPG

[setup.xml] remove option "Sort list by" from MultiEPG settings

---

po/el.po

Greek translation update 4/12/2017

Greek translation update 4/12/2017

---

po/el.po

Greek translation update 28/12/2017

Greek translation update 28/12/2017

---

lib/python/Screens/About.py

as a scrolllabel with all information from "nims", "hdd" and "mounts"

[about.py] add a widget "allinonedevices" for screen "devices"

---

lib/python/Components/UsageConfig.py

Added Indonesian on config menu 'auto languange selection'.

Auto Language Selection for Indonesian

---

data/7segment/skin_display.xml
data/display128/skin_display.xml
data/display128dm/skin_display.xml
data/display220/skin_display.xml
data/display220/skin_display_picon.xml
data/display390/skin_display_picon.xml
data/display400/skin_display_picon.xml
data/display480/skin_display.xml
data/display480/skin_display_picon.xml
data/display720/skin_display.xml
data/display720/skin_display_picon.xml
data/display800/skin_display_templates.xml
data/displaytext/skin_display.xml
data/grautec70x0/skin_display_grautec.xml
data/grautec8000/skin_display_grautec.xml

* Added the new EMCSelectionSummary name to defealt skins.
* Small correction to display800 picon. (as requested here :  https://www.opena.tv/vu-ultimo-4k/34181-ultimo4k-display-skin-mod-post336422.html#post336422 )

VFD skin fix for EMCSelectionSummary

---

po/el.po

Greek translation update 8/3/18

Greek translation update 8/3/18

---

data/displaytext/skin_display_alternate.xml

This fixes broken standby time on alternate display skin on Xpeed LX1

Fix broken standby time

---

lib/python/Components/Sources/StaticText.py
skin.py

Thanks to @littlesat  and @Huevos

Conditionally show png button files

---

lib/python/Screens/VirtualKeyBoard.py

add hu_HU virtual keyboard

---

lib/python/Screens/NetworkSetup.py

Yesterday I pasted code in wrong class!!
Sorry

Add config file in OpenVpn

---

lib/python/Screens/NetworkSetup.py

Added an inputbox call used to choose openvpn config file name

Update NetworkSetup.py - OpenVpn config file name

---

lib/python/Components/EpgList.py
lib/python/Components/UsageConfig.py

Also reduced minimum picon width to 50 
Please check this previous commit before committing bug should be fixed https://github.com/openatv/enigma2/pull/546

Add optional numbers on Graphical EPG

---

po/el.po

Greek translation update (6.2 branch) 6/9/2018

Greek translation update (6.2 branch) 6/9/2018

---

po/el.po

Greek translation update 26/9/2018
NOTE: This is both for 6.2 and DEV, please push accordingly

Greek translation update 26/9/2018

---

po/sk.po

Translation synchronized with latest POT, new texts were translated, marked texts were checked. Older translation was edited, if I found some problem or inconsistency in terminology.

Update of SK translation for Enigma2

---

lib/dvb/pmt.cpp

This is my first pull request ever.
This fixes #935.

few small fixes for automatic audio language selection

---

data/encoding.conf
lib/base/encoding.cpp
lib/base/encoding.h
lib/base/estring.cpp
lib/base/estring.h
lib/dvb/scan.cpp
main/enigma.cpp
tools/enigma2.sh.in

tested and confirmed, now convert dvb to utf8 work correctly.

estring: fix the first byte checked fail about requst about # 1043

---

lib/python/Screens/ServiceInfo.py

fix gamma tuple index out of range for the unsupport video.

---

lib/gdi/gfbdc.cpp
lib/gdi/grc.cpp
lib/gdi/grc.h
lib/gui/elistbox.cpp
lib/gui/elistbox.h
lib/python/Plugins/SystemPlugins/AnimationSetup/plugin.py
lib/python/enigma_python.i
lib/service/listboxservice.cpp
main/enigma.cpp
po/enigma2.pot

Support focus animation for listbox
Based on
http://code.vuplus.com/gitweb/?p=vuplus_dvbapp;a=commitdiff;h=74f5884fdc5a23465cf40c27b5c069ff7d882746

[vuplus] support focus animation for listbox

---

po/el.po

Greek translation update 23/1/2019

Greek translation update 23/1/2019

---

po/el.po

Greek translation update 14/3/2019

Greek translation update 14/3/2019

---

po/el.po

Greek translation update 12/4/2019

Greek translation update 12/4/2019

---

po/el.po

Greek translation update 27/4/2018

Greek translation update 27/4/2018

---

data/startwizard.xml
lib/python/Screens/InstallWizard.py
tools/enigma2.sh.in

Add to start wizard so user can choose

[Default sat] Do not force install.

---

po/el.po

Greek translation update 13/5/2019

Greek translation update 13/5/2019

---

lib/python/Screens/VirtualKeyBoard.py

- Update the locale function names to better match the keyboard definitions used in http://kbdlayout.info/ which is the reference source for these layouts.
- Add the Ukrainian (Enhanced) layout and make it the default.  (This was requested by OpenATV.)

[VirtualKeyBoard.py] Update locale function names

---

lib/python/Screens/VirtualKeyBoard.py

This change unifies the definition and various uses of the space character into a single variable.  This ensures that the representation of the space character and icon are synchronised across the code.

[VirtualKeyBoard.py] Unify SPACE definition

---

lib/python/Screens/VirtualKeyBoard.py

This change makes the delete forward and delete backward method names follow the style used elsewhere in this code.

[VirtualKeyBoard.py] Improve method names

---

po/el.po

Greek translation update 4/6/2019

Greek translation update 4/6/2019

---

data/menu.xml

The current name does not mention anything about tuners. Tuners and scanning covers both terms

[Menu] Rename service searching

---

po/el.po

Greek translation update 4/7/2019

Greek translation update 4/7/2019

---

lib/python/Tools/Directories.py

Optimise use of os.path.normpath() by only optimising the path at the end of processing.

[Directories.py] Optimise and simplify code

---

po/sk.po

Update of Slovak translation for Enigma2 (6.3). New texts were translated, fuzzy matches were corrected or confirmed. This translation was shortly tested.

Update of Slovak translation for Enigma2 (sk.po)

---

lib/python/Components/NimManager.py

NimManager: add new method "getNimListForSat"

---

po/sk.po

Update of Slovak translation, all the new and edited strings are translated now.

Update of SK translation for Enigma 2 (6.3)

---

tools/enigma2.sh.in

The previous change was not required and made the changes look more significant.

[enigma2.sh.in] Use "$datarootdir" shell variable as per original

---

tools/enigma2.sh.in

This proposed change is not acceptable to all images.  I will revert to the previous mode of operation.

[enigma2.sh.in] Revert skin based backdrop logo

---

lib/python/Components/Language.py

Missing from Norsk Bokmål line

[Language.py] Add a space

---

po/el.po

Greek translation update 5/9/2019

Greek translation update 5/9/2019

---

data/setup.xml
lib/python/Components/PluginComponent.py
lib/python/Components/UsageConfig.py
lib/python/Screens/Menu.py

-You can enable new menu under (menu > setup > Usage & GUI > Cusomize > Show Main menu as).
-Should be to add screens of new Horizontal menu in any skin you want to support new menu.
-Important to Add screen to skin.xml to enable/shown new menu .
If skin.xml doesn't have screen or If you add it on other .xml file then Horizontal menu will not work .. Default menu will be work automatically.
-As in this cmmit you can import screens + should be add (icon1.png) in buttons folder.
https://github.com/openatv/MetrixHD/pull/385

Add New Feature Horizontal menu ... 

---

po/sk.po

New or changed texts are translated now. Translation was updated according to latest .pot file.

Update of SK translation for Enigma 2 (6.3)

---

data/unicable.xml

Unicable lnb

---

po/el.po

I think I learned German after this one...

Greek translation update 24/10/2019

---

lib/python/Tools/Directories.py

Correct a typo in the error number index to the error text function.

[Directories.py] Correct typo in error code

---

lib/python/Tools/Directories.py

- [Directories.py] Update try/except for Python 3
Update the try.except syntax to a format ready for any future Python 3 upgrades.
- [Directories.py] Add two new scopes
Add two new scopes to add more options for developers to abstract their code.
SCOPE_CURRENT_PLUGIN_ABSOLUTE returns the absolute path of the current plugin if called from within a plugin. If this scope is called from code other than a plugin it returns None.
SCOPE_CURRENT_PLUGIN_RELATIVE returns the relative path of the current plugin if called from within a plugin. The path fragment returned is relative to SCOPE_PLUGINS. Again, if this scope is called from code other than a plugin it returns None.
Using os.path.join(resolveFilename(SCOPE_PLUGINS), resolveFilename(SCOPE_CURRENT_PLUGIN_RELATIVE)) the result should be the …

Directories.py updates

---

lib/python/Components/Keyboard.py

- Obtain location of keymaps via SCOPE_KEYMAPS.
- Use Pythonic style for processing the "*.info" files.
- Report errors processing the "*.info" files.
- Simplify and optimise the keymap file parsing.
- Log the available keymaps.
- Document a proposal for finding language appropriate default keymap.

[Keyboard.py] Refactor the code

---

lib/python/Components/SetupDevices.py
lib/python/Components/Timezones.py
lib/python/Tools/Geolocation.py
mytest.py

6.4 pull requests here:
https://github.com/openatv/enigma2/pull/1529
https://github.com/openatv/enigma2/pull/1533
Please squash and merge instead of separate merge commit. Thanks

Timezone commits from 6.4 branch

---

data/setup.xml
lib/python/Components/UsageConfig.py
lib/python/Screens/EpgSelection.py
po/enigma2.pot
po/hu.po

I have upgraded the graphical EPG (EPG_TYPE_GRAPH) feature on my openATV  system.
I've modified the following:
- added Red button and Blue button options -> nextPage, prevPage, nextBouquet, prevBouquet
- Channel +/- -> nextPage / prevPage or nextBouquet / prevBouquet
I made the modifications in the graphic EPG menu with the corresponding text additions.
I think this makes the system much more usable and functional. This way I can use my system better.

Expanding the functionality of the graphical EPG

---

po/sk.po

Update of Slovak translation for Enigma2, version 6.4. Most of the new texts were translated, fuzzy were checked and corrected. 2 untranslated (fuzzy) strings will be translated later, after better specification of meaning.

Update of sk.po (for version 6.4)

---

lib/python/Components/SetupDevices.py

Also remove defunct "Timezones" import.

[SetupDevices.py] PEP8 cleanup

---

po/hu.po

Change Recepció -> Vétel beállítása
Visszafejtés -> Dekódolás

Change hu.po; Recepció and Visszafejtés

---

lib/python/Components/Timezones.py

- Check if the geolocation reports a VPN and if so ignore the results.
- Remove inappropriate code assumptions about the saved timezone values.  (Enigma2 does not save values if they are the default value but doesn't realise that the defaults could have changed.)
- Optimise the AutoTimer interface code.

[Timezones.py] More improvements and optimisation

---

lib/python/Tools/Geolocation.py

- Detect json decode errors and log an error rather than crashing.
- Fix a few log messages.

[Geolocation.py] Make code more resilient

---

lib/python/Components/Timezones.py

- Add a new DEFAULT_ZONE = "Amsterdam" for OpenPLi.
- Load and use the timezone in "/etc/localtime" if it differs from the timezone defined in Enigma2.  A warning is logged if the timezones differ.
- Improve some of the logging messages.

[Timezones.py] Changes for legacy support

---

lib/python/Components/Timezones.py

- Fix initialisation in "Classic" mode.
- Fix "posix" and "right" zoneinfo files not being properly suppressed.
- Fix the value of the "TZ" shell variable.
- Fix logging messages referring to "Directories".

[Timezones.py] Multiple fixes

---

data/setup.xml

The wording of the time zone prompt and help text adjusted / improved to address concerns expressed by a user.

[setup.xml] Change time zone wording

---

lib/python/Components/Timezones.py

Only encode strings that actually contain UTF-8 characters.

[Timezones.py] Optimise string encoding

---

lib/python/Tools/RedirectOutput.py

Adapt and match code to the OpenPLi and OpenViX versions.

[RedirectOutput.py] Synchronise code

---

lib/gdi/font.cpp

Many of these messages are seen in the Python log files. These changes make the messages more consistent with the Python logging messages.

[font.cpp] Improve logging and debug messages

---

skin.py

This change allows for the changes made to RcModel.py in the OE-Alliance code.

[skin.py] Adjust for new remote control code.

---

skin.py

This was removed when I was told it was no longer used.  The functionality is now restored but I hope this will be improved upon for a future version.

[skin.py] Restore skin part processing

---

lib/python/Components/Timezones.py

Display the current local and UTC times in the initialisation logs.

[Timezones.py] Add time display to logs

---

skin.py

- Add a mechanism to update the windowstyle to take account of all skin updates that occur after the windowstyle was first loaded.
- Update the getSkinFactor() method to allow for higher *and* lower resolution screens.

[skin.py] More improvements

---

data/keymap.xml
lib/python/Screens/VirtualKeyBoard.py

- [VirtualKeyBoard.py] Apply latest updates
- Add an erase button to clear the current text with a single remote control button press.  The PVR/MEDIA/VIDEO/etc button has been allocated this function.
- Improve the button help text.
- Add trigger to display the TEXT button (this offers the locale selection menu).
- Clean up imports to only use objects that are used.
- Correct a PEP8 error.
- [keymap.xml] Add erase action to VirtialKeyBoard
- This new action allows the user the clear all the text in the VirtualKeyBoard buffer with a single button press.

VirtualKeyBoard Updates

---

lib/python/Components/RecordingConfig.py

Input via left right is not that good.

Improve offline_decode_delay input

---

lib/python/Components/Timezones.py
lib/python/Tools/Geolocation.py

- [Geolocation.py] Allow config control of geolocation
This change adds a config entry "config.misc.enableGeolocation" to control if geolocation is run at startup.  The default is to allow it to run once every boot until the geolocation lookup succeeds and then it will never run again.  It can be enabled for one more run by setting "config.misc.enableGeolocation" to True.  It should be noted that the previous code would not allow geolocation to run more than once in any boot session.  This case is now clearly stated with an appropriate log message.
In the future "config.misc.enableGeolocation" will not be forced to False on a successful lookup but will allow the user to specifically control if geolocation is permitted to run more frequently.
- [Timezones.py] Update to match changed …

Limit geolocation use to first run wizard

---

lib/python/Screens/VirtualKeyBoard.py

This change should have minimal visual impact but can improve VirtualKeyBoard performance on some hardware.

[VirtualKeyBoard.py] Switch from "Blend" to "Test"

---

lib/python/Screens/VirtualKeyBoard.py

Make some code adjustments in preparation for migration to Python 3.

[VirtualKeyBoard.py] Make adjustments for Python 3

---

data/setup.xml
po/da.po
po/enigma2.pot

Update PiP mode description. Issue : https://github.com/openatv/enigma2/issues/1687
Danish Enigma2 Translation. Forum : https://www.opena.tv/fehlende-oder-falsche-uebersetzungen/52533-danish-translation-daenische-uebersetzung.html

Update to the translations

---

po/da.po

Updated the da.po for 6.3

---

lib/service/event.cpp
lib/service/event.h

According to the suggestions:
PiDron(gisclub.tv)
ims(openpli.org)

[event] add items field at the end of the extended description

---

lib/python/Screens/Screen.py

PEP8 code clean up and match the code to the other images.

[Screen.py] PEP8 code clean up

---

data/keymap.xml

This addresses a user request to allow OK (and ENTER) to repeat.

[keymap.xml] Allow OK and ENTER buttons to repeat

---

data/setup.xml

Allow the wizard to select any time zone area or region as well as the time zones in that area or region.

[setup.xml] Fix wizard time zone selection

---

lib/python/Screens/Screen.py

Include comments to advise about code correction for Python 3 migration.  (The commented exec lines should be swapped for 6.5.)

[Screen.py] Improve code comments

---

skin.py

- Remove superfluous int()
- Remove confusion in scrnID and screenID usage

[skin.py] Correct error in previous commit

---

lib/python/Screens/SimpleSummary.py

This is a tidy up and small optimisation of the code.

[SimpleSummary.py] Tidy up code

---

data/keymap.xml

- Start moving map blocks into more logical groupings.
- Start documenting the keymaps.
- Use a space before the self close tag for readability.
I hope that this tidy up will assist in comparing keymaps between images. This is only a start of what will probably be a long term clean up process.

[keymap.xml] Organise and document the keymap file

---

data/keymap.xml
lib/python/Screens/VirtualKeyBoard.py

[VirtualKeyBoard.py] Use optimised keymaps
[keymap.xml] Use optimised VirtualKeyBoard keymap

Optimise VirtualKeyBoard keymap usage

---

po/Makefile.am

This change updates po translations Makefile to include shortened file refs

Update po Makefile to include shortened file refs

---

po/tools/cleanUpPoFiles.py

Fixed Python 3 "print" incompatibility

Fixed Python 3 "print" incompatibility

---

po/Makefile.am
po/tools/cleanUpPoFiles.py

Fixed Python 3 "print" incompatibility (#1825)
This change 
- fixes print statements
- removes comment line from po/Makefile.am
- simplifies sed calls in po/Makefile.am

Po tool Python 3 compatibility (#1825) & Makefile tweaks

---

lib/python/Plugins/Extensions/CutListEditor/meta/plugin_cutlisteditor.xml
lib/python/Plugins/Extensions/DVDBurn/meta/plugin_dvdburn.xml
lib/python/Plugins/Extensions/DVDPlayer/meta/plugin_dvdplayer.xml
lib/python/Plugins/Extensions/FileCommander/addons/dmnapim.py
lib/python/Plugins/Extensions/MediaPlayer/meta/plugin_mediaplayer.xml
lib/python/Plugins/Extensions/MediaScanner/meta/plugin_mediascanner.xml
lib/python/Plugins/Extensions/PicturePlayer/meta/plugin_pictureplayer.xml
lib/python/Plugins/Extensions/ProgrammlistenUpdater/history.py
lib/python/Plugins/Extensions/ProgrammlistenUpdater/settinglist.py
lib/python/Plugins/SystemPlugins/CommonInterfaceAssignment/meta/plugin_commoninterfaceassignment.xml
lib/python/Plugins/SystemPlugins/DefaultServicesScanner/meta/plugin_defaultservicesscanner.xml
lib/python/Plugins/SystemPlugins/DiseqcTester/meta/plugin_diseqctester.xml
lib/python/Plugins/SystemPlugins/NFIFlash/downloader.py
lib/python/Plugins/SystemPlugins/NFIFlash/meta/plugin_nfiflash.xml
lib/python/Plugins/SystemPlugins/NetworkWizard/meta/plugin_networkwizard.xml
lib/python/Plugins/SystemPlugins/PositionerSetup/meta/plugin_positionersetup.xml
lib/python/Plugins/SystemPlugins/SatelliteEquipmentControl/meta/plugin_satelliteequipmentcontrol.xml
lib/python/Plugins/SystemPlugins/Satfinder/meta/plugin_satfinder.xml
lib/python/Plugins/SystemPlugins/SoftwareManager/meta/plugin_softwaremanager.xml
lib/python/Plugins/SystemPlugins/VideoEnhancement/meta/plugin_videoenhancement.xml
lib/python/Plugins/SystemPlugins/VideoTune/meta/plugin_videotune.xml
lib/python/Plugins/SystemPlugins/WirelessLan/meta/plugin_wirelesslan.xml
lib/python/Screens/SoftwareUpdate.py

This change transitions code calls to https where possible 
Not part of this change 
- change of google domain for privacy
- po translation file changes
- references to `openvix.co.uk` in `SoftwareUpdate.py`

Transition references to https where possible

---

po/sk.po

Added Slovak translation for new texts since last update. 
**Note for developers:** The strings where source text would be equal to target text were not added to the language file. But maybe it would be better to exclude such texts from PO-file completely (= exclude even source texts if is no translation needed.)

Update of sk.po

---

po/zh_CN.po

Update zh_ CN.po

---

lib/python/Screens/InstallWizard.py

The question relates to which list to install, "scan" is not a channel list
The scanning question is a separate question.

[Install Wizard] Reword sat list options

---

README.md

Update Readme.md (text tweaks)

---

lib/python/Screens/AutoDiseqc.py

Tested with SF8008 and MultyTenne Quattrosat in first run Wizard

Update Astra 28.2E Transponder to CNBC

---

lib/python/Components/Timezones.py

There is a notifier in the plugin to handle timezone changes.
https://github.com/oe-alliance/enigma2-plugins/commit/972ab1e6d13264f1318f34efb191957a49dcc529

[Timezones.py] Remove AutoTimer code

---

po/el.po

Greek translation update 13/3/2021

Greek translation update 13/3/2021

---

lib/python/Screens/EpgSelection.py

This removes an import that's no longer required

Remove usused IMDb import

---

po/en.po

Fix text `Radio button` -> `Radio`; `Name (a-z)` -> `Name`

Fix text `Radio button` -> `Radio`; `Name (a-z)` -> `Name`

---

po/en.po

Fixed typos, grammar

---

lib/python/Screens/NetworkSetup.py

Fix NetworkSetup crash

---

lib/actions/action.cpp
lib/actions/action.h
lib/base/cachedtssource.cpp
lib/base/cfile.cpp
lib/base/cfile.h
lib/base/console.cpp
lib/base/eerror.h
lib/base/eptrlist.h
lib/base/message.h
lib/base/wrappers.cpp
lib/gui/Makefile.inc
lib/gui/einputstring.cpp
lib/gui/elabel.h
lib/gui/epixmap.cpp
lib/gui/ewidget.cpp
lib/gui/ewidgetdesktop.cpp
lib/gui/ewindow.h
lib/gui/ewindowstyle.cpp
lib/mmi/mmi_ui.h

This pull will sync some files of OV and ATV and should not change anything.
* add m_long_key_pressed ivar
* add function parsePts_t
* add eTraceNoNewLineStart and eTraceNoNewLine
* use template class for ePtrList erase
* add getNoWrap to eLabel
* prevent eWidget crashes if root is null
* changes some log outputs

Sync of OV and ATV

---

lib/python/Components/ActionMap.py
lib/python/Components/HelpMenuList.py
lib/python/Tools/KeyBindings.py
lib/python/keymapparser.py

Redesign keymap based on OV
Thanks to @IanSav

Reorg keymap

---

lib/base/encoding.cpp
lib/base/encoding.h
lib/base/estring.cpp
lib/base/estring.h

* add formatNumber, undoAbbreviation, GEOSTD8ToUTF8
* refactor UnicodeToUTF8
* replace EIT CR/LF with standard newline
* fix typo

sync estring from OpenPli

---

lib/python/StartEnigma.py
lib/python/skin.py

* fully sync with OV
* sort class functions
* add new Screen scale feature
* use new fileReadXML
* add AttribDeprecatedError for old skin properties
Thanks to @IanSav

refactor skin.py

---

lib/python/Components/Sources/EventInfo.py

Fix extended description

---

README.md

- Better use of markdown
- Added building of specific packages
- Corrected a couple of typos and expressions

README.md facelift

---

lib/python/Plugins/SystemPlugins/SoftwareManager/BackupRestore.py

local ipk were skipped due to a typo
please also backport to 6.4

fix install of local ipk in BackupRestore

---

lib/gui/elistbox.cpp
lib/gui/elistbox.h
lib/python/enigma_python.i

* use m_scrollbar_offset instead of fixed value of 5
* add new Defaultwidth and Defaultoffset
* introduce setListBoxScrollbarStyle to set the Defaultwidth and Defaultoffset

[eListBox]

---

lib/python/Screens/TagEditor.py

[TagEditor.py] Fix crashes when tag list is empty
[TagEditor.py] Improve clarity of method name

[TagEditor.py] Fix crashes when tag list is empty

---

lib/python/Screens/ButtonSetup.py

This hotkey action enables
* Activate PiP
* Zap PiP
* Deactivate PiP

[Hotkey] Enable PiP cycle without remapping

---

lib/python/Components/Converter/ModuleControl.py

add ModuleControl Converter

---

data/unicable.xml

```http://www.inverto.tv/multiswitch/307/unicable-ii-cascadable-switch-with-terrestrial-input-and-4x-sky-dscr-satcr-legacy-terrestrial-outputs```

Add Inverto ISKY-UST110-CUO4O-16P

---

data/keymap.ntr

Könnt ihr die Neutrinokeymap bitte immer mit nachziehen, so das ich ich mich nicht zwischen den Feiertagen da hinsetzen muss und die für meine Eltern wieder richten muss. Choicebox ging gar nicht mehr. 
Danke

fix keymap.ntr

---

data/setup.xml
lib/python/Screens/HDMICEC.py
lib/python/Screens/PluginBrowser.py

These changes to CamelCase setup.xml key names will feed into cleaner skin customizations of Setup based screens.

Next step of setup.xml clean up

---

data/setup.xml
lib/python/Components/UsageConfig.py
lib/service/servicemp3.cpp
tools/enigma2.sh.in

Thanks to @pike, @betacentauri and @jbleyel

[servicemp3] enable gst debug log and pipeline graph

---

data/menu.xml

- Use uniform self closing tag spacing.
- Tidy up and optimize the embedded Python code.
- Remove magic numbers from TryQuitMainloop arguments.

[menu.xml] A few more clean ups

---

data/setup.xml
lib/python/Screens/NetworkSetup.py

- Make "NeworkPassword" a sub class of "Setup" rather than a copy of "Setup".
- Add a "Password" block to "setup.xml" for the new "NetworkPassword" code.
- Sort and tidy up the imports.  (There is more tidying up to come as the rest of this module is refactored.)

[NetworkSetup.py] Refactor NetworkPassword

---

lib/python/Components/International.py

This code is commented out but has been improved should the functionality ever be enabled.

[International.py] Improve the language default

---

lib/python/Screens/NetworkSetup.py

This change restores the previous, more secure, code but adds some further protections and improvements.
- Force the "passwd" program to run in US English mode so that the prompts can be interpreted by the Python code.
- Add logic to ensure that the interactions with "passwd" are correct and complete.
- Force a timeout if the interactions with "passwd" do not go as expected.
- Correct the analysis of the status code returned from the "execute()" method call.  This status is *NOT* the exit status of the command being run!  This is the status of the attempt to launch the command being run.
- Move the analysis of the exit status of the "passwd" command run to where the exit value is actually presented.
- Add some more logging to show what is going on in the UI.
The issue with the first …

[NetworkSetup.py] Harden NetworkPassword code

---

lib/python/Screens/NetworkSetup.py

This extra code improves the language hack.  It addresses issues in other code that expect the shell to be in the selected locale.
Thanks to @jbleyel for researching the issue.

[NetworkSetup.py] Improve the language hack

---

data/keymap.xml

- Correct the mapping name for the overwrite feature in text editing.
- Add keyboard equivalents for the color buttons.

[keymap.xml] Small correction and enhancements

---

lib/python/StartEnigma.py

- Correct tuple in getBrandOEM() content check on line 410.
- Add "[StartEnigma]" to all logging messages.
- PEP8 correct and improve some comments.
- Use consistent quotation marks.
- Improve indentation of code to enhance readability.

[StartEnigma.py] Start cleaning up the code

---

data/encoding.conf

updated unused and non-essential TP's
add new 42E DigitalPlatfom  ( thanks @tanerkaderli ) 
fixed this issue : https://github.com/openatv/enigma2/issues/1750

[encoding.conf] Updating, cleanup wrong format ..

---

data/encoding.conf

Remove old and inactive transponders in EIT.

[encoding.conf] Digital Platform cleanup

---

data/keymap.xml

Add a few more convenience action maps to allow more flexible action map usage.  Coders can select action maps that are more focussed on their needs.

[keymap.xml] Add convenience action maps

---

data/setup.xml

Thanks to @nautilus7 for the bug report.

[setup.xml] Correct spelling of "conditional"

---

lib/python/Screens/VolumeAdjust.py

- Remove unused imports.
- Add HELP to the service selection screen.
This is a temporary change as it will not be required when the "ChannelSelectionBase" is refactored and help is added to the code functionality.

[VolumeAdjust.py] Small adjustments

---

lib/python/Plugins/Extensions/MediaPlayer/settings.py
lib/python/Plugins/Extensions/MediaPlayer/setup.xml

* Remove setTitle from setup based screen
* Add missing setup item to setup.xml

[MediaPlayer] Fix #2282

---

lib/python/Components/SystemInfo.py
lib/python/Tools/MultiBoot.py

- [SystemInfo.py] Restore DualBoot information
- [MultiBoot.py] Add canDualBoot() method

Restore DualBoot

---

lib/python/Screens/FlashManager.py

[FlashManager] - fix EGAMI Json Lists. add Request for UA

[FlashManager] - fix EGAMI Json Lists. add Request

---

lib/python/Screens/MultiBootManager.py

Thanks to @nautilus7 for the report.

[MultiBootManager.py] Correct grammar

---

lib/python/Components/SystemInfo.py

Thanks to @nautilus7 for the bug report.

[SystemInfo.py] Correct typo

---

lib/python/Screens/ButtonSetup.py
lib/python/Screens/InfoBarGenerics.py
po/enigma2.pot

Add a `Start recording current event` hotkey action (#2313)

Hotkey record event (#2313)

---

lib/python/Screens/FlashManager.py

Maybe OpenDROID will have future 'model' changes
read comments
https://github.com/opendroid-Team/enigma2/commit/a64bd25ccefc3572ab5c08172fe144b7c1373ac4

[FlashManager] - add OpenDROID

---

lib/python/Components/SystemInfo.py
lib/python/Screens/Information.py

[SystemInfo.py] Improve and optimise code
- Remove redundant check of immutable variables.
- Remove separate lookup of override variables.  The override variables will now simply replace the original values.  This should have no operational change except for a performance increase.
- Rename variables that hint at the old kernel module.
[Information.py] Update SystemInfo method call
- This change matches the change in SystemInfo.py.

Improve and optimise SystemInfo code

---

lib/python/Screens/NetworkSetup.py

File "/usr/lib/enigma2/python/Screens/NetworkSetup.py", line 907, in queryWirelessDevice
File "/usr/lib/python3.10/site-packages/wifi/scan.py", line 72, in all
wifi.exceptions.InterfaceError: b"wlan0     Interface doesn't support scanning : Device or resource busy"

[NetworkSetup] try to fix :

---

lib/python/Screens/FlashManager.py

- Further optimise the code.
- Replace ChoiceBox with MessageBox so that the prompt text can be seen in its entirety.
- Don't use a shell to run commands.
- Allow slots with non numeric designations to be overwritten.
- Restore Open Vision access as the source code for that distribution has been reopened.
- Improve text and help messages.
- Optimise sorting.
- Improve variable names to make code more readable.
- Remove "self["list"].l." list references.
- Reduce debug log noise.

[FlashManager.py] Complete previous refactor commit

---

lib/python/skin.py

- Add catcher methods for skinners who use the attributes "hAlign" and "vAlign".
- Add data structures to support setting ScrollLabel() scrollbar defaults.  An updated ScrollLabel.py module will be published soon.
- Update the windowstyles enhancements to match the latest C++ code.  Slider widgets can now also have their default border width set.
- Replace the word "picture" in scrollbar attributes with "pixmap" to be more consistent with naming.  This matches the equivalent changes in the C++ code.
- Update all scrollbar related attributes to use the new C++ methods.  All old names have been retained and redirected to their new equivalents and deprecation warnings are added to the logs.

[skin.py] More updates and enhancements

---

lib/python/Tools/StbHardware.py

Suppress a logged error trying to access a file that does not exist.
The code in this module should be checked and optimised by someone familiar with the drivers and box capabilities.  Consideration should also be given to moving all this code into SystemInfo.

[StbHardware.py] Silence log noise

---

lib/gui/elistboxcontent.cpp
lib/gui/ewindowstyle.h
lib/gui/ewindowstyleskinned.cpp
lib/gui/ewindowstyleskinned.h

* provide setLabelFont and setListboxFont to define the defaults via skin

[windowstyle]

---

lib/python/skin.py

This change adds a default font specifier (font="Regular;20") attribute to the "windowstyle" "listbox" tag".  A new "label" tag has been added to the "windowstyle" to hold a font specifier (font="Regular;20") attribute to set the default font for all eLabel based widgets.

[skin.py] Add styles for default fonts

---

data/keymap.xml
data/menu.xml
lib/python/Screens/ButtonSetup.py
lib/python/Screens/ChannelSelection.py
lib/python/Screens/InfoBar.py
lib/python/Screens/InfoBarGenerics.py
lib/python/Screens/Menu.py
lib/python/StartEnigma.py
lib/python/Tools/Migration.py

This is the next step in optimising and improving the Menu.py code for Enigma2.
[Menu.py]
- Further optimise and clean up the code.  Remove more defunct / unused code.
- Add a new method "findMenu()" to find menu elements within "menu.xml" DOM.  This saves external code knowing about or searching the menu DOM themselves.
- Remove the defunct menu history code.  This functionality is now in Screen.py and supports all screens being opened.
- Cache menu images.
- Restore support for a legacy menu image system using the "mainmenu" skin subdirectory as well as the newer "menus" tag system.
- Add MENU button support within the menu screen to take the user directly to "MENU > Setup > Usage & GUI > OSD Settings" where the menu configuration items can be found.
- Remove alternate menu widgets from …

More Menu.py refactor and matching code changes

---

lib/gdi/grc.cpp

Fix debug message typo

---

lib/python/Tools/Conversions.py

This tool contains classes and methods that can be used by other modules to convert or format data to different layouts.

[Conversions.py] Add new tool for data conversion

---

lib/python/Screens/Information.py

[Information]
* use driversdate from enigma.info
* use formatDate for imagebuild

use driversdate from enigma.info

---

lib/python/Screens/Information.py

The new log file names will be:
YYYYMMDD-HHMMSS-enigma2-crash.log
YYYYMMDD-HHMMSS-enigma2-debug.log

[Information.py] Find new and old log file names

---

lib/python/Screens/LogManager.py
main/bsod.cpp
tools/enigma2.sh.in

YYYYMMDD-HHMMSS-enigma2-crash.log
YYYYMMDD-HHMMSS-enigma2-debug.log

New logfile name format:

---

lib/python/Plugins/SystemPlugins/SoftwareManager/ImageWizard.py

[ImageWizard]

---

lib/python/Screens/Information.py

- Add missing MENU button to embedded skin.
- Remove INFO to display images from base class.
- Add INFO to show Build Information from within DistributionInformation screen.
- Rename "InformationImage" to "ImageInformation" to be consistent with other classes.
- Add INFO button to "ReceiverInformation" to display the available receiver images.

[Information.py] Small updates

---

lib/gui/elistbox.cpp

* update start/end only if scrollbar visible
* fix division by zero on mipsel boxes

[eListbox] improve scrollbar

---

lib/python/Components/Sources/List.py

- Use the new navigation methods in the C++ code.
- Keep the old navigation methods as pointers to the new methods until the clean up is completed.
- Improve some variable names to eliminate PEP8 errors.

[List.py] Small update to code

---

lib/python/Components/ConfigList.py

- Use the new navigation methods in the C++ code.
- Keep the old navigation methods as pointers to the new methods until the clean up is completed.
- Improve some variable names to eliminate PEP8 errors.
- Small code move to make the code more readable.

[ConfigList.py] Small update to code

---

lib/python/timer.py

- Add StateDisabled placeholder
- Sort and optimize imports.
- PEP8 clean up.
- Comment tidy up and spelling corrections.

[timer.py] Add StateDisabled placeholder and clean up

---

lib/python/Components/TimerSanityCheck.py

This change is a code tidy up in preparation for a refactor of this code.
- Most of the changes are to PEP8 clean up the comments.
- Optimize a few if statements.
- Improved debug logging messages.

[TimerSanityCheck.py] Code tidy up

---

lib/python/Components/Converter/ConfigEntryTest.py

- Clean up and sort imports
- Use the new 'silent' option for the "getResolvedKey()" method call to suppress error logs on invalid/missing keys.
- Strip spaces from around the skin based arguments being parsed.
- Improve the logged messages.
- Use consistent quoting.
- Use camelCase on the "argError" variable.

[ConfigEntryTest.py] Code enhancement and clean up

---

lib/python/Components/TimerSanityCheck.py

- If the timer is in the past and has finished don't bother checking it is conflicts.
- More PEP8 fixes.
- Remove some unhelpful comment lines.

[TimerSanityCheck.py] More cleaning and an optimization

---

lib/gui/elistbox.cpp
lib/gui/elistbox.h
lib/python/skin.py

The default value is 0 -> pageSize = no. of items per page/screen.

[eListbox] add pageSize and DefaultPageSize for linemode

---

lib/python/Screens/InfoBarGenerics.py

- Sort and organise all imports.
- Update all references to the old timer code to use the new Timers.py code.

[InfoBarGenerics.py] Correct and clean up imports

---

lib/python/Components/Converter/EventName.py

- Make the style of all global variables consistent.  (Use upper case and "_" to separate words.)
- Optimise string generation.
- Allow CRID results to be stripped if required.
- PEP8 corrections.

[EventName.py] More clean up

---

data/setup.xml
lib/python/Components/VolumeControl.py
lib/python/Screens/Volume.py

- Add option to disable the logarithmic volume control.
- Add an option to vary the time out of the MUTE button image.
- Sort the imports.
- Tidy up the code and PEP8 correct the code.

Tweak the volume controls

---

lib/python/Screens/Timers.py

- This change ensures that the nominated recording target exists and is valid.  Previously a non existent recording location could cause this code to crash.
- The new code also checks to see if the recording is going to be saved on the Flash disk and warns against the location.

[Timers.py] Rework space calculations

---

lib/gui/elistboxcontent.cpp
lib/gui/elistboxcontent.h

* Rename m_font variable because of the same name in parent class.

[eListboxPythonMultiContent]

---

lib/python/Components/config.py

- Optimize the code in the ConfigSelection subclasses.
- Add an option to display unit strings for ConfigSelectionNumber().
- Improve a choicesList() error message.
- Remove an incorrect comment.

[config.py] Optimize and enhance ConfigSelection subclasses

---

lib/python/Components/TuneTest.py

* remove print_function
* rename dict variable
* fix self.checkPids typo

[TuneTest]

---

lib/python/Components/UsageConfig.py

- Optimize translation strings.
- Optimize many choice list generations.
- Tidy up some comments.

[UsageConfig.py] Code clean up

---

lib/python/Plugins/SystemPlugins/SoftwareManager/ImageBackup.py

Create sparse image file with int instead of float

[ImageBackup] Fix #2545

---

lib/python/Components/SystemInfo.py

* add HasSoftcamEmu
* improve softcam checks

[SystemInfo]

---

data/menu.xml

Users can download as well as flash images

[Menu] Reword hint text

---

lib/python/Screens/LocationBox.py

This should resolve a crash recently detected and reported.

[LocationBox.py] Correct errors in sub classes

---

data/menu.xml
data/setup.xml
lib/python/Screens/LocationBox.py
lib/python/Screens/Playback.py
lib/python/Screens/Recording.py

- Add a new "Playback.py" module to support the management of the movie location.
- Add a new "PlaybackLocationBox" sub class to "LocationBox.py".
- Remove the movie location option from the "Recording.py" module.
- Small optimization for the "Timeshift.py" module.
- Update "menu.xml" and "setup.xml" to reflect the change of configuration options.

Update Playback, Recording and Timeshift screens

---

lib/python/Plugins/SystemPlugins/DiseqcTester/plugin.py

Center and move status and result text to bottom of page

[Diseqc tester] Adjust embedded screen

---

lib/python/Components/NimManager.py

[Nimmanager]

---

lib/python/Screens/SkinSelector.py

* Refactor imports
* Cleanup variables
* Fix MetrixHD switch issue

[SkinSelector]

---

lib/python/Components/AVSwitch.py

* fix box model detection
* add missing except error

[AVSwitch]

---

lib/service/servicedvd.cpp
lib/service/servicedvd.h

* Add missing return
* Use C++11 struct initialize
* use nullptr instead of 0
* use PyLong_FromLong instead of PyInt_FromLong

[servicedvd]

---

lib/python/Components/Sources/List.py

Add "getCurrentIndex()" and "setCurrentIndex()" methods to be more compatible with other lists like ConfigList, EpgList, MovieList, ServiceList, etc.

[List.py] Add new methods

---

lib/python/Components/MenuList.py

Add "getCurrentIndex()" and "setCurrentIndex()" methods to be more compatible with other lists like ConfigList, EpgList, MovieList, ServiceList, etc.

[MenuList.py] Add new methods

---

lib/python/Components/MenuList.py

This also corrects the SONAR bug and code smell.

[MenuList.py] Correct typo

---

lib/python/Components/FileList.py

- Add a new calling argument "showCurrentDirectory" to cause an extra line to be included in the directory list.  This new line offers a link/value of the current directory.  This will be used in an improved LocationBox that is soon to be committed.
- Optimise some of the code structures.
- Use "sep" instead of "'/'".
- PEP8 clean up the code.  Use proper variable names, clean up comments.

[FileList.py] Tidy up and optimise the code

---

lib/python/PowerTimer.py
lib/python/Screens/ChannelSelection.py
lib/python/Screens/EpgSelection.py
lib/python/Screens/EventView.py
lib/python/Screens/InfoBarGenerics.py
lib/python/Screens/Timers.py
lib/python/StartEnigma.py

[Timer/Powertimer]

---

lib/python/Screens/LocationBox.py

- Add an embedded screen to rescue old skins.
- The unused "userMode" argument has been removed.
- The action map usage has been corrected.
- Enhance the features offered by the context menu.
- Replace InputBox by VirtualKeyBoard.
- Rename skin widgets to be more logical.
- Improve the usability of the user interface.  For example, you no longer need to enter a directory in order to select it or add it as a bookmark.
- No longer always sort bookmarks but add a context menu item to sort the bookmarks.
- Allow the order of the bookmarks to be changed.
- Add new bookmarks to the start of the bookmark list.
- The rename proposed file name option now only allows the basename and *not* the extension to be renamed.
- Add comprehensive help.  Note that the help text is dynamic and will change to …

[LocationBox.py] Refactor the code

---

lib/python/Components/ScrollLabel.py

This change adds the new consistent navigation methods to ScrollLabels.  The new names are shared with MenuList and List widgets and will be progressivly added to all widgets that accept navigation.  The standard methods are goTop(), goPageUp(), goLineUp(), goLineDown(), goPageDown(), goBottom().

[ScrollLabel.py] Add consistent navigation methods

---

lib/python/Components/Converter/EventName.py

- Correct country "INT" to "ETSI" to match the UsageConfig.py definition.
- Upper case COUNTRIES dictionary variable as it is global.
- Add "ShortDescription" skin option to match other images.

[EventName.py] Small corrections and updates

---

lib/python/Plugins/SystemPlugins/SoftwareManager/plugin.py

* Call opkg update before installing ipk to prevent dependency errors.
* Improve configuration backup location selection.
* cleanup imports
* use pathjoin instead of + "/"
* use with for open files

[SoftwareManager]

---

lib/python/Screens/TaskList.py

- Optimize the code.
- Improve the embedded screen.
- Add help.
- Sort and clean up the imports.
- Improve the screen name but keep a legacy entry point for backward compatibility.
- PEP8 clean up.

[TaskList.py] Refactor and improve the code

---

lib/python/Screens/TaskView.py

- Optimize the code and screen updates.
- Fix the issue of the task status not updating if task notifications are used (like in FileCommander, etc).
- Remove obsolete and inappropriate widgets and replace them with more contemporary button controls.
- Properly interface with the ConfigList controls.
- Add an embedded screen.
- Add help.
- Sort and clean up the imports.
- Improve the screen name but keep a legacy entry point for backward compatibility.
- PEP8 clean up.

[TaskView.py] Refactor and improve the code

---

lib/base/console.cpp
lib/base/console.h
lib/base/ioprio.cpp
lib/base/ioprio.h
lib/python/python_console.i

[eConsoleAppContainer]
* add setNice and setIONice

eAppconsoleContainer / nice

---

lib/python/Components/SystemInfo.py
lib/python/Tools/MultiBoot.py

[SystemInfo.py]
- Allow for positive integers to be accepted.
- Also add brackets for code readability.
[MultiBoot.py]
- Allow for positive integers to be accepted.
- Also add brackets for code readability.
The brackets for the quotation marks line was suggested by Huevos.

Allow for positive integers to be accepted

---

lib/python/Plugins/SystemPlugins/SoftwareManager/BackupRestore.py

* add /etc/hosts and /etc/enigma2/volume.xml to the default file list
* small improvements

[BackupRestore]

---

lib/python/Screens/InfoBarGenerics.py

Fix that a renamed service couldn't have a subservice

Make subservices comparable

---

lib/python/Screens/SubservicesQuickzap.py

Fix that a renamed service get a SubserviceIndex

Make subservices comparable #2

---

lib/python/Screens/SubservicesQuickzap.py

Do not check for last but for current subservice.

Fix Fix SubservicesQuickzap Selected

---

data/setup.xml
lib/base/estring.cpp
lib/base/estring.h
lib/python/Components/UsageConfig.py
lib/service/event.cpp
lib/service/event.h

* add fixUTF8 for getShortDescription and getExtendedDescription
* remove fixUTF8 from convertDVBUTF8
* add setting to enable the this fix

[eServiceEvent]

---

lib/python/Components/config.py

Add information about the new TranslationHelper.py file to give coders a place to add any required translations that don't appear elsewhere.

[config.py] Update ConfigSelectionNumber comment

---

po/el.po

Greek translation update 28/11/2022

Greek translation update 28/11/2022

---

po/el.po

Reverted as PO file is broken.  Requested by @jbleyel who is unavailable at the moment.

Revert "Greek translation update 28/11/2022"

---

lib/python/Plugins/Extensions/FileCommander/plugin.py

- Make some text changes to improve translation.
- Camel case one of the new variables.
Text changes requested by @jbleyel.

[FileCommander]

---

lib/actions/Makefile.inc
lib/gui/Makefile.inc
lib/python/enigma_python.i

* remove einput, einputnumber and einputstring from build
* remove InputAction from native action bindings

remove einput*

---

lib/python/Plugins/Extensions/FileCommander/plugin.py

Fix line selection for move and delete
ReAdd open ViewEdit by startTeletext

[FileCommander] improvments 

---

lib/python/Plugins/Extensions/FileCommander/plugin.py

[FileCommander] copyMove Buttons

---

lib/python/Plugins/Plugin.py
lib/python/Screens/ButtonSetup.py

* allow plugin to assign to hotkey only
#2648

[ButtonSetup]

---

lib/python/Tools/MultiBoot.py

This change addresses a potential crash issue on private builds of OpenViX.
Issue reported by Huevos.

[MultiBoot.py] Address possible crash

---

lib/python/Components/FileList.py

- Fix crash in "fileListComponent()" when path is None.  Use generic file icon in this case.
- Improve the test for the no mounts / files found message.
- Remove some old debug and code comments.

[FileList.py] Crash fix and clean up

---

lib/python/Plugins/Extensions/FileCommander/plugin.py

Add template options to better explain the current and parent directory entries in the file list:
- Template option 24 shows the current directory at all times.  This means that the skinner can now choose to not use the path, option 17, but rather use option 24 to show the current directory and option 19 to show the current item.  This addresses some user concerns that for some items in the file list the current directory is not obviously available.
- Template option 25 is similar to the previous change but retails the full path display for all normal items in the file list but shows the current directory and the parent directory when the cursor is on a "<Current Directory>" or "<Parent Directory>" entry.
Also add a message to show that a package installation process has completed.  The …

[FileCommander] Add some visual updates

---

data/setup.xml
lib/python/Components/ActionMap.py
lib/python/Components/UsageConfig.py

- Allow the legacy navigation code enhancement to work on all action maps.
- Change the config entry from "config.usage." to "config.misc." to allow the variable to be used earlier in the start up of Enigma2.
- Improve the logging comments.
- Add further code improvements from @jbleyel.

[ActionMap.py] Improve legacy navigation code

---

lib/python/Screens/HelpMenu.py

This is another part of making the remote control naming more consistent.

[HelpMenu.py] Update button name label

---

lib/python/Plugins/Extensions/FileCommander/plugin.py

Please reopen FileCommanderUpdates
[I have this in queue... you can have a look at it](https://github.com/geeeeeeeeeee/enigma2/tree/geeeeeeeeeee-traditional-key-assignment)

[FileCommander] fix and some code changes

---

lib/python/Screens/SoftcamSetup.py
lib/python/Tools/camcontrol.py

* Add 3rd party softcam support.
* Set selected softcam to None if the link target no longer exists.
Close #2705

[SoftcamSetup]

---

lib/python/Plugins/Extensions/FileCommander/plugin.py

This improves the setCurrentIndex experience.

[FileCommander] multiselect with related files

---

lib/python/Components/FileList.py

- Rename the "selectedFiles" variable to "selectedItems".  This better describes the contents of the variable as it may contain directories as well as files.  It also matches the name used in the FileCommander plugin.
- Rename the "getSelectedList()" method to "getSelectedItems()" to match the previous point.  The old name is retained for code that has not yet been updated.
- Improve and optimise the selection code.
- Add new options to set, clear or toggle all the items in the file list.

[FileList.py] More code improvements

---

lib/python/Plugins/Extensions/FileCommander/plugin.py

- Update the FileList component method name "getSelectedList()" to the new "getSelectedItems()".
- Use the new FileList method "clearAllSelections()" rather than "clearSelection()" to correctly remove the selection marker from all files after an action is performed on the selection.
Please merge Pull Request #2739 before processing this pull request.

[FileCommander] Small correction and enhancement

---

lib/python/Components/UsageConfig.py

This fixes Issue #2446.
The default directories for movie and time shift only created if the user specified directories do not exist and fail to be created.

[UsageConfig] Enhance creation of movie and time shift directories

---

data/menu.xml
data/setup.xml
lib/python/Components/Opkg.py
lib/python/Components/PluginList.py
lib/python/Screens/PluginBrowser.py

[PluginManager]
* replace PluginManager with PluginDownloadManager in menu
[PluginDownloadManager]
* add manage option to allow delete and install in one screen
* remove locale packages support
[Opkg]
* add info call
* add info parser
[Setup.xml]
* remove language filter setting for PluginDownloads

[PluginManager]

---

lib/python/RecordTimer.py
lib/python/Screens/ChannelSelection.py

* refactor zap timer channel selection

[RecordTimer]

---

lib/python/Components/PluginList.py
lib/python/Screens/PluginBrowser.py

* cleanup imports
[PluginBrowser]
* improve package filter
* use double quotes

[PluginList]

---

lib/python/Plugins/Extensions/FileCommander/keymap.xml
lib/python/Plugins/Extensions/FileCommander/plugin.py

- Correct issue with action map buttons being unavailable.  (Use enableAutoNavigation(False).)
- Optimize and improve heading sort calculations.
- Correct keyRename() for directories.
- Update the headings when the sort orders are changed.
- Expand the capabilities of the text editor:
- Sequence the code methods alphabetically.
- Rename the "updateLine()" method to "updateStatus()" to better reflect what the method does.
- Add command to duplicate the current line.
- Add a command to delete all empty and white space only lines.
- Add a command to remove all duplicated lines in the file.
- Add a command menu to sort all the lines in the file.  The options are to sort the lines in ascending and descending order.
[keymap.xml] Add new button options to change panels

[FileCommander] More refinements

---

lib/python/skin.py

[Skin.py] Another legacy resolution fix

---

data/unicable.xml

The "hello" family name is correct and works. Some people like to have the exact model name.

Unicable- GT Sat

---

lib/python/Screens/InfoBarGenerics.py

Scrolling in SecondInfoBar screen

---

lib/dvb/dvbtime.cpp
lib/dvb/dvbtime.h

* add new setDVBTimeMode function

[eDVBLocalTimeHandler]

---

lib/python/Components/Converter/ServiceInfo.py

Tweak dimensions
https://github.com/openatv/enigma2/issues/1089

Service info

---

lib/python/Components/Converter/pstrCnvrt.py

[Converter/pstrCnvrt]

---

lib/python/Screens/FlashManager.py

- Add delete confirmation pop up contributed by @m4dhouse .
- Sort and optimize imports.
- Small optimizations to the code.
- Improve callback method names and scope.
- Use updated list navigation controls.

[FlashManager.py] Bring code up to latest standards

---

lib/python/Components/MovieList.py
lib/python/Screens/InfoBar.py
lib/python/Screens/MovieSelection.py
lib/python/StartEnigma.py
lib/python/Tools/Trashcan.py

[Trashcan]

---

lib/python/Components/FileList.py

This change renames the name of the parent icon in the file list from "back.png" to a more obvious "parent.png".

[FileList.py] Improve parent name icon label

---

lib/python/Components/FileList.py

- Two calls to fileListComponent() method were not updated.
- Make the new icon variables more self explanatory.

[FileList.py] Fix and improve previous commit

---

data/unicable.xml

Digital CSS 24CH LNBF.  AKU0-U05-M103
https://www.mtigroup.com/upload/media/products/03_Satellite-TV-Solution/MTI_dCSS_24UB_LNB_AKU0_U05_M103_Spec.pdf

Add Microelectronics LNB

---

lib/python/Components/Console.py

- Remove six import.
- Add some debugging for "waitpid()" call.
- Optimize code.
- Correct some comments.

[Console.py] Small code clean up

---

lib/python/Tools/MultiBoot.py

- Optimize the imports.
- Optimize the code.
- Protect processing of the dual boot file.
- Reuse a single "Console()" class invocation.
- Correct some debug logging method names.
- Improve some variable names to reinforce their scope.

[MultiBoot.py] Small code clean up

---

lib/python/Components/Network.py

* Removed six
* Added to blacklist Wg0 (Wireguard interface)

[Components/Network]

---

lib/python/Components/Sources/List.py

This change adds a "getList()" method as a symmetrical partner method to the existing "setList()" method.  This new method does not change or affect the existing "list" property.

[List.py] Add a new getList() method

---

lib/python/StartEnigma.py

The value of the "parentalControl" import was not being updated.

[StartEnigma.py] Correct last commit

---

lib/python/Screens/ChannelSelection.py

These changes have been made to clean up the code in preparation of fixes and code enhancements.  There are no intentional functionality changes.
- Sort and optimise the imports.
- Improve indentation and code layout.
- Fix and improve logging.
- Correct and improve many comments.
- Use consistent quotation marks.

[ChannelSelection.py] Clean up code

---

lib/python/Components/ChoiceList.py

This optimization was suggested by @wedebe.

[ChoiceList.py] Optimise image selection code

---

data/display128/skin_display.xml
data/display128dm/skin_display.xml
data/display128dm/skin_display_picon.xml
data/display220/skin_display.xml
data/display220/skin_display_picon.xml
data/display240/skin_display.xml
data/display240/skin_display_picon.xml
data/display390/skin_display.xml
data/display390/skin_display_picon.xml
data/display400/skin_display.xml
data/display400/skin_display_picon.xml
data/display480/skin_display.xml
data/display480/skin_display_picon.xml
data/display720/skin_display.xml
data/display720/skin_display_picon.xml
data/display96/skin_display.xml
data/displaytext/skin_display.xml
data/displaytext/skin_display_alternate.xml
data/skin_text_clock.xml
data/vfd128/skin_display.xml
data/vfd140/skin_display.xml
data/vfd255/skin_display.xml
data/vfd255/skin_display_picon.xml
data/videowizard.xml
lib/python/Screens/VideoWizard.py

* remove VideoWizardSummary
* small cleanups

[VideoWizard]

---

lib/python/Plugins/newplugin.py

- Optimize the imports.
- Optimize the processing.
- Improve the UI.
- Add options to exit the code gracefully.
- Generate PEP8 complaint code.
- Ignore CR-LF based newlines in source files and generate clean UNIX formatted files.

[newplugin.py] Refactor code

---

lib/python/Components/ConfigList.py
lib/python/Components/MenuList.py
lib/python/Components/Sources/List.py
lib/python/Plugins/Extensions/FileCommander/plugin.py
lib/python/Plugins/SystemPlugins/SoftwareManager/ImageBackup.py
lib/python/Screens/ChannelSelection.py
lib/python/Screens/LocationBox.py
lib/python/Screens/MessageBox.py
lib/python/Screens/MultiBootManager.py
lib/python/Screens/SoftwareUpdate.py
lib/python/Screens/TaskList.py
lib/python/Screens/TaskView.py
lib/python/Screens/Timers.py
lib/python/Screens/VirtualKeyBoard.py

[MenuList.py]
* add enableAutoNavigation
[ConfigList.py]
* add enableAutoNavigation
[TimerListBase.py]
* add enableAutoNavigation
This commit makes the enableAutoNavigation call consistent.

enableAutoNavigation

---

lib/dvb/frontend.cpp
lib/dvb/frontend.h

* replace eDebugDeliverySystem with eTrace

[frontend]

---

lib/python/Components/PluginList.py

- Use consistent quotation marks.
- Don't use "list" as a variable name.

[PluginList.py] Code clean up

---

lib/python/Screens/MultiBootManager.py

The action map description should match / relate to the title description.

[MultiBootManager.py] Match description

---

lib/python/Components/PluginComponent.py

- Add a property and method to access the warning list.  Using a method is preferred for accessing a variable within this class.
- Add the preferred class instantiation variable which is usually the class name with the first letter as lower case.  The old name is still available until all code is updated to use the new name.

[PluginComponent.py] Small improvements

---

lib/python/Components/StackTrace.py

- Sort and optimize imports.
- Improve logging messages.

[StackTrace.py] Small code clean up

---

lib/dvb/fcc.h
lib/nav/core.cpp
lib/nav/core.h

[eNavigation]

---

lib/gui/erectangle.cpp
lib/gui/erectangle.h
lib/gui/ewidget.cpp
lib/gui/ewidget.h
lib/python/skin.py

* remove setBackgroundGradient
[eWidget]
* add setBackgroundGradient to eWidget
[Skin]
* fix parseGradient
* fix backgroundGradient attribute names

[eRectangle]

---

data/menu.xml
data/setup.xml
lib/python/Components/Opkg.py
lib/python/Screens/PluginBrowser.py
lib/python/Screens/QuickMenu.py

[PluginBrowser.py] Complete rewrite and refactor
- This code has been completely rewritten.
- Imports have been optimized and sorted.
- All plugin filters are now integrated into the base code and new filters have been added.
- The PluginBrowser and new PluginAction screens are fully skinable.
- There are now two UI designs, the original list design and a new grid design.
- An embedded fallback skin has now been added.
- The action maps have been enhanced.  Buttons are no longer enabled if they are not functional.
- QuickSelect has been added to allow fast finding of plugins in PluginBrowser and PluginAction screens.
- PluginAction screen allows LEFT / RIGHT buttons to jump directly to previous / next category heading.
- Use new methods in Opkg.py to simplify and speed up interacting with …

[PluginBrowser/Opkg] Complete rewrite and refactor

---

lib/python/Screens/PluginBrowser.py

- Use correct method name in keyMenu() callback.
- Add a log message for an unhandled event.

[PluginBrowser.py] Fix SONAR issues

---

lib/python/Components/FileList.py

This change reflects recent changes made in commit https://github.com/openatv/enigma2/commit/d95336b142fc0a07fe59f5e557b8fd9c47d5ecb7.

[FileList.py] Update extension lists

---

lib/python/Screens/LocaleSelection.py

* add restart question after language change.

[LocaleSelection]

---

lib/driver/avcontrol.cpp
lib/driver/avcontrol.h
lib/python/Components/AVSwitch.py
lib/python/Screens/InfoBarGenerics.py
lib/python/Screens/VideoMode.py

* Implement SetMovieAR plugin features directly

[SetMovieAR]

---

lib/python/Screens/FactoryReset.py

- Optimize code logic.
- Correct failure logging for fileWriteLine() method.
This commit is dedicated to my late step-mother who passed last week.

[FactoryReset.py] Apply code optimizations

---

lib/python/RecordTimer.py
lib/python/Screens/Timers.py

[RecordTimer]
* write and read failed state
* remove state from xml because it's no longer needed
[RecordTimerOverview]
* show failed icon for failed timers
Close #2853

Show Failed info in RecordTimerOverview

---

lib/python/Screens/MovieSelection.py

[MovieSelection]
* tiny code changes
* remove print_function
* use proper exceptions

[MovieSelection]

---

lib/python/Screens/ChannelSelection.py

[ChannelSelection]
* fix radio/tv switch
#2999

[ChannelSelection]

---

data/setup.xml
lib/python/Components/UsageConfig.py
lib/python/Screens/InfoBarGenerics.py

[InfoBarGenerics]
* show subservice channels and indicator also if no epg data available
This needs to be finalized by adding of an additional setting.

[InfoBarGenerics]

---

lib/python/Screens/Ci.py
lib/python/Screens/Setup.py

* improve createSetup
[Setup]
* createSetup add parameter for append and prepend items

[CiSelection]

---

lib/python/Components/Lcd.py

* move exception handling into the thread function
* remove duplicate timer start
#3018

[LCD/IconCheckPoller]

---

doc/DOCUMENTATION

This is a proposed style guide for people to use to improve any text used within Enigma2 and/or plugins.

[DOCUMENTATION] Add a text/documentation style guide

---

lib/python/skin.py

- Replace "%s" substitutions with f"" formatting to improve performance of the code.
- Use better variable names for single letter variables as per PEP8 recommendations.
- Sort and clean up skin attribute methods.
- Other small code optimizations.

[skin.py] Optimize code and improve variables

---

lib/gui/elabel.cpp
lib/gui/elabel.h
lib/gui/elistbox.cpp
lib/gui/elistbox.h
lib/gui/eslider.cpp
lib/gui/eslider.h
lib/gui/ewidget.cpp
lib/gui/ewidget.h
lib/python/Components/ScrollLabel.py
lib/python/skin.py

[eLabel]
* add setAlphatest to allow alphablend for eLabel

Graphic updates

---

lib/python/skin.py

In the variable name update I made a mistake with one of the substitutions.  The error was corrected but unfortunately the correction was also incorrect.  Hopefully this change is now correct.  :)

[skin.py] Correct a corrected variable name

---

lib/python/Plugins/Extensions/PicturePlayer/ui.py

This pull request builds on Pull Request #3088 that does not fix all the division errors.  (That commit fixed the vertical alignment errors but did not correct the horizontal errors.)

[ui.py] Complete the Python 3 floor division corrections

---

lib/service/elistboxservicecontent.cpp
lib/service/listboxservice.cpp

https://github.com/OpenViX/enigma2/commit/41320646128af00497778a216f39dcd57074bf88

Cherry pick

---

lib/python/Components/Converter/PliExtraInfo.py

* add color parameter support
* remove many copy paste code
* use more f-strings

[PliExtraInfo]

---

lib/python/Screens/Information.py

- This change improves the parsing of the "df" output used in the StorageInformation screen.
- This change also allows for the correct processing of the "df" output if spaces  are used in the device and/or mount point fields.

[Information.py] Improve parsing of "df" output

---

lib/python/Screens/InfoBarGenerics.py

fix #3130
fix #2800 completely

[InstantRecord] fixes

---

lib/python/Screens/PluginBrowser.py

After investigating the cause of the recent crash it was decided to further refactor and optimise the code.  This change removes the cause of the crash (which was caused by trying to manipulate a variable from the parent method) and further streamlines the code.

[PluginBrowser.py] Small corrections and optimizations

---

lib/python/Screens/InstallWizard.py

- Use the Python tar library rather than forking a shell to run tar.
- Use the new Opkg.py library.
- Fix and improve variable names.
- Add help text to the screen.
- Clean up and optimize the code.
- Use match rather than if/elif/else blocks.
- PEP8 clean the code.

[InstallWizard.py] Refactor code

---

lib/python/Components/Element.py

This is a small tidy up and code rearrange to match the current coding styles.

[Element.py] Tidy up code

---

configure.ac
lib/driver/rcinput.cpp
lib/python/Components/ActionMap.py
lib/python/Components/UsageConfig.py
lib/python/StartEnigma.py

* remove usage of keytranslation.xml
* add remapping of keytranslation.xml into rcinput

[keytranslation]

---

lib/python/Components/SystemInfo.py

Remove an unused condition in "processValue()".

[SystemInfo.py] Small code optimization

---

lib/python/Screens/ChannelSelection.py
lib/python/Screens/ChoiceBox.py
lib/python/Screens/EpgSelection.py

[ChoiceBox.py] Refactor code
- Refactor the ChoiceBox screen as ChoiceBoxNew and provide an interface class called ChoiceBox to handle the command line argument changes.
- Add HELP button functionality.
- Change the action maps to show the invalid button pop up if any of the accelerator buttons are unassigned.
- Add a ChoiceBoxSummary class to create a more usual summary screen.
- Simplify many areas of the code.
- Remove reserved word variable names.
- Use more meaningful variable names.
- Use the all the standard navigation buttons.
- Use the latest navigation methods directly.
- Sort the imports.
- Remove the "autoResize()" method logic as resizing is very skin dependent.
[ChannelSelection.py] Use refactored ChoiceBox screen
- Update the interface arguments to use the …

[ChoiceBox.py] Refactor code

---

lib/python/Screens/MovieSelection.py
lib/python/Screens/VirtualKeyBoard.py
lib/python/Tools/NumericalTextInput.py
lib/python/TranslationHelper.py

[NumericalTextInput.py] Optimize code
- Move global space variables into the class variable space.
- Ensure that the "nextFunc" argument is a callable method.
- Add a method to stop the internal timer.  This eliminates a crash if NumericalTextInput is exited before the timer fires when the internal timer is active.
- User f-strings
[MovieSelection.py] Update the NumericalTextInput import

[NumericalTextInput.py] Optimize code

---

lib/python/Screens/ChoiceBox.py

- Correct the logic of the ChoiceBox interface class to correctly and better match the legacy arguments.
- Add some debugging code for issue #3233 and a possible solution.

[ChoiceBox.py] Correct interface code

---

lib/python/Components/ConfigList.py

- Reduce the scope of some callback code.
- Update the calling arguments for the ChoiceBox call.

[ConfigList.py] Small code improvements

---

data/setup.xml
lib/python/Components/UsageConfig.py
lib/python/Screens/ChannelSelection.py

* add setting to change the sort order of the channels

[HistoryZapSelector]

---

lib/python/Screens/OScamInfo.py

- bugfix: no more crahses when special characers occure in log (log is 'latin-1' coded, not 'utf-8')
- improvement: better division of the columns in the lower status bar

[OSCamInfo] bugfix and skin improvements

---

lib/python/Screens/OScamInfo.py

- larger font for better readability
- new screens for the Entitlements:
* physical and virtual readers (on server)
* virtual readers (on client) incl. their own details screen
* cards
- some code improvements (special thanks to **@jbleyel**)

[OSCamInfo] Screens for Entitlements added

---

lib/gui/elistboxcontent.cpp

[eListboxContent]

---

lib/python/Screens/NetworkSetup.py

* use the correct configuration file for miniDLNA

[NetworkSetup] Use the correct configuration file for miniDLNA

---

lib/python/Screens/LocationBox.py

Try to keep one exit point per method.

[LocationBox.py] Small code adjustment

---

lib/python/Components/Converter/ConditionalShowHide.py

- Improve some variable names.
- Align the token parser to be comparable to the other converter refactors.  It is too simple to use the same coding style.

[ConditionalShowHide.py] Refactor code

---

lib/python/Components/GUIComponent.py

- Don't import all of skin.py, just the method used here.
- Use True/False instead of 1/0.
- Use more meaningful variable names (avoid single letter variables).
- Optimise some of the logic.
- Remove the specific skin hack as it was non-functional anyway.
- Improve some comment text.

[GUIComponent.py] Small code cleanup

---

lib/python/Components/Converter/RemainingToText.py

- The new code has been streamlined and optimized for improved performance and code readability.
- The tokens have been sorted to make finding things easier.

[RemainingToText.py] Refactor code

---

lib/python/Components/ScrollLabel.py

- Correct the background of the eSlider.
- Correct the calculations of the number of lines with and without the scrollbar.  This corrects some reported positioning errors.
- Small code clean up and optimisation.

[ScrollLabel.py] Correct visual anomalies

---

lib/python/Components/ScrollLabel.py

- Correct a crash issue with screens that use the noWrap attribute.
- More code optimisation.
- Improve variable name to properly represent its function.

[ScrollLabel.py] Small corrections

---

lib/python/Navigation.py
lib/python/NavigationInstance.py

- Use fileWriteLine().
- Correct debug text.
- Improve logging text.
- Improve comments.

[Navigation.py] Cosmetic clean up

---

lib/service/iservice.h
lib/service/servicedvb.cpp
lib/service/servicehdmi.cpp
lib/service/servicehdmi.h
lib/service/servicemp3.cpp

[eServiceHDMI]
* add sVideoInfo, add fake video info
[eServicemp3]
* add sVideoInfo
[eServicedvb]
* add sVideoInfo

Improve video info

---

lib/python/Screens/SoftwareUpdate.py

- Resolve an issue where the update would not complete if there was a minor, and potentially ignorable, update error.
- Refactor the embedded screen to current standards.  This includes using the new XML templates.
- Add a new option to display the new version number in the UI list of updates.
- Optimize the action maps and navigation code.
- Update some text to current text standards.
- Tidy up and improve some of the code layout to match current coding standards.

[SoftwareUpdate.py] Code updates and a fix

---

data/menu.xml
lib/python/Screens/ImageBackup.py

- Completely refactor the code.
- Now completes the while process using a single shell script.
- Improve the logging output.
- Update the embedded screen.
- Keep the old backup code in the menu to allow users to try the new version and fall back to the old code if they experience any issues.  Please report any issues with the new code.
- Eliminate lots of dead or pointless code.
Co-developed with @atvcaptain and @jbleyel.

[ImageBackup.py] Refactor and relocate the image backup code

---

data/setup.xml
lib/gdi/grc.cpp
lib/gdi/grc.h
lib/gui/ewidgetdesktop.cpp
lib/python/Components/UsageConfig.py
main/enigma.cpp

- use ConfigSequence for spinner position
- add spinner position scale

Spinner Position config

---

lib/base/Makefile.inc
lib/base/esubtitlesettings.cpp
lib/base/esubtitlesettings.h
lib/dvb/subtitle.cpp
lib/gui/esubtitle.cpp
lib/python/Components/UsageConfig.py
lib/python/enigma_python.i
lib/service/servicedvb.cpp
lib/service/servicemp3.cpp

[eSubtitleWidget]
- remove eConfigManager and use new eSubtitleSettings
[eDVBSubtitleParser]
- remove eConfigManager and use new eSubtitleSettings
[eDVBServicePlay]
- use new eSubtitleSettings
[UsageConfig]
- add notifier for eSubtitleSettings config settings and use the new functions of eSubtitleSettings
[eSubtitleSettings]
- new class for static subtitle settings

Subtitle Settings

---

lib/python/Screens/QuickMenu.py

- Covert to f-strings
- Remove import *
- Replace most of the Screen imports using new openScreen function
- Add number key selection
- Enable help
- Refactor Actionmap
- Remove QuickMenuDevices Screen
Co-authored-by: @IanSav

[QuickMenu]

---

lib/python/Screens/Console.py

- Simplify and reorganize the code.
- Move the "Save Log" to the YELLOW button.
- Improve the layout and content of the log data.
- Complete the set of vertical navigation options.
- Move the command line and command script logging to the place just before they are used. This makes reading the log file easier.
- Add skin option "commandColor" to color the command line log message in the on-screen log.
- Add skin option "scriptColor" to color the command script file log message in the on-screen log.
- Add a subclass of "ScrollLabel" to extract the new color attributes from the skin widget.
- Strip the color data from the saved log file.
- Use fileReadLines() and fileWriteLines() rather than doing all the processing of the files here.
- Remove the "Load Log" option as the on-screen and …

[Console.py] Refactor the screen

---

lib/python/Components/SystemInfo.py
lib/python/Components/VfdSymbols.py
lib/python/StartEnigma.py

* Use new getVFDSymbolsPoll
* Use fileWriteLine
* Reorg and rename functions to camelcase.
* Remove/cleanup unused variables.
* Sort and cleanup imports.
* Use match/case
* Refactor functions to be more readable
[SystemInfo]
* Remove VFDSymbolsPoll and VFDSymbols
[StartEnigma]
* Use new getVFDSymbolsPoll
Co-authored-by: @IanSav

[VfdSymbols]

---

lib/python/Tools/MultiBoot.py

- Use f-string
- Fix struct error
- Fix bootloop if boot partition is not on device sda ( #3361 )

[MultiBoot]

---

lib/python/Components/Converter/ServiceInfo.py

- Remove the unnecessary polling code.
- Remove the defunct HDMI-In code.  The C++ code now handles HDMI-In.
- Sort token values.
- Sort token code.
- Replace log if / elif / else with match / case.
- Use camelCase variables.
- Prepare to add more information items.
- Use new iServiceInformation.sVideoInfo() call to optimize access to the video information.
- Remove unused and commented out code.
This is an initial commit.  There will be more changes and enhancements to this code.

[ServiceInfo.py] Refactor code and prepare for enhancements

---

lib/python/Tools/MultiBoot.py

- Use Python 3.12 syntax for f-strings.
- Rename variable "imgversion" to "version" to avoid confusion with the "imgversion" BoxInfo variable.

[MultiBoot.py] Update coding style

---

lib/python/Components/Converter/ServiceName2.py

- Change the evaluation of the NUMBER value to use the new LCN values when requested.
- Use uniform quoting.
- Use match statement instead of long if / elsif blocks.
- PEP8 corrections:
- Correct comment indenting.
- Complete exceptions.

[ServiceName2.py] Clean up and improve the code

---

lib/python/Components/ServiceList.py
lib/python/Components/Sources/CurrentService.py
lib/python/Components/Sources/ServiceEvent.py
lib/python/Navigation.py
lib/python/Screens/ChannelSelection.py

[ChannelSelection]
* refactor ActionMap including help
* rename RdsActions
* remove access to self.servicelist.l
[ServiceList]
* add fillFinished, sort and isVertical to support new ChannelSelection navigation
Co-Authored-by: IanSav

ChannelSelection Navigation

---

data/menu.xml

These menu label changes better match the content of the menu.

[menu.xml] Update some menu labels

---

data/unicable.xml

Added Inverto Multiswitch  IDLU-UST110-CU080-32P a.k.a. Item 5458.

Update unicable.xml Added Inverto Multiswitch

---

lib/python/Screens/Volume.py

- Optimise the code using current standards.

[Volume.py] Update code

---

lib/python/Screens/ServiceScan.py

- Remove the need for the ServiceScan component.
- Remove the need for the FIFOList class.
- The scanStatusChanged method from the component is now internal, improved and optimized.
- The scanning process is optimized.
- The LCNScanner is now run after the scan and not when the screen is exited.  (A status pop up appears when the LCNScanner is running.)
- The list of found services is now better managed so that the entire list of services is kept in the screen widget so that a scrollbar is now displayed, when required, and offers the user more feedback on the progress of the scan.
- The summary screen is now a ScreenSummary sub-class.
- Sort and optimize the imports.
- Correct and improve the color buttons.
- Add button help.
- Use consistent quoting.
- Make the code …

[ServiceScan.py] Refactor code

---

lib/python/Tools/Directories.py

- Add a new scope called SCOPE_HARDWARE for the new remote control code changes and a place to store hardware related items.
- Replace "pathjoin" with "join".
- Add a note about future changes being planned.

[Directories.py] Add new SCOPE_HARDWARE and code update

---

lib/python/Components/InputDevice.py
lib/python/Screens/HelpMenu.py

- Move class methods used my one method into that method.
- Remove reserved word variable names.
- Optimize some of the code.
- Make variable names more meaningful.
- Add getRemoteControlPixmap method to InputDevice.py.  This method allows the new HelpMeny.py code to be committed now as a separate commit that won't need to change when the new remote control code is committed later.

[HelpMenu.py] Tidy up the code

---

lib/python/Navigation.py
lib/python/Plugins/Extensions/StreamlinkWrapper/plugin.py
lib/python/Plugins/Extensions/YTDLPWrapper/plugin.py
lib/python/Plugins/Extensions/YTDLWrapper/plugin.py
lib/python/Plugins/Plugin.py
lib/python/Screens/ChannelSelection.py

* cleanup code
* rename zap to playService
* rename WHERE_CHANNEL_ZAP to  WHERE_PLAYSERVICE
* move the hook from ChannelSelection to Navigation

[Wrappers]

---

lib/python/Components/InputDevice.py
lib/python/Screens/Information.py

[Information.py]
- Prepare for updated "InputDevice.py" where the remote control indexes are moved from global variables to class variables.
- Prepare for the new "MountManager.py" screen by adopting matching names for disk labels where the word "Capacity" is now "Size" and the word "Mountpoint" is now "Mount".
[InputDevice.py]
- Move the global remote control index values to become class based values.

Prepare for more refactored code

---

lib/python/Screens/OScamInfo.py

- remove 'SSL: CERTIFICATE_VERIFY_FAILED' error on oscam webif with ssl certificate as OSCamInfo requests it on loopback interface address (127.0.0.1)

[OSCamInfo] skip certificate verification

---

lib/python/Screens/OScamInfo.py

introduced in https://github.com/openatv/enigma2/commit/67f4585e689121cac157615df9fad1433c840266

[OSCamInfo] fix webif authentication errors

---

lib/python/Screens/OScamInfo.py

[OSCamInfo] fix broken ncam handling

---

data/setup.xml
lib/python/Screens/OScamInfo.py

* [OSCamInfo] use BoxInfo to detect active softcam
* [OSCamInfo] validate hostname and ip address

[OSCamInfo] more freshups

---

lib/python/Screens/OScamInfo.py

- replace unsafe and slower code parts
- remove verfile not defined crash
- remove debugging remnants

[OSCamInfo] replace regex search with xml.etree

---

data/setup.xml

- Correct the new subtitles color option.
- Adjust a comment structure.

[setup.xml] Small grammatical correction

---

data/setup.xml
lib/python/Components/UsageConfig.py
lib/python/Screens/InfoBarGenerics.py
lib/python/Screens/ScreenSaver.py
lib/python/Tools/Migration.py

- Update and optimize the screen saver code.
- Add more screen saver start delay time options.
- Add a new configuration item to set the time between movement of the screen saver image.
- The old screen saver start timer will be migrated to the new config item.

[ScreenSaver] Update and enhance screen saver functionality

---

lib/python/Tools/Directories.py

- Improve the efficiency of the resolveFilename() method by eliminating non-existent directories from the list.
- Tidy up some code.
- Correct and/or improve some comments.
Developed by @jbleyel with a little help from @IanSav.

[Directories.py] Implement planned changes

---

lib/python/Components/MovieList.py

- Sort and optimize the imports.
- Remove the duplicate EXTENSION definitions and use the definitions directly from FileList.py.
- Ignore all JPEG files as they are often added as movie posters but should not be listed as extra media.
- Optimize and PEP8 some of the code.
- Use consistent quotation marks.
- Improve some logging messages.
- Improve some of the comments.
This is not a full refactor of the code though a more comprehensive refactor and optimization will probably be done later.
@jbleyel also contributed to the commit.

[MovieList.py] Improve and optimize the code

---

lib/python/Tools/Directories.py
lib/python/skin.py

* use different skinResolveList for xml files to support old skins

[Directories]

---

data/unicable.xml

Added a quite popular unicable LNB from Inverto. The IDLU-32L412-UNBRR-OPN.

Update unicable.xml with new LNB

---

lib/python/Screens/MovieSelection.py

- Optimize a few more code paths.
- CamelCase another local variable.
- Add comments for some more proposed text corrections that can not yet be implemented.

[MovieSelection.py] Clean up more code

---

include/hardwaredb.h

Hi @jbleyel 
Could you please check if it is correct and add this PR?
Here is SSD:
Fanxiang 1TB SSD PCIe 4.0 NVMe M.2 Internal Solid State Drive
/sys/class/block/sdd -> ../../devices/platform/soc/f9890000.ehci/usb1/1-1/1-1.4/1-1.4:1.0/host1/target1:0:0/1:0:0:0/block/sdd
/sys/class/block/sdd1 -> ../../devices/platform/soc/f9890000.ehci/usb1/1-1/1-1.4/1-1.4:1.0/host1/target1:0:0/1:0:0:0/block/sdd/sdd1

Add internal SSD for Octagon Supreme

---

lib/python/Components/FileList.py
lib/python/Plugins/Extensions/FileCommander/plugin.py

[plugin.py]
- Change method "checkStillExists()" method to also allow for the removal of broken links.
- Update the embedded skin to use an XML template rather than a Python template.
- Add the XML template dictionary.
- Rename "pathjoin" back to "join".
[FileList.py]
- Add a new overlay icon for broken links.
- Improve the logic an efficiency of the directory based icons and the link overlay icons.
- Update the file name for "link-arrow.png" to "link_arrow.png" to match the naming style of using "_" rather than "-".
- Move the static "EXTENSION_ICONS" dictionary to a class variable "extensionIcons" to allow for dynamic skin changes.
- Adjust the "FileEntryComponent()" method to keep the "FTPBrowser" plugin working.
- Rename "pathjoin" back to "join".

[FileCommander] Fix reported symbolic link issue

---

lib/python/Plugins/Extensions/FileCommander/plugin.py

Issue:
- create symlink
- delete target
- try to del, move, copy, info, menu, etc. for symlink.

[FileCommander] Fix's for broken symlinks.

---

lib/python/Screens/Information.py

Issue reported by GhostofGeeeee.

[Information.py] Correct displaytype code

---

data/setup.xml
lib/python/Components/SystemInfo.py

* show REC Symbol settings only if display skin exists
#3476

[setup.xml]

---

lib/python/Screens/InfoBar.py
lib/python/Screens/InfoBarGenerics.py

- hide swapPiP extension if unavailable
- better PiP support for EMC, IPTV plugins

[InfoBarPiP] showPiP() code improvement

---

lib/base/eerror.cpp
main/bsod.cpp

[BSOD] clear buffer if crashlog created

---

lib/python/Screens/VolumeControl.py

- Address the significant Sonar errors.
- Remove some defunct comments.
- Improve some standby debugging code.

[VolumeControl.py] Address Sonar issues

---

lib/python/Tools/MultiBoot.py

- Correct VTi version number detection and formatting.
- Update code to latest coding standards.

[MultiBoot.py] Correct VTi version number detection

---

lib/python/Screens/VirtualKeyBoard.py

Thanks to @DimitarCC for the information and prompt to add this mapping.

[VirtualKeyBoard.py] Add Bulgarian keyboard mapping

---

lib/python/Screens/OScamInfo.py

* see https://www.opena.tv/viewtopic.php?p=584037#p584037

[OScamInfo] * fix unbound variable

---

data/keymap.u80
data/keymap.xml
data/setup.xml
lib/python/Components/UsageConfig.py
lib/python/Screens/ButtonSetup.py
lib/python/Screens/InfoBar.py
lib/python/Screens/InfoBarGenerics.py

[setup.xml/UsageConfig]
* remove config.plisettings.ColouredButtons
[InfoBar]
* remove usage of config.plisettings.ColouredButtons
[InfoBarExtensions]
* remove usage of config.plisettings.ColouredButtons
* cleanup actionmap

InfoBar Cleanup

---

lib/python/Components/UsageConfig.py

Also add a comment to list the media navigation items that are planned to be removed.

[UsageConfig.py] Align with current development code

---

lib/python/Screens/Information.py

- Ensure all callbacks are callable.
- CamelCase some more variables.
- Remove a redundant import.

[Information.py] Small code improvements

---

lib/service/servicemp3.cpp
lib/service/servicemp3.h

* improve vtt subtitle support
* add doxy header

[servicemp3]

---

lib/python/Components/About.py

* needs https://github.com/oe-alliance/oe-alliance-core/commit/a7063343a018e334f8ac440fab54abcc4305313a

[About] * rework rust version check

---

lib/python/Components/About.py

- Optimize some of the methods.
- Use more meaningful variable names.
- Use uniform quoting.
- Improve logging text.

[About.py] Update code style and optimize some methods

---

lib/python/Screens/FlashManager.py

[FlashManager] * Allow /media/usb for FastRestore

---

lib/python/Screens/InfoBarGenerics.py

This new screen implements a whole new mechanism for seeking within media files.  Users access the new screen in the same way that they accessed the old "Seekbar" screen as the new screen is intended as a complete replacement.
The new screen is significantly more configurable and has an added HELP screen to show what actions are currently available for the settings and modes selected.
In the Playback settings some of the new options that were recently added now become active.
Firstly, the actions of the ARROW buttons is now configurable.  The "Arrow skip mode" setting has options of "Traditional" where the ARROW buttons act as they have always worked, "Symmetrical skips" where the sensibility percentage skips are applied, and "Defined skips where each ARROW button can be assigned to skip …

[InfoBarGenerics.py] Replace "Seekbar" screen with "SeekBar" screen

---

data/setup.xml

Move the setup blocks back into alphabetical order.

[setup.xml] Sort setup blocks

---

lib/python/Tools/Directories.py

- Remove debug log bloat from a debug line in the comparePaths() method.
- Use more f-strings, including in commented out code.
- Use a class for the resolve lists.  This change inspired by a commit made in OpenViX.

[Directories.py] Small code improvements
